### ISSUE TITLE
JSONata: A declarative syntax for querying your JSON data

### ISSUE THREAD

**Issue by andrew-coleman** [lnug/speakers#100]
JSON is becoming the de facto standard format for exchanging data between systems over the Internet.  Its key strengths are its lightweight syntax and its simple data model, which have helped propel it to be the dominant payload format in RESTful web services.

A lightweight data format deserves a lightweight query and transformation technology that is accessible to non-programmers.  [JSONata](http://jsonata.org) provides that in an open-source module that can be embedded in a web page or used in a node.js app.  Designed with the principle that queries should be simple to write, JSONata has a very shallow learning curve. Yet sophisticated expressions can be quickly mastered by combining the simple navigation syntax with a rich set of operators and functions for extracting, manipulating and aggregating JSON data. 

This session will introduce you to JSONata and show you how to find buried treasure in your JSON data.

Andrew Coleman is a senior software engineer at IBM specialising in data transformation and application integration.  He is currently building a graphical data mapper for [integrating cloud based services](http://www-03.ibm.com/software/products/en/ibm-app-connect).

Andrew is the Chair of the [W3C XML Query Working Group](https://www.w3.org/XML/2015/05/query-charter.html) responsible for developing the [XPath](https://www.w3.org/TR/xpath-31/) and [XQuery](https://www.w3.org/TR/xquery-31/) family of specifications.  He has borrowed heavily on the experience gained from this to create the [JSONata](http://jsonata.org) query and transformation language for JSON.

**Comment by jkbits1** [comment]
@andrew-coleman @admataz thanks, this sounds very interesting. Do you have some scenarios to show the audience how it relates to Nodejs ?

**Comment by andrew-coleman** [comment]
Yes, I plan to demonstrate this running in Node-RED.  The latest version of [Node-RED has adopted JSONata as its expression language](https://nodered.org/blog/2017/01/11/version-0-16-released#jsonata) to allow users to create node.js apps without having to write large amounts of code.  It's a good example of how JSONata can be used both in the browser and in node.js.  It also follows on nicely from Tony Yates's excellent talk at the last meetup where he demonstrated Node-RED running on a Raspberry Pi.

**Comment by admataz** [comment]
Hi @andrew-coleman 

Nice to meet you on wednesday - and thanks for this talk proposal - I agree - a good follow on from Tony's talk, and a suitable hands-on topic for a talk. 

Is April 26th ok for you?

**Comment by andrew-coleman** [comment]
Hi @admataz - yes, that sounds good.  Thanks!

**Comment by admataz** [comment]
Hi @andrew-coleman  - are you all good for your talk tomorrow?

**Comment by andrew-coleman** [comment]
Yes - all good, thanks.  See you tomorrow.
