### ISSUE TITLE
Automatically build and publish Node and Electron applications for Linux

### ISSUE THREAD

**Issue by flexiondotorg** [lnug/speakers#101]
An introduction to snapcraft.io and electron-builder, tools that enable you to deliver your Node and Electron applications to millions of Linux users. Packaging for Linux used to be hard, that has changed. The Snapcraft team have built a platform that makes it simple to build and publish your applications so they run on all the major Linux distributions. It gives you  tools to deliver updates at a high frequency without compromising stability. Push a commit and it will automatically build for free in the store for your users.

Martin WImpress is a passionate Open Source advocate, Linux enthusiast and Podcaster. Lives in Hampshire, England, with his wife and daughter. Works at Canonical making Ubuntu and Snapcraft. Martin is [@m_wimpress](https://twitter.com/m_wimpress) on Twitter.

**Comment by admataz** [comment]
Hi Martin, 
Thanks for your proposal - and nice to meet you on Wednesday. This looks good. 

Apart from the introduction to what it is and the philosophy behind snapcraft - if it's possible I think our audience will really enjoy a practical walk through the capabilities -  how to deploy a simple node/electron app - and maybe mentioning any of the specific challenges/opportunities we may  face with our stack.  

Would it be possible to shape your description above to reflect a more specific focus on the node/js developer's experience?

**Comment by admataz** [comment]
hi @flexiondotorg
any thoughts on the above? keen to schedule you in for Aprils meetup on the 26th. are you able to do that date?

**Comment by admataz** [comment]
@flexiondotorg  - as discussed - accepted and confirmed! pls add a comment here if/when you update the description

**Comment by admataz** [comment]
HI @flexiondotorg  - just checking in  - all good for your talk tomorrow evening?

**Comment by flexiondotorg** [comment]
@admataz All set.
