### ISSUE TITLE
How Bionode.io uses Node.JS Streams to handle genomic big data

### ISSUE THREAD

**Issue by bmpvieira** [lnug/speakers#102]
Bionode.io is an open source community. We aim to provide highly reusable code and tools for genomics by leveraging the Node.JS ecosystem. We are big fans of Node.JS Streams! I will talk about what they are and how you can use them to process large data in chunks.

Bruno Vieira | @bmpvieira
PhD Student in Bioinformatics at WurmLab.github.io (Queen Mary U. of London)
Mozilla Science Lab fellow and Founder of Bionode.io

**Comment by admataz** [comment]
yes! I've been looking at streams a lot recently with some vague and abstract ideas for implementation. A talk on how you are using node and streams for processing data would be amazing.

**Comment by admataz** [comment]
@bmpviera  - can you talk this month? 26th april

**Comment by bmpvieira** [comment]
yes @admataz, that would be perfect! I spend more time in Portugal now but I'll be in London 26-29 this month. Thank you!

**Comment by admataz** [comment]
fantastic... your on.

**Comment by admataz** [comment]
HI @bmpvieira  - hope all is well with you? all good for tomorrow?

**Comment by bmpvieira** [comment]
Hi @admataz, all good thanks, see you tomorrow!
