### ISSUE TITLE
Speeding up CI with node and docker

### ISSUE THREAD

**Issue by willm** [lnug/speakers#103]
Tips for running faster builds with nodejs and docker. This talk mainly outlines lessons learned and optimisations which will hopefully help you get quicker feedback from your CI pipeline and make your deployments run quicker.

Although I have more experience in the back end side of things, I strive to be a full stack developer. I like working on well tested codebases with a well oiled CI pipeline

**Comment by willm** [comment]
I've made a start at some notes for this talk if you'd like to see it https://github.com/willm/speed-up-ci-talk/blob/master/speed-up-ci.md

**Comment by jkbits1** [comment]
@willm this sounds ideal 👍 thanks for the notes. 

I'd love to see something on integrating a nodejs docker setup with CI.

I use the alpine builds for my various development docker machines and add in steps to install git and tiny vim. Some quick thoughts and tips on the differences between debian and alpine would certainly appeal to me (and others, too I'm sure). 

Our audience does consist of a wide range of devs, though, so for many of them an introduction to the basic concepts is what's needed. When can you speak? We have slots available for May 24 and June 28.

**Comment by willm** [comment]
Hi, I could do the 24th of may. I haven't done a talk like this before though, so hopefully it will be OK :)

**Comment by willm** [comment]
Hi just wondering if you've scheduled this, Should I prepare this for the 24th of May?

**Comment by admataz** [comment]
hi @willm  - I've added your talk to next month's schedule! 

>  I haven't done a talk like this before though, so hopefully it will be OK :)

It will be great! If you need feedback in your preps - be sure to reach out - we'll be glad to provide some helpful comment.

**Comment by jkbits1** [comment]
@willm looking forward to your talk. As @admataz says, just let us know if you want feedback etc, we are always happy to help

**Comment by willm** [comment]
Thanks, I'm going to do some work on it this weekend which I'll share with you for feedback.

**Comment by willm** [comment]
Hi all, I've started making some slides for my talk. There's not much yet, but if you'd like to have a look at what I've done so far, check out [my slides](https://slides.com/willmunn/faster-ci-with-node-and-docker)

**Comment by jkbits1** [comment]
@willm that's great! I'll take a look

**Comment by jkbits1** [comment]
Hi @willm the slides look good 👍 it comes across that you have experience with CI and have some useful points to make. It looks like you plan to add some more slides (entirely your choice, though) and I'm definitely interested to see where they go and to learn some good tips for my own set-ups

**Comment by admataz** [comment]
Hi @willm 
Just checking in and confirming you're all ok for Wednesday? Do you need any more feedback or review on your talk prep? (looking good so far from what I've seen)

Let us know if you need anything - otherwise see you there  - we will be setting up from around 6pm

**Comment by willm** [comment]
Hi @admataz, yes I'm all set, need to finish it off this evening. I'll see you there tomorrow :)

**Comment by admataz** [comment]
Thanks for the talk @willm. video uploaded to https://youtu.be/USiUNWVrDYo
