### ISSUE TITLE
From LNUG presentation to published book - my tale of writing "Cross Platform Desktop Applications"

### ISSUE THREAD

**Issue by paulbjensen** [lnug/speakers#104]
3 years ago I gave a talk at LNUG on Node Webkit, and then posted online. Little did I know that the end result would be writing a book for Manning publications on Electron and NW.js.

This talk is about how that happened, the process of writing a book about those Node.js frameworks, and the learnings from undertaking the whole project. 

My name is Paul Jensen, and I'm a Senior Pre-Sales Consultant at Starcount. My Twitter handle is @paulbjensen.

**Comment by admataz** [comment]
Hey @paulbjensen  - welcome back!

And congrats on the publication of your new book!  This sounds like it has all the elements of a good story and talk - and with a happy ending too! It would be great to hear how it all came together - and I think it would be be a brilliant motivator for members to hear how contributing and sharing knowledge and putting yourself forward in the community can have positive spinoffs - lessons and hard work included.

I see you are about to release - our next meetup is 24th May and there are speaker slots available. How does this suit you?

Aside: Do you have a standard press release or some info we can put into our newsletter? - also would your publisher consider donating a copy for a raffle on the night? And of course bring along a couple copies  - you may find a willing buyer too. 

cc. other @lnug/organisers  - any thoughts?

**Comment by orliesaurus** [comment]
congrats on the publication

**Comment by admataz** [comment]
Hey @paulbjensen  - how are you for 24th May? can you confirm?

**Comment by paulbjensen** [comment]
@admataz Yes, I can do that date if it's still an option?

**Comment by admataz** [comment]
Good stuff! you're on! I will update the website and meetup page now

Let us know if you want to run any part of your talk past us for feedback - we'd be glad to help

**Comment by paulbjensen** [comment]
PS - I'll donate a copy to the raffle.

**Comment by admataz** [comment]
thanks @paulbjensen - that's brilliant

**Comment by admataz** [comment]
Hi @paulbjensen 
Just checking in and confirming you're all ok for Wednesday? Do you need any feedback or review on your talk prep? 

Let us know if you need anything - otherwise see you there  - we will be setting up from around 6pm

**Comment by paulbjensen** [comment]
Hi, @admataz,

Yes, all good. I will post slides for review, hopefully by end of Tuesday. I've got a mid 2014 13" MacBook Pro to present on with Keynote installed, is that fine to run the deck on?

**Comment by admataz** [comment]
Thanks @paulbjensen  - that should be good - I'll have a couple display adapters there just in case. Worst case we can transfer your keynote to another mac  - it's only sometimes complicated if you have some live code to run... See you Wednesday

**Comment by admataz** [comment]
Hi @paulbjensen  - thanks for a great talk last month. 
Video uploaded to our youtube channel: https://youtu.be/TCAQLu4IYUs
See you again at lnug!
