### ISSUE TITLE
Trading cryptocurrencies, forex, commodities stocks and more using node.js

### ISSUE THREAD

**Issue by flyingunicorn222** [lnug/speakers#105]
Description: The aim of the talk is to show what i have learnt and the libraries and tools i have developed over the last couple years after getting into trading bitcoin and ethereum, which turned out later into trading all sorts of things based on technical analysis and a bit of flaky statistics. I'm really bad at making graphs and charts and what not, so expect some hands on approach, the talk should cover the very basics of trading and then how to use trading APIs to actually buy and sell stuff online directly from your command line.

About me: The first time i programmed javascript was twenty years ago and since them i have played around with pretty much all the interesting programming languages i have found in front of me just to discover in 2011 i would actually end up doing everything again using only node.js. During this long journey i have worked on backend and frontend applications, interactive games, multiplayer applications, and whatnot. The last few years my big interest turned to be blockchain, cryptocurrencies and trading. After moving to London nearly seven years ago i worked for a few years in a very nice design studio and then later left to create my own little technology company where all those crazy experiments happen.

**Comment by admataz** [comment]
@flyingunicorn222  - sounds good - I'd be interested to hear about these uses of node - especially something hands on. We have a slot available for next week's meetup (Wednesday 24th May) are you interested in taking it?

@lnug/organisers  - anyone else have any thoughts - want to second the proposal?

**Comment by flyingunicorn222** [comment]
@admataz there are a few ways i used node.js in these projects:

1 - Integrating with Exchange APIs, so basic dealing with GET/POST requests in order to fetch market data almost no exchange provide real time data for the kind of data i judged to be useful

2 - Dealing with chart data and technical analysis library, like http://ta-lib.org/ and https://www.npmjs.com/package/ta-lib

3 - Creating a dashboard to visualise data, this was done using meteor.js and highcharts, there are other chart libraries that can be talked about like D3 and Techlist

4 / 5 - i might talk about other ways i used node.js depending on how much time we have in there!

For the hands on approach of showing this we will just need a browser and a command line and a projector, i know you guys will have a projector there the command line and browser can be provided by me (( :

Next Wednesday i'm game!

**Comment by admataz** [comment]
great stuff, sounding even better!  you have 20-25 minutes - get in as much as you can!

**Comment by jkbits1** [comment]
@admataz @flyingunicorn222 definitely sounds like enough to keep the audience interested 👍

**Comment by admataz** [comment]
@flyingunicorn222  - confirmed and added to the schedule - do you want to add any twitter details or name/bio? (your choice)

**Comment by admataz** [comment]
Hi @flyingunicorn222 
Just checking in and confirming you're all ok for Wednesday? Do you need any feedback or review on your talk prep? 

Let us know if you need anything - otherwise see you there  - we will be setting up from around 6pm

**Comment by flyingunicorn222** [comment]
hey guys, sorry i didn't see this notifications before!

thanks for having me and for the beers and pizzas, was a massive pleasure to speak to such nice audience!

hope to see you all soon!

**Comment by jkbits1** [comment]
@flyingunicorn222 thanks again for a great talk! The audience really loved your talk and speaking to you afterwards

**Comment by flyingunicorn222** [comment]
very happy to hear that!

One note i would like to do is since the talk end up deviating to talking more about blockchain, charts and trading crypto with node.js i would suggest we use the following title for the video recording "Blockchain, charts and crypto trading using node.js"

**Comment by admataz** [comment]
Hi @flyingunicorn222  - thanks for the talk last month. The video is busy uploading to our youtube channel: https://youtu.be/JmzWD038qtM

Hope you're well - see you at a meetup soon

**Comment by guidsen** [comment]
Hey @flyingunicorn222 I loved your talk! I'm really interested in more of this. I'm thinking of writing my own trading bot as well that also does some kind of analysis what the impact of ETH/BTC value changes is on other upcoming crypto currencies for example Litecoin etc. Unfortunately you had not enough time to explain this further.
