### ISSUE TITLE
async_hooks - tracing the event loop

### ISSUE THREAD

**Issue by overlookmotel** [lnug/speakers#106]
async_hooks, a new feature in Node 8, lifts the lid on the core of Node's workings - the event loop - and allows you to inspect (and play with) async callbacks.

In this talk, I'll explain what async_hooks is, and how you can use it to ease debugging with long stack traces, trace call stacks, store data associated with a single HTTP request in an express app without having to pass around the `req` object, and all kinds of other goodness. And, if you're a module author, how to support async_hooks in your code.

I run a small company, Cinebox, who provide technical management for film festivals across the UK, with the help of a web-based platform which (of course) runs on Node. http://www.cinebox.co/ Twitter: @cineboxfilm

**Comment by jkbits1** [comment]
@overlookmotel this sounds excellent, I'd definitely like to hear more about this

**Comment by overlookmotel** [comment]
@jkbits1 What else would you like to know about the talk? Or did you mean you'd like to hear more about async_hooks and so think the talk sounds good?!

**Comment by jkbits1** [comment]
@overlookmotel the second one 😄 Did you have some dates in mind for giving the talk at LNUG?

**Comment by admataz** [comment]
Hi @overlookmotel  - this looks great we're just working out our schedule for speakers in the coming months - do you have any specific preference or availability over June/July?

**Comment by admataz** [comment]
Hi @overlookmotel  - looking more into what you're doing with cinebox - I think it would be a great talk if you could also bring a little into it about the cultural/business context and the choice of using node for what you're doing. 

Any film buff angle an added bonus to the entertainment value

**Comment by overlookmotel** [comment]
I think I've got a work thing on the June date, so I think would have to be July.

Great that you're interested in what I'm doing with Cinebox and there are some things in that which it could be interesting to delve into - in a sense what I'm doing is a classic case of "market disruption" in an industry that is surprisingly stuck in its ways. But I feel that's another talk entirely! async_hooks is a pretty complicated subject with lots of angles - so I feel to do it justice, it'd need the full length of the talk without diversions (beyond a quick "this is who I am" at the start).

**Comment by admataz** [comment]
agree - not to dominate with business strategy.  I was just suggesting a just a small hook to the real world context to the use of JS and node - in a way that helps devs from all levels relate to your talk ("this is who I am" may well do that enough)

**Comment by admataz** [comment]
Ok, scheduled you for July 26th - if you end up with a preference for June 28th (2 weeks time) there is a slot still available, but let us know asap!

**Comment by admataz** [comment]
Hi @overlookmotel  - hope you are well

Can I confirm you for your LNUG July 26th?

**Comment by admataz** [comment]
Hi @overlookmotel  - just a *bump* 

> Can I confirm you for your LNUG talk July 26th?

**Comment by overlookmotel** [comment]
Sorry I've been silent. Crazy busy past month.

I'm afraid I don't think I can do July 26th. It turns out that there's been a few teething problems with async_hooks and Promises which are still being worked out. I'm keen to do this talk but I think it'd be better to hold off until the situation has stabilised so the content doesn't become swiftly out of date!

**Comment by admataz** [comment]
thanks for letting me know - yeah it's been crazy busy my side too. no worries, I'll unschedule the talk and we can pick it up in the future.

**Comment by admataz** [comment]
HI @overlookmotel  - any thoughts on reviving this talk idea?

**Comment by admataz** [comment]
Hi @overlookmotel  - I hope you're well? I'm going to close this - but please feel free to reopen when you have some time
