### ISSUE TITLE
Node microservices at Pizza Hut

### ISSUE THREAD

**Issue by lithin** [lnug/speakers#108]
**Abstract**
Pizza Hut website is powered by a system of 20+ microservices, all docker-ised and running in AWS. What challenges did we meet while writing it? How do you maintain, develop for, and test a system with extremely high availability on such a scale? It's a bit like juggling twenty fragile glass balls while riding a bicycle. Nevertheless, it's a surprisingly reliable way of delivering the best user experience, and pizza, to our users.

**More info**
I'll introduce our (complex) infrastructure and will talk a bit more about challenges we have faced and how we solved them.
1. Splitting logic into microservices; changes made into several microservices at once & deployment.
2. Testing our huge products API; running over 20000 unit tests on one microservice, we need to micro-optimise.
3. Making sure it actually works; a system of logging, monitoring, and support

**About me**
I'm a software engineer at Pizza Hut (contractor), speaker, node and react developer. Previously worked at Red Badger and Time Out. I recently spoke at JeffConf, React London 2017, several meetups.
Twitter handler: [@lithinn](https://twitter.com/lithinn)

**Comment by jkbits1** [comment]
@lithin thanks for this, it would be a fantastic talk! We'd love to have you speak at LNUG, and the possibility of free pizza and some sponsorship is excellent

**Comment by admataz** [comment]
Hi @lithin  - great to meet you the other day at FullStack conf. 

This is great - thanks for the super talk proposal 

As discussed - I'll schedule you to speak for our August meetup. Let's talk in the month about arrangements etc. 

- Adam

**Comment by lithin** [comment]
Thanks! Which day is it going to be @admataz ? I'll put it in my calendar so I don't forget ;)

**Comment by jkbits1** [comment]
@lithin we always meet on the 4th Wednesday of the month, so August 23. Really looking forward to your talk

**Comment by lithin** [comment]
Awesome! Really look forward to joining you there :)

**Comment by admataz** [comment]
Great stuff. Thanks Anna - All scheduled and confirmed for August 23rd. Look forward to it

**Comment by admataz** [comment]
Hi @lithin 
I hope you're well? Just confirming... all good for your talk this Wednesday?

**Comment by lithin** [comment]
Yup all good @admataz :) See you Wednesday!

**Comment by admataz** [comment]
Hi @lithin  - thanks again for coming along to LNUG and providing a great talk last night. The feedback I've had has been 100% good - and I think it was a great night of networking. Hopefully see you back at LNUG soon! I'll let you know as soon as the video is up and ready. Best, 
Adam

**Comment by claireinez** [comment]
Really great talk @lithin! And sounds like it came at a very relevant time for a lot of the attendees :)

**Comment by lithin** [comment]
Awesome, I'm glad people found it interesting :)

**Comment by lithin** [comment]
https://www.slideshare.net/AnnaDoubkov/node-microservices-at-pizza-hut - slides here :)

**Comment by admataz** [comment]
Hi @lithin - I hope all is well? 

Video is finally in the August 2017 playlist on our youtube channel: https://www.youtube.com/watch?v=Hnyik7oi-Mk&list=PLam_80-FY3vRb_4L80ydyNuNXR-sWO-D-

🎉
