### ISSUE TITLE
Do not yield to javascript generators!

### ISSUE THREAD

**Issue by BrunoGodefroy** [lnug/speakers#109]
**Abstract** Have you ever found yourself completely lost in front of a yield statement? What is this? Where does my promise go? How come I get the result back?

Generators are widely used amoung Node and javascript libraries to enable developers to write powerful code in a simple way.

I will try to answer all these questions and we will recreate together the [co library](https://github.com/tj/co) that is used, for example, in [Koajs](https://github.com/koajs/koa).

I would then like to go into a step by step decomposition of [redux-saga](https://github.com/redux-saga/redux-saga) to understand how this wonderful library uses generators.

**A bit about me** I'm a full stack developer at Theodo UK, a web agency in central London. We help our clients to solve their business problems through code. Our clients range from young startups to large corporates.
Twitter: [@switcher7707](https://twitter.com/switcher7707)

**Comment by lazlojuly** [comment]
Hi Bruno,

First of all, thank you for your proposal!

I have a few questions / suggestions if you don't mind:

- Have you done this talk before?
- Are you planning to do a similar exercise as Mattias did on his channel: https://youtu.be/ategZqxHkz4 ?

Our audience consists of a wide variety of developers and tech enthusiasts. If you would like to provide really good value it maybe better to do a focused and slower paced talk on either generators in general or on redux-saga only. Obviously, redux-saga could still include explanation of generators but I feel like introducing generators, reimplementing co, dissecting saga and everything around it might take a lot longer than planned.

**Comment by lazlojuly** [comment]
Also, would 23rd of August be suitable for you?

**Comment by admataz** [comment]
Hi Bruno, this is great - thank you... and great advice from @lazlojuly. I agree - keeping it focused will help you fit everything in.

**Comment by BrunoGodefroy** [comment]
@lazlojuly @admataz The 23rd of August is perfect for me!

I have already given this talk in front of my colleagues at Theodo UK. The talk lasted around 40 minutes and I had pretty good feedbacks: a lot of them were surprised about how easy it is to rewrite co.

I was planning to do a live coding that is indeed very similar to what Mattias did on his channel. My implementation is a bit different but the idea of the live coding is the same.

I can of course drop the last part to make the talk a little shorter and easier to follow, how long should I aim for?

**Comment by lazlojuly** [comment]
@BrunoGodefroy 20-25 minutes with easy to follow pace.

**Comment by admataz** [comment]
thanks @lazlojuly. could you run a build and push an update to the website so this gets published there? otherwise  i'm on the move till this evening and can do it then.

**Comment by admataz** [comment]
Hi @BrunoGodefroy  
I hope you're well? Just confirming... all good for your talk this Wednesday?

**Comment by BrunoGodefroy** [comment]
Hi @admataz 
Yes everything is good for my talk!
At what time should I arrive? 6:30pm?

**Comment by admataz** [comment]
Great - thanks @BrunoGodefroy  - yes 6:30 will be great

**Comment by BrunoGodefroy** [comment]
Ok see you there!

**Comment by admataz** [comment]
Hi @BrunoGodefroy  - thanks for a great talk last night - and for coming along and sharing your knowledge. All the feedback I had has been very positive - and people were very impressed with your live coding bravery! I'll let you know when the video is ready and online. Hopefully see you back at LNUG soon! Best, Adam

**Comment by admataz** [comment]
Video is finally in the August 2017 playlist on our youtube channel: https://www.youtube.com/watch?v=Hnyik7oi-Mk&list=PLam_80-FY3vRb_4L80ydyNuNXR-sWO-D-

🎉
