### ISSUE TITLE
Rapid web development with Huncwot & Marko

### ISSUE THREAD

**Issue by zaiste** [lnug/speakers#110]
**Abstract** [Huncwot](https://github.com/zaiste/huncwot) is an opinionated & minimal Node.js (yet another) web framework, slightly inspired by Clojure and built for ES6/7 era with « batteries included » approach. It tries to formalize conventions and eliminate choices by providing solid defaults for building web applications that increase the programmers productivity. In this talk we'll explore how to build an application with Huncwot, what it brings to the table and how to make (web) programming more approachable, especially to non-programmers.

**A bit about me** I run a software company called [Nukomeet](https://nukomeet.com/). In my spare time I organise [PolyConf](https://polyconf.com/). Twitter: [@zaiste](http://twitter.com/zaiste)

**Comment by admataz** [comment]
hi @zaiste - this sounds really interesting. I'd love to hear more about  the design decisions behind huncwot and how it leverages some of the new features available to node and js. 

how are you fixed for a talk for 27 september?

@lnug/organisers - any thoughts?

**Comment by zaiste** [comment]
hello @admataz thank you! I'll be outside of Europe after Sep 22th. Would you be willing to consider this proposal for the upcoming event in August ?

**Comment by admataz** [comment]
hi @zaiste - it's possible we can fit you in for august if you can't make september - how long is your talk? can you keep it to 20-25 minutes?

**Comment by lazlojuly** [comment]
@zaiste thank you for your proposal, it could be an interesting closing talk of the night.

It would be great to hear about the concepts you took from Clojure and how ES6 and 7 is built into your the framework. 

@admataz I agree, as this would be the 3rd talk of the night it should be kept brief... 
20 minutes long talk is preferred as being the last talk of the night...

**Comment by zaiste** [comment]
@admataz @lazlojuly thank you for this, I appreciate your flexibility. I initially planned a 20 minutes long talk.

**Comment by admataz** [comment]
Great stuff - you are confirmed and on the schedule! See you there

**Comment by zaiste** [comment]
@admataz thank you!

**Comment by admataz** [comment]
Hi @zaiste  
I hope you're well? Just confirming... all good for your talk this Wednesday?

**Comment by zaiste** [comment]
hi @admataz Yes, it's all good, thank you. I will also provide slides earlier i.e. tonight or tomorrow morning

**Comment by admataz** [comment]
Hi @zaiste  - thanks for coming along and providing a great talk last night - it was great to have you. I'll let you know as soon as the video is ready and online. For your polyglot events - please let me know details and I can share them in our newsletter and tweets. Hopefully see you back again soon!

**Comment by zaiste** [comment]
@admataz Once again thank you for having me! I hope you've already finished the bottle ;) Would you mind we continue via email regarding those polyglot events ?

**Comment by admataz** [comment]
Hi @zaiste - I hope all is well with you?

sure!  email me at adam@admataz.com

btw: 
Video is finally in the August 2017 playlist on our youtube channel: https://www.youtube.com/watch?v=Hnyik7oi-Mk&list=PLam_80-FY3vRb_4L80ydyNuNXR-sWO-D-

🎉
