### ISSUE TITLE
Hapi + Nes + MiniMongo for gloryful reactive apps

### ISSUE THREAD

**Issue by alanshaw** [lnug/speakers#111]
Ever used Meteor with React? What does it take to recreate the same reactive pub-sub experience using [Hapi](https://hapijs.com/), [Nes](https://github.com/hapijs/nes) and a [MiniMongo](https://github.com/kofrasa/mingo) library? Turns out, not a lot. Introduckting Nesquirk - a small lib built to give new life to your frontend, without having to re-write your Hapi+Mongo based backend.

In this talk I explain the merits of the reactive pub-sub experience in Meteor, live coding an example to show how frustrating stale data can be when using a simple JSON HTTP API.

I then live code a similar app, using Hapi, Nesquirk and React to show how you can bring Meteor's reactive pub-sub magic to your Hapi app without having to rewrite from scratch.

I am a recently time-poor developer working at [TABLEFLIP](https://tableflip.io/). I used to think I was time-poor but then I had a child and I realised I had no idea what I was talking about. I'm [@_alanshaw](https://twitter.com/_alanshaw) on the Twitters or @alanshaw on the Githubs. I sometimes code things in this language called JavaScript, you might have heard of it. TABLEFLIP ❤️ to build awesome apps for startups and entrepreneurs. I help out with the [Nodebots London](https://www.meetup.com/NodeBots-of-London/) and [Meteor London](https://www.meetup.com/Meteor-London/) meetups sometimes and built this website called https://david-dm.org/.

**Comment by admataz** [comment]
Yes! - this sounds great 👍  

Would love to have you back for an LNUG talk -  how are you for September 27th?

lol - "time-poor..." - I know the feeling

**Comment by alanshaw** [comment]
Yes I can do the 27th Sept

**Comment by admataz** [comment]
Hi @alanshaw -  are you still good for your talk on Wednesday? Looking forward to seeing you there.

**Comment by alanshaw** [comment]
Yep, can't wait!

**Comment by admataz** [comment]
Hey Alan 

Thanks for the talk and contributions last week - I think it was a fun night. 

I'll post here with the link to the video when it's available. 

Speak soon...

**Comment by admataz** [comment]
been there a while - https://www.youtube.com/watch?v=0QEQn9v3OJI

Happy New Year!
