### ISSUE TITLE
Having your Node.js Cake and Eating It Too

### ISSUE THREAD

**Issue by robtweed** [lnug/speakers#112]
Rob's article on the [QEWD.js](https://github.com/robtweed/qewd) project was recently [published in the Node.js Foundation's Collection](https://medium.com/the-node-js-collection/having-your-node-js-cake-and-eating-it-too-799e90d40186). 
 In this presentation, he will expand on the themes discussed in his article, in particular how the architectural design of QEWD.js creates a unique run-time environment that provides a solution to some of the concurrency-related problem areas of Node.js such as CPU-intensive and long-running code.

Rob Tweed ([@rtweed](https://twitter.com/rtweed)) is a Director of M/Gateway Development Ltd,  a consultancy and software development company in the UK that has focused on web and NoSQL database technologies, particularly in the healthcare industry, since the mid-90s.  Rob has been an attendee of LNUG since its earliest meetings - indeed he gave a presentation at the very first meeting in 2011!

**Comment by admataz** [comment]
Thanks Rob for your talk proposal - This is a great topic and a great project - really looking forward to hearing this talk. 

Adding to September's line-up. 

Any thoughts @lnug/organisers ?

**Comment by jkbits1** [comment]
This is certainly an intriguing perspective on how best to use Node. The talk should provide the audience with useful details of how things work under the surface

**Comment by orliesaurus** [comment]
Awesome!

**Comment by admataz** [comment]
Hi @robtweed  - all good for this wednesday? Looking forward to seeing you there

**Comment by robtweed** [comment]
Hi Adam

Yes I’ll be there!  Will be working on the presentation slides later today :-)

Looking forward to it

Regards

Rob

**Comment by robtweed** [comment]
BTW my Twitter handle is @rtweed (though it's robtweed on Github, just to be confusing!)

**Comment by admataz** [comment]
Hi Rob, 
Thanks for a great talk last week. I think it was a good night all round... 

Hopefully see you again soon. 

I'll post here when the video is available online...

**Comment by robtweed** [comment]
Thanks Adam - I enjoyed giving the talk.  It was a fun evening.  I'm going to try to get along to the next one this month. See you there hopefully!

**Comment by admataz** [comment]
Happy New Year! Hope you're well...
This has been on our channel for a while - just cleaning up the open issue. https://www.youtube.com/watch?v=2P46Qc2z1xo
