### ISSUE TITLE
Scalable Scraping in Node and a bit of GO

### ISSUE THREAD

**Issue by sp3c1** [lnug/speakers#113]
A story of moving a monolithic Python Twisted application into NodeJs and micro services. Will discuss what problems we have faced, how we resolved particular issues and arrived at truly modular structure on AWS. Will highlight pain points and place we see for future improvements. 

Bartlomiej Specjalny, Lead NodeJs Software Engineer at Pad Innovation Limited,  a fullstack software engineer with background in computer graphics and multimedia.

**Comment by admataz** [comment]
Hey @sp3c1  - thank you for your talk proposal. 

Sounds like an epic journey! Would  be good to hear some of the battles you have endured and the insights you have gained. 

My only advice would be to make sure you keep your talk accessible to devs who may not be familiar with your particular stack or problem domain - and highlight some of the generic learnings/patterns you can extract from your experience. 

How are you fixed for a talk on 25th October ?

@lnug/organisers  - anyone else like to add some thoughts?

**Comment by sp3c1** [comment]
Hi on holidays till 11, might be late with replies.

Yeah 25 October sounds ok. But I will then start work for a different company pad.co.uk

Sure will discuss more of an architecture choices for overall and maybe in a bit more detail one of the process that is more interesting (multiple process, non blocking event loops, distributed locks, a bit about pitfalls and node c++ extension attempts(really general))

**Comment by admataz** [comment]
Ok that's great - you can update your initial post with details of your new job before we publish it on meetup and the website.

**Comment by sp3c1** [comment]
yeah, will do as soon I sign papers ;] If it wont happen before announcement we can go with Flubit

new one gonna be:
`Lead NodeJs Sofrware Engineer at Pad Innovation Limited`

**Comment by admataz** [comment]
👍  great - thanks. so confirming for October - we will only update details closer to the next meetup on the 27th - so let me know when you're ready

**Comment by admataz** [comment]
Hi @sp3c1  - going to announce your talk at tomorrow's meetup and will update the website soon after - do you want to update your profile in the talk description?

**Comment by sp3c1** [comment]
yeah, can update, if you had not announced so far

**Comment by admataz** [comment]
@sp3c1  - just confirming - you still good for your talk this Wednesday?

**Comment by sp3c1** [comment]
be all means ;]

**Comment by admataz** [comment]
Hi @sp3c1  - thanks for your talk last night - it was great to hear your story! I hope you had a good evening and a chance to chat and meet with a few of the other developers and got some worthwhile conversation and feedback out of it... 

I'll update this issue when we have the video available online.

Thanks again - and hopefully see you again at the next meetup!

**Comment by sp3c1** [comment]
Hi @admataz , 

hope i didnt crush the young minds too much :D (or get them borred for the matter)

**Comment by MattJLeach** [comment]
Hi @sp3c1 
I can only speak for myself but I thought is was a great talk. Some of it was above my head a bit but very interesting. Well done

**Comment by admataz** [comment]
Happy New year! - hope you're well. Just cleaning up old issues. Video is available here: https://www.youtube.com/watch?v=7gCKAfrlkAk
