### ISSUE TITLE
Taking LNUG offline

### ISSUE THREAD

**Issue by simonmcmanus** [lnug/speakers#114]
The LNUG website uses AppCache with the help of [app-cache-nanny](https://github.com/gr2m/appcache-nanny) but with its upcoming [depreciation](https://www.fxsitecompat.com/en-CA/docs/2015/application-cache-api-has-been-deprecated/) I’ve been investigating how Service Workers might improve the experience.

In this talk I will explain how the LNUG website gets built, how it uses appCache / service workers and some of the things I’ve learned along the way.

I'm a remote Javascript engineer, part time conference organiser and my opinions can often be found on twitter: [@simonmcmanus](twitter.com/simonmcmanus).

**Comment by admataz** [comment]
yes! thanks @simonmcmanus  -  we've been waiting a while for this talk!

There's space in October and November so far - any preference? 

@lnug/organisers  - any feedback or thoughts?

**Comment by jkbits1** [comment]
Hi @simonmcmanus @admataz definitely looking forward to this talk, excellent content and a great speaker 👍 

Use of service workers is increasing, I'm very interested to see they have been applied to an established application that I've been familiar with for a while

**Comment by simonmcmanus** [comment]
If I can get the November slot that give me a little bit more time to prepare. (sorry to make you wait even longer @admataz :) )

**Comment by admataz** [comment]
Hey @simonmcmanus  - great to see you last night. You're locked in for November! Let us know if you want  any feedback on your talk preparation...

**Comment by simonmcmanus** [comment]
Good to see you too @admataz - Is there anything you would like me to go into about how the LNUG site works?

Anything that people find confusing?

**Comment by admataz** [comment]
Hey @simonmcmanus  - a couple thoughts - take/leave as you think is relevant -  I think apart from the technical discussion it would be a good opportunity to try encourage contributions. 

- a very brief overview of how the site grabs data from github issues
- the process/path data goes through from source -> build -> cache (or however it actually works)
- some broad mention of different/other methods of developing offline experiences 
- opportunities in the codebase for contribution from community (maybe before the talk we can prune and optimise https://github.com/lnug/website/issues with some real actionable features)

**Comment by simonmcmanus** [comment]
@admataz - Im going to go over the issues this week and will let you know once they have been updated. 

I notice we have some lightning talks this month too, how long would you like my talk to be?

**Comment by admataz** [comment]
HI @simonmcmanus  - yeah, I wanted to catch the enthusiasm for the lightning talks from last month - had lots of good feedback to them - so added them this month too. This shouldn't affect your talk though - take as long as you need.

**Comment by admataz** [comment]
Thanks for the talk! https://www.youtube.com/playlist?list=PLam_80-FY3vSlu5Wg0psgn-zivPc1IDXx
