### ISSUE TITLE
 Building an Electron application with NodeJS

### ISSUE THREAD

**Issue by bernardbaker** [lnug/speakers#115]
NodeJS has many uses, but what about taking the traditional web development offline and developing NodeJS application for the desktop. This talk introduces Electron. A nifty framework which makes desktop application development with NodeJS a breeze and stretches the horizon for businesses and developers to offer desktop applications as solutions to client and business needs.

Watch Bernard Baker (BTAB [@bernibear2000](https://twitter.com/bernibear2000)) walk you through the development of a production ready application which is being used at Sky which converts videos into sprite sheets for use by online display campaigns.

Bernard Baker is an aspiring programmer who has been coding for over ten years. Currently working as a Digital Innovations Specialist - dreaming up new product ideas, mentoring programmers and investigating new technologies for their benefits in his business domain.

**Comment by jkbits1** [comment]
@bernardbaker thanks for this, your talks are always great and the audience enjoy them a lot. What dates can you do?

@bernardbaker @admataz we had a talk in April on Electron. That was a different slant on the topic, but any thoughts on that?

**Comment by admataz** [comment]
@bernardbaker - thanks for the talk proposal - this sounds awesome - a hands on electron talk and applying nodejs to the desktop... great!  You said you could do November?  Putting you in for that - let me know if that needs to change!

@jkbits1 - I was disappointed with the talk in April by the guy from Canonical  - I think he just trotted out some standard marketing material about snapcraft (Canonical's distribution/packaging system for apps) but didn't really make an effort to talk to the node developer aspect (which he assured me he would). Bernard's talk sounds much more relevant and interesting to our audience - actually building apps with node.js  - and being a regular Lnug attendee, I trust he knows what the audience will appreciate.

**Comment by admataz** [comment]
hi @bernardbaker  - are you still up for giving your talk on the 22nd of November?  let me know asap and I will add this to the website and meetup

**Comment by bernardbaker** [comment]
Yes I am.

**Comment by admataz** [comment]
Hi @bernardbaker  - are we all good for wednesday? We'll be getting there around 6pm to start setting up... Do you have anything special with regards to presentation? It makes it a lot easier if you can run your slides from the MC's laptop (saves swapping cables) but if you need to do live code or any demo in your environment - that's no problem either...

See you Wednesday!

**Comment by admataz** [comment]
Thanks for the talk @bernardbaker https://www.youtube.com/playlist?list=PLam_80-FY3vSlu5Wg0psgn-zivPc1IDXx
