### ISSUE TITLE
An introduction to Docker and Kubernetes for Node.js developers

### ISSUE THREAD

**Issue by georgecrawford** [lnug/speakers#117]
Node.js apps can run on a multitude of platforms. But when you ship code to production, how can you be sure that it will behave in the same way it did on your local dev machine? Containerisation is one way to mitigate this risk: by building a virtual 'image' which includes the OS, software and source code that your application needs to run, you can ensure a reproducible build you can trust, which runs in the same way in every environment.

But containerisation isn't the whole picture. Take the concept of reproducible, declarative builds to its natural conclusion and you get 'container orchestration': a representation of all of your applications and servers and how they relate together. 

This talk will introduce containerisation with Docker; how you can use it to make your workflows more predictable and your servers more reliable; and using Kubernetes to spin up your applications in the cloud using nothing but YAML files, with monitoring, logging, scaling and networking all taken care of. We'll be looking at some real-world examples, some tips and tricks, advice on developing on your local machine, and some of the more painful discoveries from a few months of deploying to production.

---

I gave this talk at BristolJS recently, and my slides are here: https://speakerdeck.com/georgecrawford/an-introduction-to-docker-and-kubernetes-for-node-dot-js-developers. Video coming soon, apparently.

---

George Crawford
https://twitter.com/georgeocrawford
https://github.com/georgecrawford
https://www.linkedin.com/in/george-crawford-185671a9/

**Comment by admataz** [comment]
Hi @georgecrawford  - this looks some really useful info for node developers... (slides look good too!) Would be great to have you give this talk at LNUG... How are you fixed for January? We don't run a meetup in December, and November is looking full already. 

I think orchestration is a really useful topic - as long as we keep the node angle alive and keep it focused/not too long. I've seen the audience get a bit restless when faced with 30 minutes of  boxes and arrows.   Live relevant demos of this kind of thing are also always a win! 

@lnug/organisers  - please provide any thoughts/feedback.

**Comment by georgecrawford** [comment]
Hey Adam. 

Thanks for the feedback. I could do January. It's not clear from the LNUG site (and I'm afraid I haven't managed to attend before) whether the meetups are always on Wednesdays or not. Do you have a calendar of proposed dates for Jan?

As presented at Bristol JS, the talk was only just under 1 hour - it was too long, and I will be trimming it for sure. I don't do live coding, but certainly do some interactive terminal sessions (one example: https://asciinema.org/a/144302) to illustrate each major area of Docker and k8s.

Do you have a very rough idea of what percentage of your typical audience are already familiar with Docker? I'd imagine it's quite high, so could trim that section in particular?

**Comment by admataz** [comment]
Hi George, 
We always hold our meetups on the 4th Wednesday of the month - so for January that's the 24th.  

Yes, an hour is too long - we're not geared to long talks.  To keep things interesting and moving on the night we allocate 20 mins for each speaker - there can be some flexibility and stretch, but I'd encourage you to rather focus on a particular interesting aspect of your subject than to try cover everything comprehensively.

In terms of levels of experience  in the audience - there is a large range in the 120-150 people that attend each month - some regulars will be very familiar with Docker and kubernetes and using it daily, but we get a fair number of new developers and first timers every month too.  A high level intro to Docker and the problems it can solve will be fine - leave the details to some links or resources. 

Live code/interactive terminal session - it always helps to see something working in action

Happy to review any thoughts you have in developing the talk - I'm sure some others in the LNUG orgs will have some useful input too.

**Comment by admataz** [comment]
Hi @georgecrawford Happy New Year! 

I hope you had a good break?  How are you for Wednesday 24th Jan?  - would you be able to do a shorter talk?

**Comment by admataz** [comment]
Hi @georgecrawford  - hope you are well? Haven't heard from you - and next week is looking pretty full -  so putting this proposal on hold for now - please let us know if it suits you to find a slot another month

**Comment by georgecrawford** [comment]
Hi Adam,

Sorry, it's been a hectic few weeks. Let's put this on hold until I can find some free time. I'll be in touch.

Cheers,


____________________


George

**Comment by admataz** [comment]
Hi George - I hope all is well with you? - how's your schedule looking over the coming months?

**Comment by admataz** [comment]
Hi @georgecrawford  - I hope all is well with you. 

I'm going to close this for now - feel free to reopen when your schedule is clear!
