### ISSUE TITLE
⚡️MOAR lightning community node.js talks! ⚡️

### ISSUE THREAD

**Issue by admataz** [lnug/speakers#119]
We loved it last month when people stood up with ad hoc talks, tips and tool walkthroughs. Much fun and entertainment all round. (If you missed it - check [all last month's videos here](https://www.youtube.com/watch?v=7gCKAfrlkAk&list=PLam_80-FY3vTo_2mlVajPvnqWqUrECJeK))

This month it's your turn. For 3-8 minutes, the mic is yours. Add your name and topic as a [comment in this issue](https://github.com/lnug/speakers/issues/119). Or turn up on the night and we will try fit you in... 

Also, as usual: community announcements, open source projects, job hunters and offers will have a chance on the mic.

**Comment by forbesmyester** [comment]
Would like to introduce my project [binary-repository](https://github.com/forbesmyester/binary-repository) and solicit contributions / talk briefly about the components yargs, GPG, BASH(!), AWS S3, AWS CLI(!) etc and what I have learnt using them.

Can we have slides (even if only web hosted ones)?

**Comment by admataz** [comment]
Thanks @forbesmyester  - sounds great!  Sure slides are good - even better if they are online and you can take over the host's laptop and we don't need to fiddle with display connections

**Comment by admataz** [comment]
Thanks all 
https://www.youtube.com/playlist?list=PLam_80-FY3vSlu5Wg0psgn-zivPc1IDXx
