### ISSUE TITLE
Tim Perry - Web Components & Microservices Are The Same Thing

### ISSUE THREAD

**Issue by pimterry** [lnug/speakers#12]
I've got a talk put together on web components, microservices, and the shared principles behind both of them (complete with node-based example). Does that sound like a good fit for LNUG?

Not sure how long your talks typically are; this is about 30 minutes, but that's a bit tight, so a 35/40 minute slot would be great if that's possible. It looks like the October & November slots are already pretty full, but January 28th would work for me.

**Comment by orliesaurus** [comment]
Hi @pimterry are you still okay to run this awesome session?

**Comment by pimterry** [comment]
Yep, very happy to.

**Comment by orliesaurus** [comment]
Thanks see you on the 28th more details to come :)
