### ISSUE TITLE
Testing Node.js Applications

### ISSUE THREAD

**Issue by thanpolas** [lnug/speakers#120]
In the "Testing Node.js Applications" talk we go through techniques and patterns for effective and optimal testing of your node.js application. We'll talk about how you need to implement your application so it's more testable, how to setup your folder structure, techniques and tactics on setting up your testing libraries and lastly we'll dive into a couple of test examples.

* *Talk*: https://speakerdeck.com/thanpolas/testing-node-dot-js-applications
* *Github*: https://github.com/thanpolas
* *Twitter*: https://twitter.com/thanpolas
* *LinkedIn*: http://www.linkedin.com/in/thanpolas
* *Home*: http://thanpol.as
* *Job*: _Comming soon_

**Comment by admataz** [comment]
Hi @thanpolas  - just noticed you closed this - my apologies that  no-one has responded so far to your proposal... 

If you would still like to talk at a meetup  - please feel free to reopen - and I'll be sure to get someone from @lnug/organisers to take a look and respond

**Comment by thanpolas** [comment]
Thanks @admataz, I closed it because I booked the talk for another meetup, I will open a new issue with another topic once I find it.
