### ISSUE TITLE
Unit testing has never been so much fun!

### ISSUE THREAD

**Issue by lazlojuly** [lnug/speakers#124]
* This is a lightweight and entertaining 15 minutes long talk.
* It is aimed at developers on **ALL** levels.
* Covers basic and advanced concepts.

Bio: I am a JavaScript Engineer with growth mindset. 
Connect with me on [Twitter](https://twitter.com/lazlojuly), [LinkedIn](https://www.linkedin.com/in/lazlojuly) or [GitHub](https://github.com/lazlojuly)

**Comment by admataz** [comment]
I look forward to it! How about kicking off  the talks for the year on January 24th?

**Comment by lazlojuly** [comment]
Yes, January is good!

**Comment by admataz** [comment]
Hey @lazlojuly  - assuming all is good for you next week? Do you want any feedback on your talk prep?

**Comment by lazlojuly** [comment]
@admataz I am going to work on the talk this weekend. I'd appreciate some feedback on Monday or Tuesday maybe. I'll email you my slides. Thanks!

**Comment by admataz** [comment]
Hello - talks from January are now on the Youtube channel: https://www.youtube.com/playlist?list=PLam_80-FY3vQYf354vj8MyEa5TIV8oe-c Thanks again for your talk!
