### ISSUE TITLE
Creating PowerPoint files with Officegen and Node.js

### ISSUE THREAD

**Issue by paulbjensen** [lnug/speakers#126]
It turns out that you don't need Microsoft Office to create PowerPoint files - you can create them in Node.js. In this talk I will show you how libraries like Officegen allow you to generate PowerPoint files containing text, shapes, charts and images, and demonstrate a real-world use of this tool that we've been crafting to save us some time.

My name is Paul Jensen, I'm the author of Manning's Cross Platform Desktop Applications, and I'm the Lead Innovation Engineer at Starcount. My twitter handle is paulbjensen.

**Comment by admataz** [comment]
Hi @paulbjensen 

I think this sounds like a good lightning talk? <5-8 minutes?  

@lnug/organisers  - any thoughts. 

If you can keep it short, I'm pretty sure we can fit you in Jan, Feb or March

**Comment by jkbits1** [comment]
@admataz agree that this could be a great lightning talk

**Comment by paulbjensen** [comment]
Hi,

Yep, it can definitely be a lightening talk. As for schedule, happy with whichever slot you'd like to put it in.

**Comment by admataz** [comment]
great stuff - how about January 24th?

**Comment by paulbjensen** [comment]
Sounds good.

**Comment by admataz** [comment]
HI @paulbjensen  - hoping all is good for next week... if you want any feedback on your talk prep - please feel free to get in touch...

**Comment by admataz** [comment]
Hi Paul - I had great feedback from attendees on the night about your talk in January - thanks again for your contribution. The talk is now on our youtube channel: https://www.youtube.com/playlist?list=PLam_80-FY3vQYf354vj8MyEa5TIV8oe-c Hopefully see you again soon.

**Comment by paulbjensen** [comment]
Thanks, I hope to pop to the March one, plus I’m scheduled to talk about Cucumber in April, so looking forward to it.
