### ISSUE TITLE
My Node.js process is on Fire

### ISSUE THREAD

**Issue by mcollina** [lnug/speakers#128]
At 10am on Black Friday, your phone rings: the new JS application you deployed came under too much load, and the site has gone down! Your employer is losing sales opportunities... your employer is losing money!

But you don’t lose your cool. You log into your cloud provider and tweak your autoscaling settings. Now the deployment can handle the load spike but with four times the number of servers, which is four times the cost.

The next day, you try to analyze what happened and begin to optimize your application to prepare for future load spikes. 

This talk is a journey into the world of Node.js performance, taking a look at the available tools and optimization techniques inspired by insight gained from glimpsing under the hood of Node and V8.

### Bio

Matteo is a code pirate and mad scientist. He spends most of his days programming in Node.js, but in the past he worked with Ruby, Java and Objective-C. In 2014, he defended his Ph.D. thesis titled "Application Platforms for the Internet of Things". Now he is a Principal Architect at [nearForm](http://nearform.com), where he consults for the top brands of the world.
Matteo is also the author of the Node.js MQTT Broker, [Mosca](http://mosca.io), the fast logger [Pino](https://github.com/mcollina/pino) and of the [Fastify](https://www.fastify.io) web framework. Matteo is also a member of the Node.js Technical Steering Committee. Matteo spoke at several international conferences: Node.js Interactive, NodeConf.eu, NodeSummit, JSConf.Asia, WebRebels, and JsDay to name a few. He is also co-author of the book "Node.js Cookbook, Third Edition" edited by Packt. 
In the summer he loves sailing the _Sirocco_.

Twitter handle: [@matteocollina](https://twitter.com/matteocollina)

**Comment by jkbits1** [comment]
@mcollina thanks for this proposal, it sounds practical and fun, too! I enjoyed hearing you talk about Fastify last year and this would be great for our audience.

We try to encourage a wide mix of attendees, from new'ish Nodejs devs to experienced ones, so if there could be some elements that everyone could take away from the talk that would be great. Also, we generally aim for talks to be 20-25 minutes (LNUG is always a busy evening), but they can go over that if it's agreed in advance, if that gets the content across better.

@admataz any thoughts from you?

**Comment by mcollina** [comment]
A 20 minute slot is ok. The talk is an introduction to the topic, and how to approach it from a process perspective. Then it touches what are the available tools, and some more details about how Node and V8 work. It does not require prior knowledge on Node.js internals.

**Comment by admataz** [comment]
nice one @mcollina  - this is great and all looks good. And thanks @jkbits1 for reviewing...

I'll add you to the schedule for March 28th 

Meanwhile some members have asked us to formalise the agreement with speakers a little: 
So just checking: 
- [x] Length of talk - needs to be 20-25 mins. (done!)
- [ ] Code of Conduct - as part of our community we need to make sure all speakers agree with that - see https://lnug.org/code-of-conduct.html

Look forward to seeing you on March 28th - let me know if we can be of any assistance with anything - otherwise,  will be in touch shortly beforehand to confirm.

**Comment by mcollina** [comment]
Of course, I agree with the CoC.

**Comment by admataz** [comment]
Hi @mcollina  - just confirming - is all still good for you for this Wednesday? As discussed - I have you in for the first talk (soon after 7pm start) - let me know if this is still good for you.

**Comment by mcollina** [comment]
All set!
Il giorno dom 25 mar 2018 alle 19:15 Adam Davis <notifications@github.com>
ha scritto:

**Comment by admataz** [comment]
Hi Matteo

Thanks again for your talk last week - it was great to have you at LNUG. Hopefully again some time! I had really good feedback from attendees for all the talks on the night - and I think it was a fun night - one of my favourite LNUG meetups so far.

I'll post details here when the video from the night is ready and online, and meanwhile, if you have any feedback from the perspective of speaker - I'd  love to hear it.

**Comment by mcollina** [comment]
Awesome!! let me know when the video is online!

**Comment by admataz** [comment]
Hey @mcollina  

the videos are now available in the March 2018 playlist on our YouTube channel: https://www.youtube.com/playlist?list=PLam_80-FY3vQpb1xoZn-qaISFOfvNjJBh

Thanks again for your talk - see you next time you can make it to London on the 4th Wednesday!
