### ISSUE TITLE
Never get stuck with a wrong framework

### ISSUE THREAD

**Issue by sielay** [lnug/speakers#129]
Case study of our app, where we divided it to multiple heads (microapps/microservices) to allow it to be relatively small and fast, but also be able to shift between different stacks and framework depending on current needs and not carry big cost of wrong choices.

I'm lead Web & Desktop developer at Pushfor. We build our content sharing solutions mixing vanilla, react, angular, third party libs, stacking that on node and wrapping in electron. Just check my GH account.

**Comment by admataz** [comment]
Hi @sielay  - thanks for your proposal - sorry it's taken a while to get back to you

Sounds good - let's talk about giving the talk abstract some shape and give it a hook for people to relate to (I think it's a little bit generic right now - I'd be happy to chat about what you want to talk about, and help you shape it)

It would be good if we could word it in a way that...

1. gives an idea of a story and narrative/suspense
2. mentions technologies/stacks/frameworks you battled with
3. talks in specifics about your challenges/goals/aims

Other than that - couple things we need to confirm: 
- [ ]  Length of talk - needs to be 20-25 mins. (thanks - see you have confirmed above!)
- [ ]  Code of Conduct - as part of our community we need to make sure all speakers agree with that - see https://lnug.org/code-of-conduct.html

Looks like we have space in April, May or June - any preference? 

@lnug/contributors, @lnug/organisers   - please help speakers with feedback to their proposals - and let us know your thoughts on proposals!

**Comment by sielay** [comment]
Background:
Scenario: existing project, rushed, incrementaly amended instead of actually planned - quite typical startup environment. You bet on tools that a) you know b) are established c) provide easy hires d) provide up to date featureset. I took Angular 2/4 SAP hostes on S3 as API layer is totally separate from your concerns. All works quite well until pivot. I discover that 1) app grows to levels lazy loading doesn't help the speed 2) mixing various vendors starts to be problematic 3) app doesn't actually works as SAP, you need it more modular. We decide to reintroduce backend layer (even if it's statelss) and server side routing. We divide app to small chunks. We take out data layer to allow caching between impressions. We don't commit to specific framework, use it by case.

Points addressed:
1. You have clear vision of the app and strucutre, until business decide to pivot in direction technology doesn't fit anymore.

2. Static hosting and Angular (because bootstraping) fails against Dockerized Express + various frontend code in terms of agility. Framework specific data layer fails against abstracted business logic.

3. Need to be able to make 180 turn on any part of the app without need to rewrite 100%. Need to allow team/developer unfamiliar to most of the app be able to build new features using shared elements.

Biggest challange to prepare speach: fit complex example in 20-25 min and make it applicable outside given story.

Way to address it:
1. not going into technical details re configuraiton, version, frameworks, etc (except when/what failed)
2. present problem/solution as reference to specific business/product requirements 
3. finish with potential pivot examples to prove the point

Hope it makes sense. Do you want to discuss it more in details, have some draft of presentation?

**Comment by admataz** [comment]
Hi @sielay  - thank you - I appreciate the extra background and context - I think you have the ingredients for a really good talk here - and with some editing, your new background scenario makes  better abstract for promoting the talk on meetup and the website. Will you be at this Wednesday's meetup? If so, and if you like, we can have a quick chat about good approaches.  

Any thoughts on dates?

**Comment by sielay** [comment]
So far my calendar collide only with July as I understand each LNUG is on last Wed of the month.

I will be for 90% on this Wed. I am this annoying guy who shows up once a year, makes cheeky comments and tries to hire someone ;) easy to find me

**Comment by admataz** [comment]
cool - hopefully see you there - just to clarify it's the 4th wednesday of every month  - so sometimes not the last wednesday (e.g August)

**Comment by sielay** [comment]
I am closing this one as I won't be able to dig into that topic too much unfortunately. I will come up with other topic. Thanks

**Comment by sielay** [comment]
@admataz Had a chance to rethink approach for the talk and let's see if that would work.

Working title: "Limiting wrong tool choices in fudge development"

to fudge sth - as in `Adjust or manipulate (facts or figures) so as to present a desired picture.` (Oxford Dictionary)

Summary: a compilation of various `quick win` approaches happening in early-stage startups with examples how some tool choices can work in such scenarios and other can derail the process.  It would be giving an example of vanilla vs anuglar vs react. It will show 3rd party vs own code and i.e. tests vs types

Level: an overview of technical references but approachable for a non-tech audience too 

Can do any month except August.

**Comment by sielay** [comment]
I'll try to write nice explanation (for website) later today.
