### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by claudiamatosa** [lnug/speakers#130]
Who hasn't found themselves in despair after hours of trying to debug a problem that seemed simple, because halfway down the line the stack trace ended in a file called `throw-error.js`, or simply there were no errors thrown and the code just didn't work as expected?

The talk will last between 15 and 20 minutes, will be structured in two parts and there will be plenty of gifs and emojis. It should cover errors in Node and browsers.

### 1. Common bad error handling scenarios

- Stacktrace lost.
- Code exits without error.
- Generic error messages (`something has failed`).
- ...

### 2. Exploring possible solutions (examples)

- Custom errors.
- Formatting error api responses.
- Displaying errors in the UI.
- Examples when using Apollo (GraphQL), React and maybe other tools.

Conclusion: your library/utility/api should be built around its users, and they shouldn't need to read the code to know why something is wrong.

(I'm really bad with titles 😳)

I'm a freelance front-end developer, currently working with React and GraphQL.
[twitter](twitter.com/claudiamatosa) | [github](github.com/claudiamatosa)

**Comment by jkbits1** [comment]
@claudiamatosa thank you for your proposal, I really appreciate how clearly it's been thought-through and presented 👍 

We'd definitely like to have you give your talk at LNUG. The content and length are both ideal. It's great to get across that an api or app should put the user's concerns first 😄

We encourage a wide mix of attendees to attend, from new'ish Nodejs devs to experienced ones, so if there could be some elements that less experienced devs could take away from the talk too, that would be great. 

We definitely have speaker slots available for 25 April and 23 May (possibly for 28 March, too, just need to double-check our schedule).

@admataz @lnug/organisers - any thoughts?

I like the title, but it can be changed if you want!

**Comment by claudiamatosa** [comment]
@jkbits1 That's awesome, looking forward to it! Let's keep the title then. :)

I would be happy to do it on the 28 of March if there's still a slot, otherwise any of the other dates work.

**Comment by admataz** [comment]
Hi @claudiamatosa  - thanks for the talk proposal - great topic (and title!) - I think this will make a great talk for LNUG. 

Your choices for dates: pretty much what @jkbits1 said. I'm happy to add you to the March schedule (we have two talks already planned - but another short talk would be ok)  - or if suits you better - one of the other dates...

A couple things we need to confirm: 
- [x] Length of talk - needs to be 20-25 mins. (thanks - see you have confirmed above!)
- [ ] Code of Conduct - as part of our community we need to make sure all speakers agree with that - see https://lnug.org/code-of-conduct.html

Adding you to March for now - let me know if you want to change that

**Comment by claudiamatosa** [comment]
Hey @admataz!

March sounds good, and I have read and agree to the code of conduct.

**Comment by admataz** [comment]
thanks @claudiamatosa  - and you're on! It's looking to be a really good meetup in March.

**Comment by claudiamatosa** [comment]
Yay! 👍 ✨

**Comment by admataz** [comment]
Hi @claudiamatosa  - just confirming - all still good for you for this Wednesday?

**Comment by claudiamatosa** [comment]
Hi @admataz, thanks for confirming. All good! What time should I arrive?

**Comment by admataz** [comment]
Hi! If you can aim for around 6:30 when doors open - or a little earlier if you like. I'm usually there from about 6 to set up - and it would be good to check all is OK with your slides etc. Talks start at 7pm - I was planning to schedule you for the 2nd talk at which is about 8:00pm, straight after the first break  -  hope that suits you ok?

**Comment by claudiamatosa** [comment]
Thanks! Will aim to be there around 6!

**Comment by admataz** [comment]
Hi Claudia 
Thanks again for your talk last week - I heard a lot of really good feedback about all the talks - and from the chats I had later in the evening - people really enjoyed yours and related well to the stories you shared. 

If you have any feedback from the perspective of a speaker - please let us know - I'd love to hear it. Meanwhile the video from the night is being prepared - and I'll let you know as soon as this is available. 

See you again soon!

**Comment by claudiamatosa** [comment]
Hey @admataz,

Thanks for your feedback, much appreciated!

I have only positive things to say. The room felt familiar and comfortable to speak in. Maybe a mix of the setup (dimmed lights, etc) and a mindful audience. I like the idea of leaving the questions for the pub, not as much because of the speakers, but because it prevents everyone else from getting bored. Looking forward to see how it goes in the the new location!

Cheers

**Comment by admataz** [comment]
Hey @claudiamatosa  

the video is now available in the March 2018 playlist on our YouTube channel: https://www.youtube.com/playlist?list=PLam_80-FY3vQpb1xoZn-qaISFOfvNjJBh

Thanks again for your talk - see you at the next meetup!
