### ISSUE TITLE
CV Hacking for the London market

### ISSUE THREAD

**Issue by Boltz101** [lnug/speakers#132]
Abstract
Finding a role in London is tough.  It's full of cowboy recruiters and companies with 77 stage hiring processes.  How can you make sure you maximise your CV?  How do you ensure that you get approached about relevant jobs (Java / Javascript, anyone?)?  In this session I will take a CV and hack it in to a format that will help you to improve that CV you've just been adding jobs to since the careers adviser helped you write it in school when your "responsibilities" were dog walking and baby sitting.

About me
I'm Adam and I host events over at www.idinlondon.co.uk.  I'm pretty passionate about recruitment and hate that there are so many people in my industry who give us all a bad name.  I care about finding people jobs that they will enjoy and have a positive hiring experience.  I am not an agency recruiter and I'm not going to start throwing business cards around like confetti.  Please love me.

**Comment by admataz** [comment]
hi - as written in https://github.com/lnug/speakers/issues/133 - thanks for your proposals  - it's just not for us.
