### ISSUE TITLE
How do I hire tech staff without annoying agencies?

### ISSUE THREAD

**Issue by Boltz101** [lnug/speakers#133]
Abstract
You worked in a big company.  You had an idea.  You started a company, and now you need to hire.  But how?  In your previous life CVs just arrived via HR or an Internal Recruiter, now, you put out a job posting and get 300 recruiters a minute calling you, and your Excel sheet on your hard drive isn't being shared and the email chains are causing grief because someone forgot to click 'Reply All'.  In this talk I'll talk through some of the easy ways to engage with talent and introduce you to a few tools for tracking applicants.

About me
I'm Adam and I host events over at www.idinlondon.co.uk.  I'm pretty passionate about recruitment and hate that there are so many people in my industry who give us all a bad name.  I care about finding people jobs that they will enjoy and have a positive hiring experience.  I am not an agency recruiter and I'm not going to start throwing business cards around like confetti.  Please love me.

**Comment by admataz** [comment]
Hi Adam, 

Thanks for your talk proposals. I'm sorry, but  we  will not accept this as a talk at LNUG

I appreciate that recruitment and finding a job is important, and making the right contacts and finding the right candidates is essential for us all to keep going. But I think you have the wrong group for your talk.  We are the  London Node User Group and we keep the focus our talks on the technologies around JavaScript and node.js. Getting a job or finding a candidate is for the networking in the breaks and the pub after the tech talks. 

From the [speaker proposal guidelines in this repo](https://github.com/lnug/speakers#some-loose-talk-guidelines): 
> this is the London Node.js User group - we are a broad group of developers and touch many technlogies in our day to day lives - but try and keep the link to Node and JavaScript central to your talk

Thanks again for your proposal - please feel free to join us at our next meetup and introduce yourself to our attendees.  I hope you can find the right audience for your topic, which as I said, is an important one.
