### ISSUE TITLE
ExpressLess - 200 OK

### ISSUE THREAD

**Issue by firecode9** [lnug/speakers#134]
Heard about Serverless? Already know Express.js? Too afraid to use the two? 

My talk will last ~20 mins and will cover the following:

- Where are my servers? (Moving from the classic setup to a serverless one)

- Express.js + Serverless?

- How can I test my serverless app? (Offline testing)

- Where are my logs?

- Wait, are my apis public? (Securing your endpoints)

- Shhhhh....(Keeping secrets)

### About me:
I started my career over a decade ago writing code for firewalls and security systems (c/c++/java). In recent years I've been specialising in cloud engineering, microservices, aws and serverless (mostly in node.js).

Now: I'm the CTO of a young and still in stealth mode startup - [sourcingbot.com](http://sourcingbot.com)

**Comment by jamesporter** [comment]
The general topic sounds really interesting although seems like it would be very ambitious to try to cover all those topics. 

I'm not a fan of tech stack overview talks as they pretty much always end up not giving enough content on any one of the topics to really engage with for those in the area. For those not in the area it will just be lots of jargon. 

In my opinion would be good to focus on what is unique/unusual about this approach (as still pretty novel to most node devs)... I'd suggest dropping as much stuff on express as possible (the audience will likely be very familiar with it) to focus on the more novel stuff. Also 2 & 3 would be interesting lighting talks but probably should be dropped from this as seem peripheral.

For e.g. 4. I'd really appreciate some kind of live demo, maybe you can could add a new endpoint, show it locally, deploy it etc. While it takes a lot more time showing, not telling, is way more engaging and convincing. Setting up some tagged commits or recording a screencast/demo in advance can streamline this.

Out of 5/6/7, I'd be most interested in seeing 7, given the novel context and how presumably typical approaches don't apply. My expectation would be 5 and 6 would be very hard to do in an interesting way; but perhaps if you are demoing something for 4, you could have some kind of CD happening automatically. CI/CD are awesome but part of a talk about configuring them is likely to be pretty dull.

**Comment by erankeren** [comment]
Hi,

Thanks for the feedback. I think you are right, it's too long for 20-25 mins. I think I would trim down to the following topics/agenda:

1. Overview of the old way for deploying and consuming restful api on aws.
(Load balancer -> ec2 -> express app with bind/listen)
~4 mins

2. Overview of the new way using serverless framework
(Api gateway -> invoke lambda)
~4 mins

3. offline testing + live demo 
(adding new endpoint, test locally, deploy, see it live)
~5 mins

4. viewing logs from the cli (cloudwatch stream)
~ 2 mins

5. Securing your endpoints + live demo
(adding api key/token)
~ 3 mins

6. Keeping the secrets using SSM store + live demo
~3 mins

If you approve - I will send the intro/movie trailer @admataz asked for.

Thanks

**Comment by erankeren** [comment]
@admataz - the 25/04 works for me

**Comment by admataz** [comment]
thanks @erankeren!  good stuff... You’re on for the 25th. I think the talk now has a good shape. Please can you edit the original opening comment with the intro/trailer and we can roll with this.

**Comment by erankeren** [comment]
My trailer:

Heard about Serverless? Already know Express.js? Too afraid to use the two? 

My talk will last ~20 mins and will cover the following:

- Where are my servers? (Moving from the classic setup to a serverless one)

- Express.js + Serverless?

- How can I test my serverless app? (Offline testing)

- Where are my logs?

- Wait, are my apis public? (Securing your endpoints)

- Shhhhh....(Keeping secrets)

**Comment by admataz** [comment]
Thanks @erankeren! I'm just back in town from holiday - I'll update the website and publish the schedule tomorrow

**Comment by admataz** [comment]
For posterity - here's the original talk proposal (updated with the copy better for promo)

> Hi,
> In this talk I would like to talk about how to create and deploy rest apis using AWS and serverless framework for 
> AWS lambda.
>
> Things I would like to cover:
>
> 1. Scaffolding the app with:
> - Express.js
> - API Gateway
> - AWS Lambda
> - Serverless
>
> 2. Proper logging with:
> - https://github.com/expressjs/morgan
> - https://github.com/baryon/tracer
>
> 3. Good error handling and pretty responses:
> - https://www.npmjs.com/package/boom
> - https://www.npmjs.com/package/express-boom
> - https://www.npmjs.com/package/express-prettify
>
> 4. How to test locally (offline testing)
>
> 5. CI/CD integration - how to deploy serverless apps from CIRCLECI
>
> 6. Connecting endpoints to a serverless DB (dynamo db)
>
> 7. Securing your endpoints and keeping your secrets
>
> About me:
> I started my career over a decade ago writing code for firewalls and security systems (c/c++/java). In recent 
> years I've been specialising in cloud engineering, microservices, aws and serverless (mostly in node.js).
>
> Now: I'm the CTO of a young and still in stealth mode startup - sourcingbot.com

**Comment by admataz** [comment]
Hi @erankeren  - I've just emailed you  - would you be able to talk on May 23rd instead?

**Comment by orliesaurus** [comment]
@firecode9 You're up on our youtube channel - check the video out - thanks for your time and I hope you've had a positive experience presenting at our meetup! https://www.youtube.com/watch?v=vCxRp9zIHgY
