### ISSUE TITLE
A Hobbyist’s Quest for a Personal Server

### ISSUE THREAD

**Issue by salmanff** [lnug/speakers#135]
How easy is it for a non-techie lay-person to set up a personal server and have their own apps running on it?

There's been much talk recently about how large companies host our data, control it, and sell ads against it. But what if we all had our own servers with our own applications running on them holding our data which we control? 

Is that doable today, using existing cloud services and node.js? What does it take? How easy is it?

For the past few years, I've been running my personal node.js-based server on AWS, Google Cloud, Openshift and Heroku, using mlabs and Mongo, as well as Dropbox!

So I'll talk about what it takes for a non-techie (or at least a newbie) to set up a node.js server using each of those environments - the pluses and minuses of each ... and why doing this would be a good thing in general.

About me:
I am clean tech entrepreneur (@zemenergy.com) and VC executive (@top-funds.com). I code for fun. See http://freezr.info twitter:salmanff github:salmanff

**Comment by admataz** [comment]
Hi @salmanff 
This is great! - I'd love to hear a talk on this angle of self-publication with node.js - I think this accessible aspect of javascript and node is often overlooked - and we are all big supporters of indy publishing.

How is May 23rd for you? (or June 27th)

@lnug/organisers  - can I get a seconder in support of this talk - and any thoughts?

**Comment by MattJLeach** [comment]
I second this talk idea @admataz @salmanff 

For years PHP hosting has been really easy with the huge array of choices of shared hosting, etc and a lot of newbies to NodeJS can find it a big change when choosing how to host their JS projects. I'm sure this talk would be very well received.

**Comment by salmanff** [comment]
Thanks very much @admataz @MattJLeach  . 
I don't live in London, but will be there next week, so to the extent there is still a slot available on April 25th, that would be very convenient for me.

**Comment by admataz** [comment]
@salmanff  - you're in luck!  I've chatted with one of the other speakers and he doesn't mind swapping  - so consider yourself scheduled for April 25th! A couple small things we need to confirm: 

- [ ] Length of talk - needs to be 20-25 mins 
- [ ] Code of Conduct - as part of our community we need to make sure all speakers agree with that - see https://lnug.org/code-of-conduct.html

Let me know if you need anything you need - otherwise see you on the 25th April. 

Note: we are hosting at a new venue this month and I'll need you to add your details to meetup and to RSVP so we can add you to the list and get you in the door!

**Comment by salmanff** [comment]
Thanks very much @admataz ( and thanks @erankeren ). Looking forward. 
Will plan for 20 minute talk and agree to the code of conduct.
(I will need wifi.)

**Comment by admataz** [comment]
Hi @salmanff 
Just confirming you're all good for Wednesday?

I have confirmed guest wifi will be available. 

The venue is:
Conde Nast
Adelphi Building, 1-10 John Adam St Level 9 · London
The nearest Tube stations are Embankment and Charing Cross

I will be there from about 6pm to get things set up - your name will be at security. If you arrive before me please ask for Michelle Garret. 

See you there!

**Comment by salmanff** [comment]
thanks @admataz. Yes, all set, and looking forward to it. Thanks for the wifi. See you there.

**Comment by admataz** [comment]
Hi @salmanff  - thanks again for your talk - it was a fun night and your talk was great - thanks for your contribution. 

Videos are now live: https://www.youtube.com/playlist?list=PLam_80-FY3vTu3eOUOavEepvDLHVAy_sZ

Speak soon!
