### ISSUE TITLE
Scheduled Messaging with RMQ, Redis, Postgres

### ISSUE THREAD

**Issue by sp3c1** [lnug/speakers#136]
It is kind of interesting how in 2018 we are missing a timed messaging queue system out of the box, and there is no clear standard how to handle the matter. We will showcase some valid use cases, discuss performance, engineering and architectural limitations, implementing and comparing RMQ, Redis and Postgres based solutions.

Bartlomiej Specjalny, Senior Software Engineer at Bizzby Limited, a fullstack software engineer with background in computer graphics and multimedia.

**Comment by admataz** [comment]
Hi @sp3c1  - great to hear from you again - and thanks for your proposal - this sounds interesting - I'd love to hear an overview of the use cases and implementation of queues in node.js - and some context around what you would consider a "proper scheduling queue" and how your wrapper approach can help. 

@lnug/organisers  - can I get some feedback and a seconder? 

A couple comments from me: 
Can you alter your description to clarify "RMQ" - I think it's better to refer to this with it's full name - not all attendees will know what this is when this goes out on the website/meetup/email. 

How are you for June 27th? 

And a couple small things we need to confirm (you've done this before - so you should know....): 

- [ ] Length of talk - needs to be 20-25 mins 
- [ ] Code of Conduct - as part of our community we need to make sure all speakers agree with that - see https://lnug.org/code-of-conduct.html

**Comment by sp3c1** [comment]
Hey, There is strong change i wont be around in June (Thailand), but July should be alright.

Wrote kind of outline http://sp3c1.ninja/2018/04/13/Scheduled-Messages-with-RMQ/ - nobody reads it so I am using more as a notepad atm ;]

What I mean by a"proper scheduling queue" is that apart from amazon take on queues, no large enterprise ready system actually does offer such functionality (setting an time on message, that would determine in first order when the message becomes visible to the consumer) without large descriptions of warnings and limitations. And even amazon one is actually offering max 15 minutes time frame while the problem - scheduled async task with arbitrary execution time - is actually quite common.

Maybe title should be more telling about the arbitrary time aspect?

**Comment by sp3c1** [comment]
@admataz Cool. seems like i will be around, that time.

Will alter also a bit title and synopsis

**Comment by admataz** [comment]
Hi @sp3c1  - just checking - Do you mean you will be around in June? I'm happy to schedule you for July (or another month) if that's better

**Comment by admataz** [comment]
@lnug/contributors  - can we get another member to feedback and second this talk?

**Comment by FabioAntunes** [comment]
This seems like a great talk, would be nice to simplify a bit the synopsis
to make it more friendly for devs with no experience on messaging queues.

**Comment by sp3c1** [comment]
Hey, yes, will be around in June. 

K fabs, will try to simply this a bit ;]

**Comment by admataz** [comment]
Hey @sp3c1  - was just juggling things with the schedules today - can you do July instead?

**Comment by sp3c1** [comment]
yeah, July is fine ;]

2018-05-20 15:34 GMT+01:00 Adam Davis <notifications@github.com>:

**Comment by admataz** [comment]
Hey @sp3c1 ! 

 I hope all is well with you? just checking you're still good for Wednesday's meetup? I won't be there, but @FabioAntunes will be looking after proceedings  - and we have a full house of attendees signed up.

Note, venue details: 
CONDÉ NAST
ADELPHI
1-11 JOHN ADAM ST
WC2N 6HT

Organisers will be there from around 6pm getting things set up.

**Comment by sp3c1** [comment]
Yeah, all good.

**Comment by admataz** [comment]
Hi @sp3c1  - just an update - I'm chasing about the video for the evening - I believe there were some technical glitches on the night - so not sure what the status is... will let you know as soon as I find out

**Comment by admataz** [comment]
Hey @sp3c1  - seems these technical glitches were never resolved... I'm sorry I was away for this and don't know what happened. Closing this now - if you have any info or concerns please get in touch!

See you at a future LNUG soon hopefully !
