### ISSUE TITLE
Objection.js, a SQL ORM

### ISSUE THREAD

**Issue by paulbjensen** [lnug/speakers#137]
Objection.js is a SQL ORM (Object Relational mapping) for Node.js.

In this talk, I will walk you through how the module works, show live examples of it in action, and present the case for considering it in your Node.js projects.

Things that we'll cover are:

- Quick setup
- Creating the underlying database schema for your models via Knex.js
- Creating models and executing SQL queries via the models
- Implementing validation in your models with JSON schema
- Defining relationships between models
- Doing graph inserts and updates
- Setting up a GraphQL API with the objection-graphql plugin
- Other interesting objection.js plugins

My name is Paul Jensen, I'm the author of [Manning's "Cross Platform Desktop Applications - Using Node, Electron, and NW.js"](http://manning.com/books/cross-platform-desktop-applications). You can find me on [Twitter](https://twitter.com/paulbjensen) and [Github](https://github.com/paulbjensen).

**Comment by admataz** [comment]
Hi Paul - thanks again for stepping up  - I haven't heard back from Stephen for #138  - and I really want to get the schedule published for next week - so would you still be keen?

**Comment by paulbjensen** [comment]
Yeah, I’m happy to step in and fill the slot.

**Comment by admataz** [comment]
Thank you - you're on!

**Comment by claireinez** [comment]
Hi @paulbjensen, really excited for the talk this month. I'll be emceeing on the night and keeping you to time ;) so on that note, just wanted to check:
- [ ] Length of talk - needs to be 20-25 mins.
- [ ] Code of Conduct - please would you let us know you agree to follow our CoC? https://lnug.org/code-of-conduct.html

See you next week!

**Comment by paulbjensen** [comment]
Yep, agreed to both.

**Comment by claireinez** [comment]
Haha yeah I know you agreed to them last month but figured it was best to keep a record in each issue :) Thanks for indulging me Paul!

**Comment by admataz** [comment]
Hi @paulbjensen  - just checking in for tonight - I've had a message from Alex that does the videos and he is having trouble with his screen capture - are you on a Mac? This will make things easier for him, but if not we can make a plan.

**Comment by paulbjensen** [comment]
Yep, I’m good to go, and I have a 13” MacBook Pro (2014 edition), same as last time.

**Comment by admataz** [comment]
thanks!

**Comment by orliesaurus** [comment]
Hi @paulbjensen - you're live on our channel https://www.youtube.com/watch?v=Jl-3p9Yq4io
Thanks for your time and the talk, hope to see you soon at another meetup (well not in person as Im few thousands miles away but you know what I mean ... :D )
