### ISSUE TITLE
When you assume, you make an error out of you and me

### ISSUE THREAD

**Issue by gvonkoss** [lnug/speakers#139]
Our choices in wording are frequently more powerful than we realise, and we risk using this power liberally and erroneously. Let’s take a look at our ideas about how we communicate in our code and in our speech, and what effects those ideas have.

My name is Gabrielle von Koss, and I work as a developer at the Financial Times. You can find my retweeting activity on [@gvonkoss](https://twitter.com/gvonkoss)

**Comment by admataz** [comment]
Hey @gvonkoss  - thanks for your talk proposal... it would be great to hear your talk at next week's LNUG meetup  - which is probably the best opportunity for you to get any feedback before JSConf. 

How long is your talk? 

@claireinez  - you are emcee for the night - do you think we can fit in another talk?

**Comment by gvonkoss** [comment]
hey @admataz the talk is a little over you 20 minute limit, but I could probably tailor it down.

**Comment by claireinez** [comment]
What a great title for a talk! @gvonkoss were you aiming to give this a dry run at LNUG before JSConf EU? If so, we should be able to fit three speakers in next week but it would definitely have to be 20 mins max (we don't do Q&A so no need to factor that in). Otherwise we'd also be happy to have you speak at LNUG a different month. Let me know and we can schedule you in :)

**Comment by admataz** [comment]
Great! I also think 3 talks will be ok - we've done it many times before - so if you're ok with it @claireinez...

@gvonkoss  - if you can confirm that suits you - I'll get this into meetup and the website

**Comment by gvonkoss** [comment]
@claireinez Thanks! 
In all honesty, it would be a great dry run, but it is a bit of a squeeze for 20 minutes because I'm still putting finishing touches on it. I'm happy to schedule it for another month though.

And for the record, I do agree with your code of conduct, apologies for having neglected that before!

Nonetheless, thank you for being willing to slot me in!

**Comment by claireinez** [comment]
We could do 25 mins maybe? Or would you prefer we just schedule it in one of the coming months?

**Comment by gvonkoss** [comment]
I'd rather we left it for one of the coming months!

**Comment by admataz** [comment]
Hi @gvonkoss - make sense.  How are you for June 27th?

**Comment by admataz** [comment]
Hi @gvonkoss. I hope all went well in Berlin?

just putting the schedule and meetup page together for later tis month. Are you still up for it?

**Comment by gvonkoss** [comment]
Hey @admataz, I'm sorry I missed that last message, the lead up to the conference has been a bit hectic. I'm afraid it's all been slightly overwhelming, and I need a little break. Is it alright if I reopen the proposal in a few months?

**Comment by admataz** [comment]
Hey @gvonkoss  - of course - that's no problem. Let us know when you're ready. Meanwhile please feel free to join us for pizza and a drink at the next meetup!

**Comment by admataz** [comment]
Hi @gvonkoss  - I hope you are well? Any thoughts on a date for this talk at LNUG? We would love to have you speak!! Let us know what suits you for the coming months...

**Comment by gvonkoss** [comment]
Hey @admataz! I am doing alright thanks, how is LNUG going?

I may be a total buzzkill here, but I don't think I'm going to be here for any of the LNUG meet ups until the end of the year 😱

When are the October/November/December (is there one in December even?) meet ups, just to make sure?

**Comment by admataz** [comment]
Hey @gvonkoss   - all good thanks!

Dates of upcoming meetups:

- 24th October
- 28th November
- nothing in December
- 23rd January 
- etc (basically 4th Wednesday of every month except Dec)

No pressure - we can think of picking it up again some time in the new year...

**Comment by gvonkoss** [comment]
(: I appreciate it. 

I think I'll have to be next year—I'm not in London for either dates on October or November! 
But January? Could work!

**Comment by admataz** [comment]
great! I'll ask again closer to the time!

**Comment by admataz** [comment]
Ahhh @gvonkoss ! January Meetup came and went! it was great, but may have been even better if you were there! 

If you still have an appetite for this talk - please let me know - we are full up with speakers for Feb, but maybe March?

**Comment by gvonkoss** [comment]
😱 @admataz I'm sorry I didn't get back to you!
I'm glad to hear you've started off the year well ☺️ 

Let's book it in—March sounds good to me!

**Comment by admataz** [comment]
🎉 that's great! thank you!

**Comment by orliesaurus** [comment]
It's official!!!

**Comment by neshka** [comment]
Hi @gvonkoss,

how are you today?

I just want to confirm if you are ready for Wednesday.
Please let me know.

Details of the venue:

CONDÉ NAST
ADELPHI BUILDING
1-11 JOHN ADAM ST
WC2N 6HT

I will be there from about 6:15pm, people start arriving around 6:30 and we plan to start with talks after 7pm.

If you have any issues - please call me: 07752387427 or @admataz 07757234443

See you there!
Aga

**Comment by gvonkoss** [comment]
Ready as I'll ever be! 😬  
I'm looking forward to it  🎉 

Shall I aim to get there for 18h15?

**Comment by neshka** [comment]
Yes and you will speak first :)
See you tomorrow!

**Comment by neshka** [comment]
Hi @gvonkoss 

Thank you for your great speech today!
I'll send you the link when video will be ready.

In touch :)

**Comment by gvonkoss** [comment]
(: Thanks @neshka I'm glad it was well accepted. Thanks for having me!

**Comment by admataz** [comment]
Hi @gvonkoss  - I've at last managed to upload the videos from last month's meetup - you can see them here: https://www.youtube.com/playlist?list=PLam_80-FY3vQKYb5bC1gzH1384eds6-IQ

Thanks again for the talk - please let us know if you have any feedback from an organisational point of view - and hopefully see you back at an LNUG meetup soon! 

(closing this issue - but feel free to add comments if you have any)
