### ISSUE TITLE
Service discovery for your Node.js applications

### ISSUE THREAD

**Issue by lukebond** [lnug/speakers#14]
A talk about service discovery in the context of Node.js. How to build services that talk to each other automatically and respond to changing IP address and ports.

The talk will be practical and technical, and focus on using Etcd as well as @pgte's Skiff Raft implementation. I may decide to do only the latter.

I plan to have an audience participation section at the end. Something along the lines of "clone this repo and run it to discover each other's services and participate in solving some problem".

**Comment by orliesaurus** [comment]
@lukebond you are summoned as our new year's champion to give a talk - still okay with that?

**Comment by lukebond** [comment]
can you push me back to February sorry? i'll be away for FOSDEM on that date

**Comment by orliesaurus** [comment]
WHAT FOSDEM is that early??? I wanted to go too :(

**Comment by lukebond** [comment]
It's actually 31/1-1/2, but I'm leaving on 28th to get there in time for a 2-day 0MQ workshop

**Comment by orliesaurus** [comment]
How about Feb?

**Comment by lukebond** [comment]
Yep February is good.

**Comment by orliesaurus** [comment]
This month, 25th :) bookmark it :D
