### ISSUE TITLE
Elm: your next programming language?

### ISSUE THREAD

**Issue by jamesporter** [lnug/speakers#140]
Maybe you have heard of Elm, the functional, front-end web language. But why would you as a full stack or backend Javascript developer learn this? Actually, it is the perfect first functional programming language (way friendlier than the others) and could change the way you think about programming Javascript. In particular you will better understand how and why to use TypeScript or Flow.

The talk comes in two parts. The first is a quick introduction to Elm via its REPL. We’ll take a look at a few of its key features and lightweight syntax. In the second part we will experience one of Elm’s superpowers: it makes making changes easy. We'll take an existing Elm App and add a new feature, letting the friendly compiler guide us to a working version.

I'm a polyglot developer currently focusing on React and React Native projects, but I dabble in lots other things. For example I recently made Isometrically: an App for creating 3D-ish graphics, ideal for websites thanks to SVG export/tiny file sizes: https://isometrically.amimetic.co.uk

I'm [@complexview](https://twitter.com/complexview) on Twitter.

**Comment by admataz** [comment]
Hey @jamesporter  - great to have you back for another talk. Was just talking about strong typing and functional programming in a meeting today and Elm came up. I think we could have done with some of your knowledge! 

I look forward to hearing this... @lnug/contributors  @lnug/organisers  - any thoughts and feedback for James?

A couple things we need to confirm (you should know this by now!): 
- [ ] Length of talk - needs to be 20-25 mins 
- [ ] Code of Conduct - as part of our community we need to make sure all speakers agree with that - see https://lnug.org/code-of-conduct.html

We have proposed talks lined up for later this month (awaiting some confirmation)  - how are you for July 25th?  - or a possibility to shuffle if there turns out to be a gap in this month's schedule.

**Comment by jkbits1** [comment]
@jamesporter thanks for the submission 👍 it's great to expand the number of people aware of current technologies for better development experience and results. 

Probably, there isn't yet a way to use Elm for Node development, is there? Apparently, people use PureScript for Node work, but the barriers to entry are much higher there. However, by showing the benefits of Elm for JS client work, it all helps to raise the awareness and demand for similar benefits on the back-end.

@admataz So I'm generally a fan of these technologies already, and definitely feel it's the way forward for all JS coding. What are your thoughts? LNUG has a history of regularly showing the benefits of functional coding to the group

**Comment by jamesporter** [comment]
Thanks @admataz I should be available both this and next month (annoyingly have missed a few recent LNUGs with various conflicts/holiday). Elm is a really nice way to learn about strongly typed fp. Such a friendly language + framework.

@jkbits1 Thanks. It is *extremely* niche but a few people do some server rendered things with Elm and I believe at least one person has done backend somehow, but the language and framework is focused on front end. For me the main benefits for Javascript development were in realising just how useful flow/typescript or (on front end) redux can be. 

Purescript and Reason both compile to quasi-readable/interoperable javascript so work much better with the existing npm ecosystem on back end. But they are both way harder to learn, a lot less friendly in practice and Reason in particular is still very rough around the edges.

**Comment by admataz** [comment]
Thanks @jkbits1 and @jamesporter  - I think the concepts and application of something like Elm will be of interest to many node devs - there are no doubt at least a few generic concepts that will be relevant. James I like that you've started with the js/node developers' perspective  - keep some hooks alive there for us mortals.  You're on for July!

**Comment by admataz** [comment]
Hi @jamesporter  - I hope all is well with you? just checking you're still good for Wednesday's meetup? I won't be there, but @FabioAntunes will be looking after proceedings.  Have a great evening...

**Comment by admataz** [comment]
I know you were there last month - so you know how to get there, but confirming venue details: 

Note, venue details: 
CONDÉ NAST
ADELPHI
1-11 JOHN ADAM ST
WC2N 6HT

Organisers will be there from around 6pm getting things set up.

**Comment by jamesporter** [comment]
Thanks @admataz

Yeah should be good... just started a new contract today but is in much closer location to meet up venue (not going to, but it wouldn't be completely ridiculous to walk). 

Have gotten slides + code ready and practiced live code bit. Will capture part of it as screen recording to keep things moving along (and will have some branches ready to checkout in case things don't quite go to plan!)

**Comment by orliesaurus** [comment]
Hey how did the talk go?

**Comment by admataz** [comment]
Hey @jamesporter  - I hope all is well, and the talk was good last Wednesday - sorry I couldn't make it! I've just had an email from Alex the video guy - apparently there was an issue with the video for your talk, and he'd like your slides so he can compile things. Can you post it so I can forward it on?

**Comment by orliesaurus** [comment]
@jamesporter if you want your video up on Youtube, can you please urgently reply to this with your slides attached or linked somewhere? Thank you!

**Comment by jamesporter** [comment]
Slides:

[intro-to-elm.pdf](https://github.com/lnug/speakers/files/2292659/intro-to-elm.pdf)

**Comment by jamesporter** [comment]
sorry completely forgot to share those

**Comment by jamesporter** [comment]
@adamdiy @orliesaurus 

I've also stuck them on S3: https://s3.eu-west-2.amazonaws.com/elm-accelerated-downloads/intro-to-elm.pdf

**Comment by admataz** [comment]
thanks @jamesporter

**Comment by admataz** [comment]
Hi @jamesporter 
Got this feedback from the Alex the video guy: 

Is there anything you can do to help?
---

Hi guys

Dominic was able to sort the slides out on Oli's presentation but I didn't realise there was a demo also in the talk.

We can't really use it without the demo, so if he is interested in having a copy of the talk, and is up for recording a demo - this is the part of the presentation we need it for:
https://www.dropbox.com/s/m4j7uo8hvq2l0kj/Elm-%20Your%20Next%20Programming%20Language%20-%20London%20Node%20User%20Group%20-%20July%202018%20MISSING%20DEMO.mp4?dl=0

Without this gap filled in I'm unsure we can complete it 😬

Let me know if he might be able to!
Cheers

Alex Frois
FilmmakerAtLarge©
07445942739
alex@filmmakeratlarge.com
www.filmmakeratlarge.com

----

**Comment by admataz** [comment]
btw... I've corrected him on your name ;)

**Comment by jamesporter** [comment]
Thanks... will try and take a look and see if I can figure something out... might be really hard to recreate a demo matching the talk.

Might actually have a go at recording a screencast version of talk, as given interruptions from construction work assume the audio can't be that great either.

**Comment by admataz** [comment]
Hi @jamesporter  - have you managed to do anything with this?

**Comment by jamesporter** [comment]
Thanks Adam

I'm still planning on having a go at recording a screencast version, probably with an update for Elm 0.19 which came out recently: https://elm-lang.org/blog/small-assets-without-the-headache and maybe change the demo a bit too plus add some FAQs-in-place-of-questions at the end. But have been pretty busy for last few weekend so haven't had a chance yet.

**Comment by admataz** [comment]
Hey @jamesporter  - seems these technical glitches were never resolved... I'm sorry I was away for this and don't know what happened. Closing this now - if you have any info or concerns please get in touch!

See you at a future LNUG!

**Comment by jamesporter** [comment]
Thanks @admataz ... still hoping to do some kind of screencast version at some point but as Elm was updated to 0.19 I'll need to actually update the talk itself.
