### ISSUE TITLE
http4js: a whirlwind tour

### ISSUE THREAD

**Issue by TomShacham** [lnug/speakers#141]
## Abstract

[http4js](https://github.com/TomShacham/http4js) is a lightweight http framework. It's immutable, has zero dependencies and is written in typescript. The [docs](https://tomshacham.github.io/http4js/#intro) are quite descriptive.

This talk would be mainly live coding to show the main benefits of using http4js over another node http framework. I've presented to colleagues who are now adopting http4js. I'd love to show the community why I think it's a better way to write web apps, by demonstration! 

I will go through the main selling points: 
 - in memory testing of your routing (no more slow end-to-end tests)
 - immutable Req/Res objects (so harder to smear state around your codebase)
 - a simple http client 
 - zero dependencies
 - support for Koa/Express backends (so you can use your favourite middleware)
 - nice things that typescript brings (autocompleting, type safety, ... ) 
 - symmetric client and server type signatures (Request => Promise\<Response\> , making proxying a cinch)

Through live coding and real examples I will show how simple and sane http4js can be!

## About me
I'm an Engineer at [Triptease](https://triptease.com/).

**Comment by admataz** [comment]
Hey @TomShacham  - thanks for you talk proposal! 

I love a bit of live code! - and this sounds like it will make a good talk too - will be good to hear what motivated your approach, and what you have learned through it too.

@lnug/contributors @lnug/organisers  - any thoughts or feedback for Tom? A seconder

A couple things we need to confirm: 
- [ ] Length of talk - needs to be 20-25 mins 
- [ ] Code of Conduct - as part of our community we need to make sure all speakers agree with that - see https://lnug.org/code-of-conduct.html

We don't generally do QA for talks - so you don't need to factor that in to your planning. 

How are you for later this month? (27th June)

**Comment by TomShacham** [comment]
Thanks @admataz I think it will be pretty fun! 
I'll be sure to include motivation and what I've learnt. 🙂 

Big yes to code of conduct, totally agree 👍 
Length of talk is good, 20 mins should be plenty.

Later this month is perfect for me :)

**Comment by jkbits1** [comment]
@admataz @TomShacham sounds good to me 🙂 the benefits sound good and it'll be interesting to hear the motivations behind the framework

**Comment by admataz** [comment]
Hi @TomShacham - just confirming you're all good and ready for your talk at this Wednesday's LNUG meetup? 

I'll be at the venue from about 6pm to get things set up. Doors open to attendees  at 6:30pm and we usually get started with talks around 7pm...  

Will be good if you can get there sometime before 6:30 just so we can test the projector and video.  Let me know if you need anything special.

Details:
Venue: 
CONDÉ NAST
ADELPHI
1-11 JOHN ADAM ST
WC2N 6HT

Your name will be on the door with security. 

If you need to contact me - my number is 07757 234443

**Comment by admataz** [comment]
Hey @TomShacham 
Thanks for a great talk on Wednesday - I had a great night - and from what I gather - so did everyone else. I think the weather and World Cup played its part in reducing attendance   - but overall it was a good night for all...

I'll post the link to the video of your talk here when it's ready

Hopefully see you again at another LNUG meetup soon!

**Comment by admataz** [comment]
Also if you have any feedback from your perspective as a speaker - would love to hear it...

**Comment by admataz** [comment]
Hey @TomShacham   - I've at last uploaded the videos: 
https://www.youtube.com/playlist?list=PLam_80-FY3vQZKP5F_O2Bo4A8mQqyvh_J

I'll be away the next couple meetups - but things are ticking along. Hopefully see you when I'm back at September's LNUG!

**Comment by TomShacham** [comment]
Awesome thanks Adam.

Thanks for having me, it was really fun. 

My only feedback is positive: you made it clear what format talk you expected and the venue was well prepared so everything went swimmingly :) 

See you again soon
