### ISSUE TITLE
Building an Alexa Skill in 20 minutes using NodeJS

### ISSUE THREAD

**Issue by muttoni** [lnug/speakers#144]
Developers can build engaging voice experiences, aka Skills, for their services with the Alexa Skills Kit. In this 20 minute session, learn how to build a voice experience for Amazon Alexa: from idea to working skill including some best practices to consider along the way.

**Personal Info:**
Tech Evangelist at Amazon, Twitter: [@muttonia](https://twitter.com/muttonia)

**Comment by admataz** [comment]
Hi @muttoni - thanks for your talk proposal!

This sounds like a fun talk - it will be great to hear how node.js developers can experiment with things like Alexa - will you be giving us a demo? 😄  👍 

How are you fixed for August 22nd or October 24th? 

@lnug/contributors @lnug/organisers  - thoughts, feedback, seconder?

**Comment by muttoni** [comment]
Of course, we'll be implementing it together, I usually ask for an idea from the audience to keep things interesting (also for myself 😉). We'll have a working prototype within 20 minutes. 

Can't do August 22nd unfortunately, but can do October 24th. I've tentatively blocked my calendar in the meantime ;)

**Comment by admataz** [comment]
Thanks @muttoni! Looking forward to hearing it.  Added you to October's meetup plans.

@lnug/contributors  @lnug/organisers  - please can someone provide their 2nd thoughts/support for this proposal?

**Comment by admataz** [comment]
Hi @muttoni  - yes if you're still up for it, I'm happy to confirm

**Comment by muttoni** [comment]
Yup :) Let's confirm it.

**Comment by admataz** [comment]
you're on!  - looks like it's going to be a good and full evening of talks!

**Comment by admataz** [comment]
Hi @muttoni !
Just getting everything finalised for tomorrow's meetup... I trust all is still good from your side?

Some details: 

We are hosted  at Condé Nast
Adelphi Building
1-11 John Adam Stree
WC2N 6HT

We aim to start talks at 7pm - it would be great if you can get there some time between 6:30pm and 7pm? 

If you need to contact me at any point - my number is 07757234443

See you tomorrow!

**Comment by admataz** [comment]
I meant to add - when you get to the venue - your name will be with security - ask for Michelle Garret if there are any issues.

**Comment by muttoni** [comment]
Ok, great. Yes I confirm for tonight!

**Comment by admataz** [comment]
Hi Andrea
Thanks for a great talk last week - it was very well presented, and really kept the audience interested  - we were talking about the talks later at the pub - and yours was a favourite for some... I enjoyed the live coding and audience interaction...

I'll post a link here with the video when it's ready.

Meanwhile if you have any feedback for us on the evening, or how LNUG is run generally - I'd welcome your thoughts! Also if you want to share any resources or links related to your talk - please post them here.

Hopefully see you again at a future LNUG meetup!

**Comment by admataz** [comment]
Thanks again for the great talk - it's now available on our YouTube channel:
https://www.youtube.com/playlist?list=PLam_80-FY3vQE2I_NP0F3dTFsVHGrTTVX

See you soon!
