### ISSUE TITLE
Building and deploying Cloud Native Node.js applications

### ISSUE THREAD

**Issue by seabaylea** [lnug/speakers#145]
[Abstract of your talk]
The CloudNativeJS.io community project provides a number of assets, tools and core modules for building Cloud Native Node.js applications. This session will show use how to use those to easily take an existing application and deploy it to Kubernetes with full support for liveness checks, metrics and request tracking.

[A bit about you, e.g. current job, twitter handle, etc.]
Chris Bailey, Chief Architect, Cloud Native Runtimes, IBM (@chris__bailey)
Beth Griggs, Node.js Core Collaborator, IBM (@BethGriggs_ )

The [CloudNativeJS.io](http://cloudnativejs.io) community project was announced last week at the Node Summit. This would be a talk covering how to use those assets to enhance an existing Express.js app to add "Cloud Native" capabilities, and how to deploy it to Kubernetes.

This would be an ideal second talk to the one proposed under Issue #143, showing how you can update your dockerized application and deploy it.

**Comment by admataz** [comment]
Hey @seabaylea - thanks for the proposal... this sounds very exciting  - let's see if we can make October's meetup themed around deploying node with Docker and Kubernetes. I'd love to hear some of the detail and motivation for the efforts going on around this. 

@lnug/contributors @lnug/organisers  - can I get a seconder?

**Comment by admataz** [comment]
#143 is scheduled for October - I presume that will suit you?

**Comment by admataz** [comment]
Hi @seabaylea  - are you back in town? Just getting the next couple months of talks in line - are you still keen for a Docker-themed LNUG with @d4nyll  and #143 ? 

I think it will be great!

**Comment by seabaylea** [comment]
Hi Adam:

I'm still keen, but unfortunately I'm now going to be at JavaOne on October 24th talking about using Node.js with existing Java microservices.

A couple of my colleagues are available the session instead of me though -  @BethGriggs and @neeraj-laad. Both are involved in the CloudNativeJS project, and Beth is also a core collaborator on Node.js.

**Comment by jkbits1** [comment]
@admataz @seabaylea excuse me chipping into this conversation about this great talk, just a couple of points:

1) one of the tricky things for me in any dockerised app is management of environment variables. Not sure if that fits into the 20 minutes, but I'm always looking for elegant solutions there
2) both alternative speakers sound great, but it's always a boost to have people such as core collaborators turn up at LNUG

**Comment by admataz** [comment]
Hi @seabaylea  - sorry you can't make it - but it would be great to have either/both @BethGriggs and @neeraj-laad in your stead to present about CloudNativeJS - can you ask one of them to create an issue here so we can associate the talk with them for October?  

Looking forward to it! 
[cc @d4nyll  - FYI]

**Comment by admataz** [comment]
Thanks @seabaylea

**Comment by admataz** [comment]
closing this because #154 thanks!
