### ISSUE TITLE
GraphQL on the Edge 

### ISSUE THREAD

**Issue by sevki** [lnug/speakers#147]
# Abstract

An introduction to GraphQL on Serverless. We'll talk about the benefits of running GraphQL (and other API gateway patterns) on the Edge (the performance benefits batching and so on).

# Speaker

Sevki Hasirci is a Systems engineer at Cloudflare, working on developer tools, his day to day responsibilities are making developers more productive.

# Other
I confirm my talk is 20 mins long in total.
I confirm that I will abide by the Code of Conduct

**Comment by orliesaurus** [comment]
Great, see you on the 22nd! Thanks for submitting your talk!

**Comment by orliesaurus** [comment]
Hi @sevki!
You're live: https://www.youtube.com/watch?v=WVn9yeV3vLo
