### ISSUE TITLE
A New Way to Profile Node.js

### ISSUE THREAD

**Issue by davidmarkclements** [lnug/speakers#148]
## Abstract 
It’s been weeks and the organisation you work for seems to be slowly turning against you. At least that’s what it feels like. User experience is poor because of slow API’s, sales are being missed, performance-linked SEO heuristics are causing a drop in page ranking. Mobile users have all but given up. Operations have reported that a critical Node.js service owned by your team is spinning at 70-100% CPU, and all parts of the application dependent on the service are experiencing intermittent slowdowns or in some cases, complete unavailability. What are you going to do now?

## Speaker
David Mark Clements is a Node.js performance specialist and author of Node Cookbook. He is currently serving as Principal Architect with nearForm. David has been coding, speaking and writing about Node.js since Node 0.4 and has worked with frontend JavaScript for 20 years. Of note among David’s open source contributions is Pino, the fastest Node.js logger available (co-authored with Matteo Collina) and 0x, a JavaScript stack profiling tool. David’s book about Node.js, the aforementioned Node Cookbook, is now in its third edition.

**Comment by orliesaurus** [comment]
Thank you so much!

**Comment by orliesaurus** [comment]
Here we go! Thank you again: https://www.youtube.com/watch?v=y7PZ4q5gk8o
