### ISSUE TITLE
Zero Knowledge Proofs in Node.js

### ISSUE THREAD

**Issue by framp** [lnug/speakers#149]
### Abstract
Zero Knowledge Proofs are one of cryptography's best hidden gems and they're behind recent advancements in privacy conscious crypto-currencies.
We're going to see how to use them in node.js and improve your applications' security, whether centralised or distributed.

### About me
Federico Rampazzo is a Software Entrepreneur and Engineer with a passion for Functional Programming, Cryptography and Payments (especially as in "receiving payments" - but also Payment System architectures).
He works for Tes, the biggest community of educators in the world and home to an excellent marketplace for teachers' resources.

-----

I abide to the Rule of Conduct and I will keep my talk under 20 minutes

**Comment by orliesaurus** [comment]
Here we go: https://www.youtube.com/watch?v=cMoD0wIxIpQ !
