### ISSUE TITLE
Large-scale refactoring with codemods

### ISSUE THREAD

**Issue by eddyerburgh** [lnug/speakers#152]
Refactoring is part of the process of maintaining an application, but large scale refactoring that are more complicated than a find and replace are time consuming. 

Codemods are a tool to refactor code by manipulating the abstract syntax tree (AST). In this talk I'll teach you what ASTs are, why we use ASTs in tools like Babel and eslint, and how to write a codemod that manipulates an AST.

**About me**
I'm a Vue core contributor, and software engineer at the BBC. https://twitter.com/EddYerburgh

**Comment by orliesaurus** [comment]
Hi Edd,
Interesting subject. Could you confirm the talk is ~20mins long in total; also, please confirm that it will abide by the Code of Conduct.

**Comment by eddyerburgh** [comment]
Yes I confirm the talk will be ~20mins length and I will abide by the code of conduct

**Comment by admataz** [comment]
Hey Edd, 
Thanks for submitting your talk proposal here - I also think this would make an interesting talk for node developers  and for understanding our tooling.

How are you for November 28th?

**Comment by eddyerburgh** [comment]
Thanks @admataz 

Yes I can do November 28th 👍

**Comment by admataz** [comment]
You're on! I'll remind you closer to the time...

**Comment by admataz** [comment]
@eddyerburgh  - it's tomorrow!!  just confirming -  still good for giving your talk? 

The venue is 
CONDÉ NAST
ADELPHI
1-11 JOHN ADAM ST
WC2N 6HT

Your name will be on the door with security. If there's any problem  - please ask for Michelle Garret from Conde Nast

We will be there from around 6:15pm - and getting a few things set up - talks will start soon after 7pm. 

If you need to contact me - my number is 07757234443

See you there!

**Comment by eddyerburgh** [comment]
Yep sounds good, see you then :)

**Comment by admataz** [comment]
Hi @eddyerburgh  - thanks for a great talk on Wednesday - very interesting and much appreciated. 

I'll post video links here when they are available...

Meanwhile  - we welcome any feedback from speakers on the LNUG process and the night in general. 

See you again soon!

**Comment by orliesaurus** [comment]
Video posted on our YT channel! Njoy
