### ISSUE TITLE
Building and deploying Cloud Native Node.js applications

### ISSUE THREAD

**Issue by BethGriggs** [lnug/speakers#154]
The CloudNativeJS.io community project provides a number of assets, tools and core modules for building Cloud Native Node.js applications. This session will show users how to use those to easily take an existing application and deploy it to Kubernetes with full support for liveness checks, metrics and request tracking.

Beth Griggs, Developer & Node.js Core Collaborator, IBM Runtimes ([@BethGriggs_](https://twitter.com/BethGriggs_) )
Neeraj Laad, Developer, IBM Runtimes ([@NeerajLaad](https://twitter.com/NeerajLaad))

**Comment by admataz** [comment]
Thanks @BethGriggs !

**Comment by admataz** [comment]
Hi @BethGriggs 

Just getting everything finalised for tomorrow's meetup... I trust all is still good from your side?

Some details: 

We are hosted  at Condé Nast
Adelphi Building
1-11 John Adam Stree
WC2N 6HT

We aim to start talks at 7pm - it would be great if you can get there some time between 6:30pm and 7pm? 

If you need to contact me at any point - my number is 07757234443

See you tomorrow!

**Comment by admataz** [comment]
I meant to add - when you get to the venue - your name will be with security - ask for Michelle Garret if there are any issues.

**Comment by admataz** [comment]
Hi Beth and Neeraj
Thanks for a delivering great talk last week - I really enjoyed it  - it's great to hear what you are doing for the community and the technical overview was really sound.  I had really positive feedback about all the talks and the evening in general - I hope you had a chance to meet some of our members and chat to them... 

If you have any feedback for us -  or thoughts about how LNUG is run - I'd welcome it - please drop us a line. 

I'll update and close this issue when I have the link to the video.


Hopefully see you again at a future event!

**Comment by admataz** [comment]
If you have your slides available anywhere for us to share - please can you post a link here?

**Comment by BethGriggs** [comment]
Link to the slides - 
https://www.slideshare.net/BethanyNicolleGriggs/london-nodejs-user-group-cloudnative-nodejs-121990911

Thanks for having us 😄

**Comment by admataz** [comment]
Thanks again for the great talk - it's now available on our YouTube channel: 
https://www.youtube.com/playlist?list=PLam_80-FY3vQE2I_NP0F3dTFsVHGrTTVX

See you soon!
