### ISSUE TITLE
Async Iterators

### ISSUE THREAD

**Issue by jamiemccrindle** [lnug/speakers#156]
### Abstract

An exploration of async iterators in NodeJS including when and why to use them, how they compare to other reactive libraries, how they perform and what to look out for when you do use them.

### About me

JavaScript enthusiast, Open Source Contributor, Co-founder of a number of successful startups, OpenBankHack17 hackathon winner, Head of Technology for Business Banking at Investec. You can find me at [https://jamie.mccrindle.org](https://jamie.mccrindle.org)

**Comment by admataz** [comment]
Hey @jamiemccrindle  - thanks for submitting your talk proposal here...

This sounds good! - I  think a view on async iterators and how they can be useful will be a good talk.

@lnug/contributors @lnug/organisers  - can we get a seconder and provide any thoughts/feedback?

**Comment by admataz** [comment]
@jamiemccrindle - how are you for January 23rd or February 27th?

**Comment by jamiemccrindle** [comment]
February the 27th, please!

**Comment by orliesaurus** [comment]
Hey - Is this talk ready or do you still have to write the slides?
IMHO for this kind of topic having the slides ahead would help a lot to review the submission and it would help us schedule it in a "wider" theme for the night, which could as well be Asynchronous programming

**Comment by orliesaurus** [comment]
Alright thanks for sharing, yeah you're right about need a little more nodejs examples!

**Comment by admataz** [comment]
Hey @jamiemccrindle  - you're on for Feb!  seems a long way away - but I'm sure it will be upon us before we know it!

**Comment by admataz** [comment]
Hi @jamiemccrindle   - it's today! 

Just confirming - How are things looking for your talk? All good?

details of the venue: 
```
CONDÉ NAST
ADELPHI BUILDING
1-11 JOHN ADAM ST
WC2N 6HT
```

I will be there from about 6:15pm getting a few things set up - people start arriving around 6:30 and we plan to start with talks after a brief intro and welcome at 7pm

If you have any issues - please call me: 07757234443

See you there!

**Comment by jamiemccrindle** [comment]
@admataz I confirm that things are looking good for my talk! Looking forward to seeing you there.

**Comment by admataz** [comment]
Hey @jamiemccrindle Thanks so much for your talk at LNUG the other week 
The video is at last online: https://www.youtube.com/watch?v=PN9HQoYW2vc&index=1&list=PLam_80-FY3vSjatQNzSPQhBAb_hrSlWJk

If you have any feedback around the event or organisation - please let us know!

Hopefully see you again at LNUG soon!
