### ISSUE TITLE
Building Cross Platform apps with Titanium

### ISSUE THREAD

**Issue by Topener** [lnug/speakers#157]
If you don’t want to learn a new language but still want to make a quality mobile app, then a cross platform tool like Titanium is what you’re looking for. In this talk you’ll be shown how easy it is to start building your app using skills you already know from web and NodeJS.

**About me**
Rene Pot, Developer Evangelist at Axway Appcelerator since 2018. I've been developing since I was 12, full time cross-platform mobile developer since 2011. 

Twitter: [@Wraldpyk](https://twitter.com/wraldpyk)

**Comment by admataz** [comment]
Hey @Topener 

Thank you for your talk proposal! 

Just some feedback  - that I think will help your talk being well received with our meetup attendees:   can you assure us  in your talk proposal and abstract that this will mostly be a technical talk, and not too much of a product promo or sales pitch? As node developers we'd love to hear about tooling and platforms and what kind of technical challenges can be met with something like Titanium - but we don't want to sit through a marketing pitch. Some war stories from users will be interesting. You could show us how awesome it is with some live coding? It will be great to hear how great your platform is from a real and practical perspective - and I think this would make a great talk with the right approach. 

@lnug/contributors @lnug/organisers  - any thoughts? 


meanwhile, if you could... we're asking speakers to confirm: 

- [ ] Talk will be ~20 minutes
- [ ] You agree to our [Code of Conduct](https://lnug.org/code-of-conduct.html) 
   

How are you fixed for January 23rd or February 27th?

**Comment by Topener** [comment]
Hi! Absolutely a technical talk. I might be a dev evangelist but I fully will talk about a completely free and open source framework and basically how to use it. 

I usually put in some live coding so will do so here as well and I’ll bring some real life examples to the table!
February 27th could work for me. 

And I agree with the code of conduct and will keep my talk in 20 minutes

**Comment by Topener** [comment]
@admataz haven't heard back on this, still on for Feb 27?

**Comment by admataz** [comment]
hi @Topener  - sorry  - I dropped the thread on this... 😞  - Feb 27th is good for me - you're on!

**Comment by Topener** [comment]
@admataz thanks! Going into scheduling :)

**Comment by admataz** [comment]
Hi @Topener   - it's today! 

Just confirming - How are things looking for your talk? All good?

details of the venue: 
```
CONDÉ NAST
ADELPHI BUILDING
1-11 JOHN ADAM ST
WC2N 6HT
```

I will be there from about 6:15pm getting a few things set up - people start arriving around 6:30 and we plan to start with talks after a brief intro and welcome at 7pm

If you have any issues - please call me: 07757234443

See you there!

**Comment by Topener** [comment]
All good @admataz! See you there between 6:15-6:30 I expect.

**Comment by admataz** [comment]
hey @Topener  - thanks so much for the talk the other week - it was great to meet you.   - hopefully see you again soon. If you have any feedback to share about the way things went and the organisation - please let me know! Meanwhile - the video from your talk is now live: 

https://www.youtube.com/watch?v=12GA9oDK5gU&list=PLam_80-FY3vSjatQNzSPQhBAb_hrSlWJk&index=2
