### ISSUE TITLE
ECMAScript Modules: They're Coming...

### ISSUE THREAD

**Issue by trevorah** [lnug/speakers#158]
ECMAScript modules are just around the corner, but they may not be what you expect. I'll go into the reasoning behind the change and what it means for the future of javascript.

I'm Andy, a full stack JS developer with a love of native apps. I'm a contractor @ DAZN and my twitter handle is `@trevorah_`.

**Comment by admataz** [comment]
Yes! This is a great topic  - and I'd love to hear the about the inner workings of how es modules are different from common.js  - and how that will affect the way we think about loading dependencies. A nod to the drama around naming/ extensions will be nice, and also the current state of polyfills. 

@lnug/contributors @lnug/organisers  - any thoughts? 

you've been here before - you know the drill... we're asking speakers to confirm: 
- [ ] Talk will be ~20 minutes
- [ ] You agree to our [Code of Conduct](https://lnug.org/code-of-conduct.html) 
   
How are you fixed for  November 28th?

**Comment by trevorah** [comment]
November 28th is perfect!

**Comment by admataz** [comment]
you're on!

**Comment by admataz** [comment]
Hey @trevorah  - just confirming...  all good for tomorrow evening?

**Comment by trevorah** [comment]
Yep yep!

**Comment by admataz** [comment]
Hey @trevorah  - thanks again for you talk on Wednesday - speak soon

**Comment by trevorah** [comment]
No worries, thanks for running it!

**Comment by admataz** [comment]
this is all done... check the video! https://www.youtube.com/watch?v=3ieHIh_A8dU&list=PLam_80-FY3vRw4EwG8GbwY6bN4KgIf5ek
