### ISSUE TITLE
Testing apps with third-party API integrations

### ISSUE THREAD

**Issue by mikesol** [lnug/speakers#160]
**Testing apps with third-party API integrations**

In this talk we will examine strategies and best practices to develop and test node apps that make heavy use of third-party API integrations. As reliance on third-party services becomes more and more prevalent in the node ecosystem, developers need cost-effective, secure, reliable and fast ways to mock these services for both dev/staging environments and testing.

We will start with looking at nock, and open-source mocking solution for local development, and move onto unmock which provides mocks-as-a-service of popular APIs.

The session will have live coding for both nock and unmock using express to create a simple microservice and jest for testing. It will also present several popular design patterns for isolating and testing third-party integrations as well as strategies for integration testing apps that rely on third-party APIs, including corner-case and error testing.

Presenters will be myself (Mike Solomon - unmock.io) and I will invite some of our London-based clients to chime in about the importance of testing third-party integrations and the emerging ecosystem of developer sandbox environments for API testing.

This is the same talk that we are giving at SFNode (https://github.com/sfnode/sfnode/issues/98). We'd love to bring it to your community, share our learnings and hear your feedback.

**Bio**
Mike Solomon is the founder and CEO of Meeshkan (meeshkan.com), a Helsinki-based DevOps company. A music major at Stanford University, Queen's University Belfast and the University of Florida, Mike has been a guest researcher at the University of Paris VI and has held the post of artistic director of the Ensemble 101 (ensemble101.fr) from 2011 until the present day. While working at the IRCAM as a computer music designer, he fell in love with Machine Learning and founded Meeshkan to ease several DevOps pain points in the ML pipeline. Since then, Meeshkan has expanded to other areas of DevOps, including API testing with unmock (unmock.io).

**Comment by mikesol** [comment]
Hi,

- [x] The talk will be 25 minutes.
- [x] Also, I agree with the [code of conduct](https://lnug.org/code-of-conduct.html).

March 27th is better for us if that's OK with you guys. Also, do you guys need help with event sponsorship/venue?  We have a few partners in London to whom I can reach out.

**Comment by admataz** [comment]
You're on! - looking forward to it! 🎉

**Comment by neshka** [comment]
Hi @mikesol,

how are you today?

I just want to confirm if you are ready for Wednesday.
Please let me know.

Details of the venue:

CONDÉ NAST
ADELPHI BUILDING
1-11 JOHN ADAM ST
WC2N 6HT

I will be there from about 6:15pm, people start arriving around 6:30 and we plan to start with talks after 7pm.

If you have any issues - please call me: 07752387427 or @admataz 07757234443

See you there!
Aga

**Comment by mikesol** [comment]
Doing well, thanks for asking & thanks for the details.  Everything looks good!

One question: a friend of mine in London, Bill Earner, would like to attend the meetup.  Is it OK if he comes?

**Comment by neshka** [comment]
Hi,

yes sure! 
We will put his name on the list.

See you on Wednesday! 
Aga

**Comment by neshka** [comment]
Hi @mikesol 

Thank you for your speech today!
I will send you the link when video is ready.

In touch :)

**Comment by mikesol** [comment]
Thanks so much for having me!

**Comment by admataz** [comment]
Hi @mikesol  - I've at last managed to upload the videos from last month's meetup - you can see them here: https://www.youtube.com/playlist?list=PLam_80-FY3vQKYb5bC1gzH1384eds6-IQ

Thanks again for the talk - please let us know if you have any feedback from an organisational point of view - and hopefully see you back at an LNUG meetup soon! 

(closing this issue - but feel free to add comments if you have any)
