### ISSUE TITLE
Bootstrapping a startup with SailsJS

### ISSUE THREAD

**Issue by SBirchall818** [lnug/speakers#161]
# Abstract
Over the last 18 months I have bootstrapped my startup using SailsJS. What did I learn? What do you get out of the box? How has the project evolved? Am I happy with my choice 18 months later?
I have previously used Rails, ASP.MVC and Laravell. I had decided on Node for the backend - but what framework would I choose? What do I really need? What can I trust? How does SailsJS differ to the aforementioned frameworks and how much bang can my buck get?

## About  Me
Hi I'm Simon, physics graduate, software engineer, team lead and now technical co-founder of Kiffgo.com.
After previously working at a consumer facing marketplace startup I teamed up with a motivated co-founder to create my own. As the technical co-founder I had some stack decisions to make. I arrived at Node + SailsJS. From webpack integration, unit testing to production deployment I've done it with SailsJS and am willing to share my experience. I've been to LNUG a number of times in the past and have always found it a friendly, welcoming and informative experience.

**Comment by admataz** [comment]
Hi @SBirchall818 

This sounds great - I'd love to hear about your sailsjs experience with a real world application- the real-world choices you faced. Sounds like it could make an engaging story/talk that many of our attendees would appreciate and enjoy and probably relate to. 

@lnug/contributors  - any thoughts or feedback for Simon? Can we get a seconder please?

**Comment by orliesaurus** [comment]
Great job @SBirchall818 - is this your first time speaking? You sound like a great person! Can't wait to hear your journey in the startup world

**Comment by SBirchall818** [comment]
Hi, thanks @orliesaurus, this would be my first time speaking at LNUG. I'm doing another talk at our company run react meetup, so not my first time overall ;)

[React Everywhere](https://www.eventbrite.co.uk/e/react-everywhere-app-web-app-tickets-57601749383?aff=ebdssbdestsearch)

**Comment by admataz** [comment]
@SBirchall818 how are your plans for  April 24th? Would love to hear your talk

**Comment by SBirchall818** [comment]
@admataz April 24th works for me. Looking forward to it

**Comment by admataz** [comment]
great! your on for April

**Comment by admataz** [comment]
Hey @SBirchall818   - just confirming you are all good for this Wednesday? 

How are things looking for your talk? All good?

details of the venue: 

```
CONDÉ NAST
ADELPHI BUILDING
1-11 JOHN ADAM ST
WC2N 6HT
```

I will be there with other organisers from about 6:15pm getting a few things set up - people start arriving around 6:30 and we plan to start with talks after a brief intro and welcome at 7pm

If you have any issues - please call me: 07757234443

See you there!

**Comment by SBirchall818** [comment]
Yes - everything's good for Wednesday.
See you then

Simon

**Comment by admataz** [comment]
Hey @SBirchall818  -that was a great talk last week - thanks so much for putting all that effort into presenting and sharing your knowledge - it's very much appreciated. I hope you found it rewarding and had good discussions. 

If you have any feedback about LNUG and the organisation of things - please add it here

When the video is ready - I'll post a link here to it.

**Comment by SBirchall818** [comment]
Hi Adam,

Thanks for letting me speak. Hopefully people will have taken something
useful away from the talk. If you've received any feedback on my content or
presentation please feel free to pass that on.

Si

**Comment by admataz** [comment]
Hi @SBirchall818  - your video is now online at our LNUG channel https://www.youtube.com/watch?v=_xcF7DBqd08&list=PLam_80-FY3vRIHHhzyFPiXMGQLNfOdxk3 

I heard nothing but good things about your talk on the night - people seemed interested in Sails  and how it compared to their current stack. Did you manage to have any follow up conversations at the pub later? 

Closing this - hopefully see you back at LNUG soon!
