### ISSUE TITLE
Zero to prod in 2 hours

### ISSUE THREAD

**Issue by hewIngram** [lnug/speakers#165]
## Zero to prod in 2 hours

Writing code is great, working out how to host it is less great (for most people!). We recently ran a workshop at CityJs and made sure that everyone walked out of that workshop with an app deployed. In this talk we’ll chat through some of the things that helped us do that (Netlify, serverless functions and Vue) as well as some alternatives (The Serverless framework + lambda etc, firebase and other SPA hosting). The aim? To get everyone to feel empowered to build something fun (and potentially silly).

## About Us

Hew Ingram
I’m a Full Stack engineer at Applied (a little startup striving to make hiring fairer, smarter and easier - driving forward diversity in companies). I predominantly use JS but dabble with bits of python, PHP and others. Lover of all things Javascript + a big fan of building cool (weird) things, often for the hell of it.

Thomas Ankcorn
I'm a Software Engineer at BAE.  I like JavaScript , starting but not finishing side projects and cats. Often referred to as some dude with a scooter.

**Comment by admataz** [comment]
this is great! so glad you're able to bring this to LNUG

**Comment by claireinez** [comment]
What a lovely topic for a talk! I'm really excited for this one ☺️

**Comment by neshka** [comment]
Awesome!  https://www.youtube.com/watch?v=K4ybXp8wZ44

**Comment by admataz** [comment]
Now also in the LNUG youtube Channel! https://youtu.be/EZBpdq8RU-c 🎉
