### ISSUE TITLE
Robots and Food

### ISSUE THREAD

**Issue by onic** [lnug/speakers#166]
At Karakuri we build robots for the food industry. I would love to share a peek into our decentralised architecture and how the different robot components interact and communicate with each other. As the physical world is quite I/O heavy, Node.js (TypeScript) was a great choice as our main programming language/framework. 

https://www.linkedin.com/in/orfeonicolai/
I'm a computer scientist with almost 20 years of industry experience. I have a double Masters degree in Innovation Design Engineering and am the course leader of the robotics course at the Imperial College Global Summer School. I work as Head of Software at Karakuri, a robotics startup. We just secured a seed funding round led by Ocado (https://techcrunch.com/2019/05/09/robotics-startups-wont-win-without-also-incorporating-ai-as-karakuris-fundraise-shows/?guccounter=1)

**Comment by onic** [comment]
Here is a video of the robot in action: https://vimeo.com/333554113

**Comment by admataz** [comment]
hi @onic  - this sounds really interesting! we'd love to hear how you are using node.js in this way - fascinating. 

How are you for June 26th?  or July 24th?

**Comment by onic** [comment]
Great! You can book me in for June 26th.

Let me know if you need any material from me beforehand

**Comment by hewIngram** [comment]
This sounds SUPER interesting @onic

**Comment by admataz** [comment]
You're on for next month @onic ! Will add it to the announcments at tonight's meetup

**Comment by neshka** [comment]
Hi @onic! :)

how are you today?

I want to confirm if you are ready for Wednesday.
Please let me know.

Details of the venue:

CONDÉ NAST
ADELPHI BUILDING
1-11 JOHN ADAM ST
WC2N 6HT

I will be there from about 6:15pm, people start arriving around 6:30 and we plan to start with talks after 7pm.

If you have any issues - please call me: 07752387427 or @admataz 07757234443

See you there!
Aga

**Comment by onic** [comment]
Hi @neshka. Yes, all ready for Wednesday. See you there!

**Comment by neshka** [comment]
Hi @onic!

Hope you are well :) Thanks so much for your talk at LNUG yesterday.
We will send you the video as soon as it's ready.

Best,
Aga

**Comment by admataz** [comment]
At last - live on the LNUG youTube channel: https://youtu.be/Zrtqrx_pcOY 🎉
