### ISSUE TITLE
Using ML in NodeJS

### ISSUE THREAD

**Issue by Berkmann18** [lnug/speakers#167]
# Abstract
An overview of ML in JS and what I was able to do with it.

How and why would you use Machine Learning in NodeJS.

I’ll go over some general concepts in ML and then dive into how I leveraged limdu and created a multi-label classifier (called ac-learn) and how you can do the same. All while seeing how fun and amazing it can be.

The talk would be focused on giving you the pointers and tools to solve problems where ML is usually the best solution as well as how you can hit the ground running.

# About me
I'm a Computer Science placement student working at BWC in Project Management, Web Dev and various other things (e.g. GDPR and IT support).
I've been working with JS for about 7 years and with NodeJS for about 3 years and simply love almost everything about it.

Twitter: @Berkmann18

**Comment by hewIngram** [comment]
This sounds like it could be fun! 
I'd love to hear about any benefits JS has over other languages for machine learning and some comparison of ml libraries (I've definitely been told very mixed things about whether tf.js is useful or not)

**Comment by Berkmann18** [comment]
@hewIngram Good question. The benefits of using JS over classical choices (Python and R) are as follows:
- you can use/train/test a model directly in the browser as well as in the NodeJS environment (so no need to have bridges/interfaces between different languages)
- integrations into JS systems is a lot easier with JS ML libraries/frameworks
- things such as online-learning are more incorporated into applications

I haven't tried (_yet_) all the ML libraries I found (and plan on at least mentioning in my talk), as I used to do ML stuff in Python for bioinformatics and malware analysis with various algorithms and methods.
It's mainly because I knew what method I needed to use to solve a problem I was facing for a feature I'm working on so I didn't get round to try what wouldn't help me solve the problem.

But I can definitely give a comparison of some classification and NLP libraries if you want me to.

**Comment by admataz** [comment]
hey @Berkmann18  - thank you so much for you talk proposal - this is a great topic - and I think our members will really love to hear what you have to say. 

Just in terms of the talk format and your abstract - let's tease a narrative out of it - can you tell a story of some kind? - or illustrate the kinds of problems/challenges you or JS developers may want to use ML to solve. I would like to see it go further than a list of language features or comparison - unless you can do some live coding benchmarks or something? Might make it exciting... 

Happy to talk this through with you and help shape it  - it's about time we had someone take on this topic!

**Comment by Berkmann18** [comment]
@admataz 
> can you tell a story of some kind?

Yes, I can.

>  or illustrate the kinds of problems/challenges you or JS developers may want to use ML to solve

Yes, I was planning on covering that in my talk.

> unless you can do some live coding benchmarks or something? Might make it exciting...

I was planning on doing a live coding demo using either a library I found or one/and one I created on top of it to solve problems I had.

**Comment by admataz** [comment]
@Berkmann18  - sounds great - can you flesh out the narrative aspect a little in your opening proposal - that's what goes onto the website and meetup pages and gets people excited about attending - that will be really useful! Thanks!

**Comment by Berkmann18** [comment]
@admataz Sure, I've edited the abstract to include a paragraph on that.
Let me know if it's great.

**Comment by Berkmann18** [comment]
@admataz Did you had a chance to look at the edit?

**Comment by hewIngram** [comment]
I totally think theres an awesome talk in here @Berkmann18 - are you going to be at LNUG this month? Maybe we can grab 5 with @admataz to try to flesh out a bit of a story/flow to it and then get you booked in!

**Comment by Berkmann18** [comment]
I am 😁.
Sure, we could have a chat about it.

**Comment by Ankcorn** [comment]
@Berkmann18 I will be at LNUG and am happy to help you flesh it out too :+1: See you next wednesday!

**Comment by neshka** [comment]
Hey @admataz @Ankcorn @hewIngram :)
Did you have a chance to discuss this topic with @Berkmann18?

**Comment by Ankcorn** [comment]
We didn't get a chance to help @Berkmann18 at the meetup but I have just sent him an email with some advice.

**Comment by neshka** [comment]
That's so great, thanks @Ankcorn!

**Comment by admataz** [comment]
HI all  - sorry been out of town and just catching up. Sorry we haven't managed to speak - last meetup was just busier for me than I expected!

@Berkmann18  - talk abstract is great -how are your plans for 24th July  - can we schedule you in?

**Comment by Berkmann18** [comment]
> HI all - sorry been out of town and just catching up. Sorry we haven't managed to speak - last meetup was just busier for me than I expected!

No worries, I've been discussing with @Ankcorn on how I could improve the abstract and intro of the talk (which will be reflected on the OP as soon as we're both satisfied with it).

> @Berkmann18 - talk abstract is great -how are your plans for 24th July - can we schedule you in?

I'll be coming to the event (possibly with 1-2 guests who I doubt are on Meetup) and I can't wait for that meetup to happen.

**Comment by neshka** [comment]
Hey @Berkmann18, we can put their names on the list - no problem.

**Comment by Berkmann18** [comment]
@neshka Awesome.
Rupert Berkmann
Alexander Berkmann

**Comment by neshka** [comment]
Hi @Berkmann18,

how are you?

I just want to confirm if you are ready for Wednesday.
Please let us know.

Details of the venue:

CONDÉ NAST
ADELPHI BUILDING
1-11 JOHN ADAM ST
WC2N 6HT

People start arriving around 6:30 and we plan to start with talks after 7pm.

If you have any issues - please call me: 07752387427 or @admataz 07757234443

See you there!
Aga

**Comment by Berkmann18** [comment]
Hi @neshka 

I'm fine and yourself?

I am (to the point of preparing my excitement-filled tweet :).

> People start arriving around 6:30 and we plan to start with talks after 7pm.

I'll try to be there at 6-6:15 pm to make sure I can get the setup right even tho I'm supposedly not the first to talk.

See y'all there.

**Comment by neshka** [comment]
Hey @Berkmann18! I'm great, thank you.
Your guests are on the list.

See you tomorrow! :)

**Comment by neshka** [comment]
Hi @Berkmann18, how are you? Thank you so much for the talk yesterday!
We will send you the video as soon it's ready.

**Comment by Berkmann18** [comment]
Hi @neshka, I'm fine and yourself?
You're welcome :smiley:

Awesome!!

**Comment by admataz** [comment]
And now available in the LNUG Youtube channel! https://youtu.be/TJI1NzhDAGE 🎉 

Thanks  for your talk - very good.  see you later this month.

**Comment by Berkmann18** [comment]
@admataz Awesome, thank you!
