### ISSUE TITLE
Create your own state management library

### ISSUE THREAD

**Issue by jamesporter** [lnug/speakers#169]
## Abstract

How hard is it to make your own state management library? By using React hooks, Context and other open source projects you can easily build your own useful library.

I wanted first class TypeScript support, immutable data, zero boilerplate and hassle free wiring. I built it in a few dozen lines of code: [Immutable Context](https://github.com/jamesporter/immutable-context).

I'll demo how to use it via a [Code Sandbox demo](https://codesandbox.io/s/intelligent-kowalevski-6evy9?fontsize=14), how it works under the hood and then look at some lessons learned, with suggestions on how to build your own state management library in 2019.

## About

I'm a polyglot developer and data scientist. I've built lots of apps, for example this [iPhone app for Isometric graphics](https://isometrically.amimetic.co.uk). My website/blog is [www.amimetic.co.uk](https://www.amimetic.co.uk). I work with React/React Native at JPMorgan. My Twitter handle is @complexview

**Comment by jamesporter** [comment]
PS I think this would work best with c. 10-15 minute duration.

**Comment by hewIngram** [comment]
This sounds awesome @jamesporter! It'd be great to maybe include a brief history of state management + why it's useful, why you decided to write your own ( and as part of that - what about Redux wasn't sufficient for your needs). Things you learned along the way and maybe things you'd want to change.

Do you use it anywhere (or plan to) or is it an experiment?

**Comment by jamesporter** [comment]
Thanks. Yeah I would be motivating it by giving my wish list of features/anti-features from a few years of mostly doing Redux.

It is experimental but has influenced actual stuff I used in real work. The main conclusion (spoiler!) is about learning about new things/creating stuff and how by standing on shoulders of (open source) giants you can go a long way with just a little code.

**Comment by hewIngram** [comment]
Sounds awesome! I still haven't played with hooks in react although @Ankcorn keeps telling me how wonderful they are.

Are you free July 24th?

**Comment by jamesporter** [comment]
@hewIngram Yes

**Comment by hewIngram** [comment]
Awesome. @admataz - shall we book in @jamesporter for the 24th?

**Comment by admataz** [comment]
Yes - thanks @hewIngram  for picking this up - and thanks @jamesporter for another great talk proposal! yes  - you're on for July 24th!

**Comment by jamesporter** [comment]
Thanks Adam

**Comment by neshka** [comment]
Hi @jamesporter,

how are you? :)
Could you please confirm if you are ready for Wednesday?

Details of the venue:

CONDÉ NAST
ADELPHI BUILDING
1-11 JOHN ADAM ST
WC2N 6HT

People start arriving around 6:30 and we plan to start with talks after 7pm.

If you have any issues - please call me: 07752387427 or @admataz 07757234443

See you there!
Aga

**Comment by jamesporter** [comment]
Thanks @neshka , yeah I'm good for Wednesday. Will try to get there for 6.30pm but my offices are quite far away (still should be there before 6.45pm).

PS I noticed I've RSVP-ed yes on Meetup, will change that to a No to let someone else in!

**Comment by admataz** [comment]
hey @jamesporter  - great! see you there. I've added you back on the list - it's a little easier for admin - don't worry about the extra attendee - we'll try make sure that everyone who signs up can make it.

**Comment by jamesporter** [comment]
thanks

**Comment by neshka** [comment]
Hi @jamesporter, thanks for the talk yesterday!
We will send you the video as soon it's ready :)

**Comment by admataz** [comment]
Video is live at in the LNUG channel https://youtu.be/8h8NI-6zva0 🎉 

Thanks again
