### ISSUE TITLE
Everything you didn't dare asking about jade

### ISSUE THREAD

**Issue by ForbesLindesay** [lnug/speakers#17]
This talk will start with a very brief overview of what the jade templating language is and why it's so powerful.  It will then deep dive into how the nitty gritty of the compiler is implemented, this will include some discussion of the many other modules that jade depends on.  I will then take the audience on a tour of a couple of my favourite spinoffs of jade.  Finally, I will end with a description of how we have built a community around the jade project that is capable of achieving far more than I could on my own.

Any thoughts on this are welcome.  I think it would be a relatively long talk, maybe 1 hour.

**Comment by orliesaurus** [comment]
25th Feb, bookmark it plz :)

**Comment by iancrowther** [comment]
@ForbesLindesay workshops involve a LOT of prep mate..

**Comment by ForbesLindesay** [comment]
@orliesaurus what do you think I should talk on?  The internals of jade could make for a fairly interesting area, but do you think people would prefer to get more of an intro to using jade.  Also, how long can I/would you like me to talk for?

@iancrowther Yes, I'm sure they would.  I'm certainly not suggesting I think it would be easy, just that it's something I'm keen to try (especially if someone would be willing to help me run/organise it).

**Comment by orliesaurus** [comment]
@ForbesLindesay Everyone heard of Jade, if they didn't they live under a rock, the internals of how jade works could be interesting, you can share the deck with me on gitter if you wish I'll take a super quick look without spoiling anything. 
We can run a workshop later in a couple of months possibly, but do you have an outline of what you'd practically do? And how long would you think it would take to run? What would people need to bring? etc.

**Comment by simonmcmanus** [comment]
@ForbesLindesay Probably a completely different talk but I'd like to hear a talk about the jade-react stuff you have been working on.

**Comment by iancrowther** [comment]
I'd be willing to help you out, just cant commit right now
