### ISSUE TITLE
Indie Hacking with Postgraphile

### ISSUE THREAD

**Issue by Ankcorn** [lnug/speakers#170]
Sometimes I get jealous of the speed people can build complex apps with things like laravel/rails. Node is a great run time but it is arguably a more complex choice for your tech stack, there is no standout MVC framework that does it all for you, instead, there are lots of small specialised tools. I want to talk about one of those. It’s called [Postgraphile](https://www.graphile.org/). It lets you generate a GraphQL API from a schema in a Postgres database. By writing just a little SQL you can create an application that would take a long time to create normally!

I'm going to show you how you can use it to build a meetup.com clone complete with JWT based authentication, real-time meetup ratings, and role-based access control. 

I'm a senior software engineer at Near.st. We are building a real-time local inventory data platform to help small businesses fight back against the growth of online shopping. Outside of work, I'm chasing my life long dream of having a dog, and building silly things with javascript. [Follow me on twitter](https://twitter.com/thomasankcorn)

**Comment by admataz** [comment]
thanks @Ankcorn! sounds great. Let's talk tomorrow at the meetup about a suitable date

**Comment by neshka** [comment]
Hey guys, are we scheduling this one for next meetup in July? :) @admataz @Ankcorn

**Comment by Ankcorn** [comment]
Hey @neshka, August suited me best! 

I can make July but am doing a workshop at another event the same week. I want to make sure I have time to prepare for this well! :)

**Comment by neshka** [comment]
Maybe August then 👍

**Comment by Ankcorn** [comment]
Perfect! Thank you 🎉

**Comment by admataz** [comment]
@Ankcorn : awesome! You are on for August!

**Comment by Ankcorn** [comment]
Ace! Thanks @admataz

**Comment by neshka** [comment]
Hi @Ankcorn! :)
how are things looking for your talk next week? Ready? 😄 
Let me know please.
Aga

**Comment by Ankcorn** [comment]
Thanks, @neshka. I have a few more things to finish off but I'll be ready 😄

**Comment by neshka** [comment]
Hi @Ankcorn! Hope you are well :) Thanks for another interesting talk. Great job!

**Comment by Ankcorn** [comment]
Thank you ☺️ that was so much fun!

If you need the video let me know

**Comment by admataz** [comment]
Hey @Ankcorn ! 
The video is now on our YouTube Channel!
https://youtu.be/dpc16H1D90E

Thanks again so much for your talk.
