### ISSUE TITLE
Security in Node.js

### ISSUE THREAD

**Issue by ForbesLindesay** [lnug/speakers#171]
While working on large node.js projects, I’ve noticed that there is no clear answer to common questions like “how do I securely store passwords”. I’ve also noticed that all the popular frameworks lack key security features such as CSRF protection and Rate Limiting by default. It’s really easy to get security wrong, and it’s not your fault that this is so difficult.

In this talk, I’ll present some practical steps you can take to secure your applications, including protecting against some of the most common attack vectors. I’ll also attempt to inspire you to think differently about what the defaults should be when you build new applications and libraries. We can make our code default to security; it doesn’t have to be this way.

I'm a tech lead at Threads Styling and maintain several large open source projects, such as Pug, [@authentication](https://www.atauthentication.com/) and [@databases](https://www.atdatabases.org/). My twitter handle is @ForbesLindesay

**Comment by jkbits1** [comment]
@admataz and everyone else, the version of this talk at FullStack 19 was both very informative and accessible, so useful for all levels. I'll let you all carry on the conversation, just wanted to add that

**Comment by Ankcorn** [comment]
@ForbesLindesay This is something I'd love to know more about. There is 1 speaker slot on august the 28th? After that it would be September the 25th. What would be best for you?

**Comment by admataz** [comment]
great to have you back at lnug @ForbesLindesay!

**Comment by ForbesLindesay** [comment]
August 28th would be great :)

**Comment by Ankcorn** [comment]
@ForbesLindesay Awesome! Let's get this scheduled.

**Comment by ForbesLindesay** [comment]
@Ankcorn I just noticed this isn't on the schedule at https://lnug.org/future.html

**Comment by admataz** [comment]
thanks. oops. haven’t updated the website this month. will sort it out as soon as i get home.

**Comment by neshka** [comment]
Hi @ForbesLindesay 

Just confirming - how are things looking for your talk on Wednesday? All good?

details of the venue: 
```
CONDÉ NAST
ADELPHI BUILDING
1-11 JOHN ADAM ST
WC2N 6HT
```

I will be there from about 6:15pm - people start arriving around 6:30 and we plan to start with talks after a brief intro and welcome at 7pm

If you have any issues - please call @admataz: 07757234443 or me: 07752387427

See you there!
Aga

**Comment by neshka** [comment]
Hi @ForbesLindesay! :) Are you ready for tomorrow? Please let us know. Thank you in advance :)

**Comment by ForbesLindesay** [comment]
Hi @neshka, I only just saw these updates. I should be there in about 30 minutes time :)

**Comment by ForbesLindesay** [comment]
[Screen Recording](https://www.dropbox.com/s/gitmr0wjke9lxyv/Security%20in%20Node%20LNUG%20Recording.mov?dl=0), [Slides](https://www.slideshare.net/ForbesLindesay/security-in-nodejs) and the JavaScript Open Source Meetup I mentioned: https://thrds.biz/meetup

**Comment by neshka** [comment]
Hi @ForbesLindesay, thank you so much for the talk yesterday.
I hope you had a good time.

We will send you the video as soon it's ready.

**Comment by admataz** [comment]
Hi @ForbesLindesay  - the video is now in the LNUG YouTube Channel.
https://youtu.be/Qrb-gwlBUzo 

Nice to see you - and thanks again for your talk and contribution. Please let us know if you have any thoughts or feedback

**Comment by ForbesLindesay** [comment]
Thanks @admataz I really enjoyed speaking, it was an excellent venue & all round well run.
