### ISSUE TITLE
Managing multiple npm modules in a single repo

### ISSUE THREAD

**Issue by knolleary** [lnug/speakers#172]
### Abstract

Ever since the start of [Node-RED](https://nodered.org), the runtime and editor components have been packaged together as a single blob of npm module.

With the 0.20 release we split the internals apart into 6 separate new npm modules, along with the original node-red module to glue it all back together - and we did it without end users ever knowing (apart from us talking about it at every chance we got).

This talk reveals how we went about this refactoring and the challenges of managing multiple modules in a single repo. I'll talk about why we ultimately decided not to use one of the various mono-repo tools, such as Lerna, and ultimately decided to roll our own approach.

### About me

I'm an Open Source developer at IBM and the creator of Node-RED.
I can be found online as @knolleary in lots of the usual places.

I presented about Node-RED at LNUG in its very early days of September 2013, not long after we'd first open sourced it.

**Comment by Ankcorn** [comment]
Hey @knolleary, 

Welcome back (I'm sad that first talk was before my time!)

That sounds like a topic that will be very useful to a lot of lnug members!

When would you like to speak, we have 1 speaker slot in august but I have just offered it to https://github.com/lnug/speakers/issues/171 so I think they get first dibs. There are also 2 slots in September!

**Comment by knolleary** [comment]
Hey @ankcorn - September would be good for me.

**Comment by Ankcorn** [comment]
@knolleary that's awesome, Coming back exactly 6 years later!

@lnug/organisers just checking this date is okay?

Lets get this scheduled

**Comment by seanmtracey** [comment]
I can't see an issue for the September event in https://github.com/lnug/event-planning/issues, so I'd say we're probably fine too go with September 🎉

**Comment by admataz** [comment]
most excellent - it's great to have you back @knolleary - and I'm so pleased to have some iot back on the agenda too...

**Comment by neshka** [comment]
Hello @knolleary!

how are things looking for your talk on Wednesday? All good?

details of the venue:

CONDÉ NAST
ADELPHI BUILDING
1-11 JOHN ADAM ST
WC2N 6HT

I will be there from about 6:15pm - people start arriving around 6:30 and we plan to start with talks after a brief intro and welcome at 7pm

If you have any issues - please call @admataz: 07757234443 or me: 07752387427

See you there!
Aga

**Comment by knolleary** [comment]
@neshka hey - all good. Looking forward to it! See you there.

**Comment by neshka** [comment]
Hi @knolleary, thank you so much for the talk yesterday!
We will send you the video as soon it's ready.

**Comment by admataz** [comment]
Hi @knolleary  - the video for your talk is now live on our YouTube channel - thanks again for the great insights into your work - and I saw the blog post  - congrats on the release  of v1.0 !! 🎉 

Hopefully see you again soon at LNUG - come and enjoy a few beers - and if you have any feedback on the meetup or organisation - please feel free to let us know

https://youtu.be/_r4emDWlApA
