### ISSUE TITLE
Concurrent editing with JSON Patch and Operational Transformation

### ISSUE THREAD

**Issue by jasoniangreen** [lnug/speakers#173]
You often want to build an app as quickly as possible. To get some kind of MVP in the hands of users, giving them value and something for you to incrementally improve. Most features can come later, but if you ever intend to offer a shared editing experience of any kind, you really need to think about it up front.

At Threads Styling we were faced with such a prospect when planning their Social Story builder. Having worked with CMSs in the past, we knew the pain of managing document locks with all their edge cases. We also knew that eventually the use case will arise to concurrently edit the document, and if you haven’t planned for it, it is a monumental task.

By treating the document as a stream of JSON patch changes from the very beginning, we were able to offer real-time collaborative editing with conflict resolution smoothly handled by an Operational Transformation algorithm. In this talk, Jason will discuss the concepts involved and demonstrate a simple, but working example of a shared document using our open source library.

By Jason Green, Principal Developer at Threads Styling - Twitter: @aziraphael

I confirm my talk is 20 mins long in total.

I confirm that I will abide by the Code of Conduct

**Comment by Ankcorn** [comment]
Hey @jasoniangreen sounds like a great talk. It would be awesome to have you at LNUG. We have 1 speaker slot left for the 25th of September. After that it would be the 23rd of October. Let me know what you can do! 👍

**Comment by jasoniangreen** [comment]
Yep, sounds good @Ankcorn. 25th of September it is!

**Comment by Ankcorn** [comment]
Lets get this scheduled! 👍 

I'm really looking forward to this.

**Comment by neshka** [comment]
Hi @jasoniangreen 

Just confirming - how are things looking for your talk on Wednesday? All good?

details of the venue:

CONDÉ NAST
ADELPHI BUILDING
1-11 JOHN ADAM ST
WC2N 6HT

I will be there from about 6:15pm - people start arriving around 6:30 and we plan to start with talks after a brief intro and welcome at 7pm

If you have any issues - please call @admataz: 07757234443 or me: 07752387427

See you there!
Aga

**Comment by jasoniangreen** [comment]
Thanks for the info, and yes, I'm all good.

**Comment by overlookmotel** [comment]
@jasoniangreen Hi JSON. Really interesting talk last night.

I'm keen to play with it, but didn't note down the URL. Could you please post a link?

Google takes me [here](https://www.npmjs.com/package/json-patch-ot), but I think this is not your package - I vaguely remember the npm package had `@threads` in the name.

**Comment by jasoniangreen** [comment]
**Here are the slides:** https://www.slideshare.net/JasonGreen146/concurrent-editing-with-operational-transformations-and-json-patch

**And everything else:**
https://www.npmjs.com/package/@threads/json-patch-ot
https://github.com/ThreadsStyling/json-patch-ot
https://github.com/ThreadsStyling/json-patch-ot-example

`npm install @threads/json-patch-ot`

**Comment by overlookmotel** [comment]
@jasoniangreen Thanks!

**Comment by neshka** [comment]
Hi @jasoniangreen!

Thank you so much for the talk yesterday.
I hope you had a good time.

We will send you the video as soon it's ready.

**Comment by admataz** [comment]
Hey @jasoniangreen 

The video for your talk is now online on our YouTube channel: https://youtu.be/sLwjXjjZ9Hs

Thanks again for a great talk and sharing your work - really valuable insights. 

Hopefully see you again soon at another LNUG - join us any time. If you have any feedback on the organisation or the meetup night - please feel free to let us know!
