### ISSUE TITLE
EsWhat now?

### ISSUE THREAD

**Issue by hewIngram** [lnug/speakers#174]
# Abstract 

So ES6 is cool - we all know that, I've even seen job ads that are for ES6 developers (which is... interesting). But ES10 was released this year with basically zero excitement from anyone. What was in it? And why did nobody care? More importantly though... how can I try out cool new features that are destined for ES11, ES12 or beyond? How do I get my awesome idea into the Javascript spec? And why is it called ES10 and not JS10? While we're at it... what on earth is ECMAScript anyway?!

This talk will go over the process that Javascript features go through, it'll help to explain some of the weird history of Javascript and everyone will leave safe in the knowledge that when they have a great idea for the JS spec, they'll know exactly how to get it in.

# About me

I'm a software engineer at Applied - a startup striving to make hiring fairer, smarter and easier. I'm a lover of all things Javascript and spend far too much time building weird (read: pointless) things on the web.

**Comment by admataz** [comment]
I think this will make a good talk - it's an  evergreen topic so maybe a good one to pull out when we need to fill some gaps?
