### ISSUE TITLE
⚡️⚡️ Lightning talks

### ISSUE THREAD

**Issue by hewIngram** [lnug/speakers#175]
So... we haven't done lightning talks in a while. 

Calling all idealists and entrepreneurs, self-starters and enterprise team members... open source maintainers, experimenters, and those just having fun... we want to hear about what you are doing with node.js. 

If it's worth your time developing, it's worth sharing.

**Comment by admataz** [comment]
yes! let's do this - was great fun and quality last time

**Comment by hewIngram** [comment]
Sweeeeet - how do you want to get people lined up? Shall we tweet out and point people to here?(or another issue for talk ideas)

**Comment by admataz** [comment]
yes! - let's rewrite your opening comment here  with an intro/promo and also use that for the website etc - we can invite and gather interested lightning talks in the comments  below - and update the main comment with the confirmed line up.

**Comment by hewIngram** [comment]
@admataz thanks for dealing with this! I've spent most of the last week holed up in bed trying to fight off some ills.

Do you reckon you could rustle up someone from NearForm to speak?
Also @BethGriggs - would you be up for speaking? You're not London based right? We can probably dial you in for it (after seeing Evan You dial in for his Keynote at Vue London... we can totally give this a try). (cc @seanmtracey because I don't know how github notifications work and maybe he can bug you about this).

**Comment by seanmtracey** [comment]
I'll drop Beth a message and make sure she gets the message :)

**Comment by BethGriggs** [comment]
I'm up for speaking! I'll most likely be able to attend in person 😃

**Comment by admataz** [comment]
@hewIngram - all good - yes - I'll ask around for potential talks

regarding live link ups - I try to avoid them if possible - we've had some pretty dire talks in the past strangers on a screen...  generally there's a disconnect for attendees - although for a lightning talk and an established member of our community I think it's fine.... 

@BethGriggs Great if you can make it!! - but let us know if you have any problems making it into London for the night

**Comment by admataz** [comment]
thanks all! videos available at https://www.youtube.com/playlist?list=PLam_80-FY3vRXJr6R104agQ8OYNoo4xNG
