### ISSUE TITLE
Open call for your lightning talk ⚡️ ⚡️ 

### ISSUE THREAD

**Issue by admataz** [lnug/speakers#176]
Tonight will be open mic for short-burst, quick-fire presentations. Maximum 8 minutes to talk about whatever is getting you thinking and acting with node and javascript. 

So far we have: 
- Beth Griggs (@BethGriggs) : "What's new to LTS with Node.js 12"
- Enrique Lacal (@EnriqueL8) : "Simplify deploying cloud-native apps to Kubernetes"
- Lucas Fernandes da Costa (@lucasfcosta): "How I’m Still not Using GUIs in 2019"
- Hew Ingram (@hewIngram ): "A talk not at all about node..." 
- Diogo (@diogofcunha): "Async generators in real life"

Add your lighting talk to the lineup in the comments on [here](https://github.com/lnug/speakers/issues/176) and get on the list!

**Comment by EnriqueL8** [comment]
Title: Appsody - Simplify deploying cloud-native apps to Kubernetes
Abstract: Appsody provides a set of open source tools and capabilities that simplifies the process of building and deploying applications to Kubernetes that are not just cloud packaged, but that are also cloud native. The talk will consist in a brief presentation of Appsody, and a demo of deploying locally a NodeJs Express application using Appsody. Estimated time around 8 minutes.

**Comment by Ankcorn** [comment]
@EnriqueL8 that sounds very cool!

**Comment by hewIngram** [comment]
Title: A talk not at all about node...
Abstract: You'll see..... (probably like 10 mins)

**Comment by hewIngram** [comment]
@BethGriggs + @lucasfcosta - if either of you can make it and have an idea of what you want to speak about can you pop a rough title here as a placeholder? 🎉 thanks!!

**Comment by lucasfcosta** [comment]
Hey @hewIngram, I’d love to do a quick one about how I use vim + tmux + zsh for JS development if that’s possible. What do you think?

Maybe “How I’m Still not Using GUIs in 2019” would be a good title?

Not necessarily focused on Node, but I’ve just presented this in a conf in Bulgaria (it was a 30min talk though) and got quite positive feedback.

**Comment by BethGriggs** [comment]
I haven't finalised it yet my topic yet - but as a placeholder "What's new to LTS with Node.js 12?" 5-8 minutes

**Comment by hewIngram** [comment]
That sounds wonderful @BethGriggs!!

@lucasfcosta - it sounds super interesting!!! Do you reckon you could do some brutal cutting to distill it down to 10 mins of pure GUI-less wisdom?

**Comment by lucasfcosta** [comment]
Yes, sure! That was the plan, sorry I didn't specify that. That was just to explain that I had already done it 😆

**Comment by hewIngram** [comment]
Sweeeeeeeet. Can't wait! Thanks

**Comment by admataz** [comment]
Thanks @BethGriggs @lucasfcosta @EnriqueL8 @hewIngram  - you're all on listed on the website and meetup page 🎉 

Look forward to hearing your talks. 

There's still space for one or two more if anyone's interested - add it to the comments below

**Comment by diogofcunha** [comment]
**Title:** Async generators in real life
**Abstract:** It has been a few years since javascript introduced async generators, probably everyone heard about them but what are they? What do they do? How can they help in real life? Are they just "streams on steroids"? The talk will consist in a brief explanation of async generators and iterators and a few code snippets whit real life examples where they can make code more redeable and at the same time less error prone.
**Expected time:** 10-15 minutes

**Comment by hewIngram** [comment]
☝️ That sounds very interesting @diogofcunha. do you reckon you could cut it down to 10 mins? We're getting pretty full so if we can keep it slim that'd be COOL.

Can't wait to hear it! Thanks!

**Comment by diogofcunha** [comment]
@hewIngram sure can do 👍

**Comment by hewIngram** [comment]
Swweeeeeeettt thanks @diogofcunha

**Comment by diogofcunha** [comment]
Hey @hewIngram is my spot confirmed for the 23rd? Just let me know as I need to prepare some slides 😆

**Comment by hewIngram** [comment]
It is @diogofcunha

Thanks

**Comment by admataz** [comment]
all confirmed and updated on relevant channels (website, Meetup, twitter...)

Looking forward to Wednesday!

**Comment by overlookmotel** [comment]
I have an idea for a talk which I think could do in less than 8 mins.

I'd like to briefly introduce [react-async-ssr](https://www.npmjs.com/package/react-async-ssr) - a package I've written that allows rendering [React Suspense](https://reactjs.org/docs/code-splitting.html) server-side on Node. React have been promising to add support for this themselves, but there's been no progress for a year, so I did it myself.

However... I'm not sure I have time to get even that short talk ready in time for tonight - busy day today. So, 3 questions:

1. Would you be willing to accept this talk, if I can get it prepped in time?
2. If so, could we leave it until tonight to see if I've managed to prepare in time, and only add me to the running order last minute if I have?
3. Are slides appropriate for a lightning talk? Or do most people just talk without slides, given the short length?

**Comment by admataz** [comment]
@overlookmotel  - sounds great! very interesting.  let's see where we are later with the schedule and your prep. No pressure - if you can't get itt done today, what about next month? 

I think slides are ok -  @hewIngram ?

**Comment by overlookmotel** [comment]
@admataz OK, yes. Let's do it next month. Then I can do it properly.

Actually, it'd be quite a good complement to "State Management with React Apollo".

**Comment by admataz** [comment]
@overlookmotel  - sounds good

**Comment by admataz** [comment]
hi @overlookmotel  - just getting to arranging this month's talks. Unfortunately the Apollo talk has had to cancel - are you still on?

**Comment by admataz** [comment]
bump! @overlookmotel  - fancy doing your talk next week?  - can I add you to the schedule?

**Comment by overlookmotel** [comment]
@admataz Sorry for silence. I'm thinking about it. A lot of new information about React's future direction for Suspense [came out at React Conf a few weeks ago](https://reactjs.org/docs/concurrent-mode-suspense.html) and I'm trying to assess whether my package should change in response to that.

I'm not keen to present something that is half-baked!

I'll try to make up my mind later this week.

Thanks for badgering me. I appreciate it that you're willing to have me talk. I have a yearning to do so, but the content needs to be right!

**Comment by admataz** [comment]
Hi @overlookmotel  - I appreciate what you're saying about presenting something that you don't feel is ready. I'd encourage you not to worry too much about that - and think about sharing what you've been doing in response to the context/problem, in whatever rough and (un)ready sate it may be. We've all been there - and are all interested to share the perspectives and  ongoing thought process from other developers to move us all forward. Even sharing your WIP can be a rewarding and enlightening process for your next iteration.

I think the entire ecosystem of the web is in a continuous state of halfbakedness! So you are in good company. 

Anyway, whichever way you feel - let me know when you are ready to go - and if you want to discuss your talk more beforehand, myself and others in @lnug/organisers will be willing to help you.

**Comment by overlookmotel** [comment]
@admataz @hewIngram OK you've convinced me!

Shall I write a little blurb for the LNUG website? Or do you just need a title? If the latter, here it is:

> Rendering React Suspense on the server side

(does what it says on the tin)

One other question: Can one get reliable internet at the venue?

**Comment by overlookmotel** [comment]
I will do my best to fully bake the cake before we cut it.

**Comment by admataz** [comment]
Awesome! Thanks @overlookmotel - that's great. 

Yeah - if you could provide a sentence or two - that will be great. 

Generally the guest internet at the venue is fine in my experience

**Comment by overlookmotel** [comment]
@admataz @hewIngram I am incredibly sorry to do this at short notice, but I need to pull out of doing talk tonight. I have a bit of an emergency and need to drive to Derby tonight.

Sorry to be so flaky. To flake once may be regarded as a misfortune; to flake twice looks like carelessness.

I'd be very happy to it another time (Dec or Jan?)

**Comment by admataz** [comment]
hey @overlookmotel  - no worries! Hope everything's OK? 

let's talk about something for the new year (no meetup in December)  - will be great to hear your talk.

**Comment by admataz** [comment]
@BethGriggs @EnriqueL8 @hewIngram @lucasfcosta @diogofcunha  - thanks again for your contribution - October was one of my favourite LNUG's ever! Lightning talks FTW!!

Let me know if you have any feedback - the videos from the night are at last uploaded: 

https://www.youtube.com/playlist?list=PLam_80-FY3vRXJr6R104agQ8OYNoo4xNG

**Comment by lucasfcosta** [comment]
Amazing, thank you @admataz for the invite. It's always a pleasure to be at LNUG 💖 

Looking forward to the next one.

**Comment by admataz** [comment]
Hi @overlookmotel  - just trawling through some open threads I have... How do you feel about giving a talk at next week's LNUG meetup (Feb 26th)? We have some space available - and I really think there would be some interest in your learnings from react-async-ssr. No pressure - but the invitation is there... 

Otherwise - hope you are well! Speak soon.

**Comment by overlookmotel** [comment]
@admataz Thanks for chasing me up.

I am still keen to talk, but want to finish up my implementation first. I'm well on the way to doing that ([react-lazy-data](https://www.npmjs.com/package/react-lazy-data) is the latest piece of the puzzle). I'd hope I'll have it done in about a month's time.

However, rather than me pulling out at late notice (again!) can we please talk about a date after I've finished the thing?

**Comment by admataz** [comment]
Thanks @overlookmotel  - no worries. Feel free to open a new issue on https://github.com/lnug/speakers/issues if you want to get any feedback or discussion  - and we will only schedule when you're ready.

**Comment by overlookmotel** [comment]
Thanks @admataz. See you on Wed...
