### ISSUE TITLE
⚡️Using Serverless to compile the Serverless.

### ISSUE THREAD

**Issue by seanmtracey** [lnug/speakers#178]
Compiling native dependencies for Serverless Node.js functions can be a PITA. In this lightning talk, I will explain how I put together an an OpenWhisk function which which makes compiling those dependencies as easy as making a single HTTP request.

## About me

I'm a Developer Advocate at IBM. I spend my time with AI, IoT, and Cloud Computing technologies - usually with Node.js (but sometimes with a smattering of Python), and I help run some meetup groups across the UK.

**Comment by admataz** [comment]
Hi @seanmtracey  - thanks for this - it's an interesting challenge - I'd love to hear how you're achieving it with OpenWhisk.  Question, maybe you can address in a few lines in your talk - but why have native deps in your serverless functions? 

We had a cancellation for later this month - how are you fixed for the 27th November?

**Comment by seanmtracey** [comment]
Hey Adam,

Yup, this month works for me :)

Will address why we might want native deps in a serverless function in the talk (in short, we don't live in a perfect world 😅)

**Comment by admataz** [comment]
as discussed - video didn't come through :(
