### ISSUE TITLE
...and more ☈ 

### ISSUE THREAD

**Issue by admataz** [lnug/speakers#179]
Last month we had a blast with top notch lightning talks - and this month's planned full talk had to be delayed.

Seems an obvious `1+1` that we should have more of a good thing - so this month....

- Step aside chat ops, Bat Ops is the future. ([@star_suit](https://twitter.com/https://twitter.com/star_suit))
- 100 player pong (or something like that) ([@admataz](https://twitter.com/admataz))
- Rendering React Suspense on the server side ([@overlookmotel](https://github.com/overlookmotel))
- Using Serverless to compile the Serverless ([@seanmtracey](https://twitter.com/seanmtracey))
 
If you want to join the list send in your ⚡️ idea as a comment [here](https://github.com/lnug/speakers/issues/179).  Same rules apply: Max 8 minutes. Whatever's getting you thinking about node and javascript. Go!

**Comment by admataz** [comment]
I think I'll kick off the thunderstorm with...

## 100 player pong  (or something like that)
Every month at LNUG we give a big shout out and thanks to [@pusher](https://pusher.com) who provide the resources to record our meetup talks. But what is it that Pusher do for a day job? Here I will explore [Pusher's Channels API](https://pusher.com/channels) - and invite you to participate in a live real-time experiment.

**Comment by hewIngram** [comment]
This sounds like magic @admataz 

I *think* @Ankcorn and one of the other NearSt developers were up for doing a talk?

**Comment by Ankcorn** [comment]
@starsuit had a very awesome idea that we built into a real thing one afternoon at NearST. The talk will be about 5-8 minutes, and hopefully encourage people to do silly things with node and IOT 🎉

Step aside chat ops, Bat Ops is the future.

Slack fatigue is real. That’s why we realised early on that the need to diversify the way feedback is delivered is crucial to any hip startup's success. In our serverless backend we capture events and make our bat buddies light up in a glorious array of colours! It's totally the future. In this short lightning talk we show you how we made this happen and how you can too!

Talk includes some node, PI, and lots of bats! 

Thoughts???

**Comment by admataz** [comment]
Thanks @Ankcorn  - yes! about time we had another IOT lightning talk.

**Comment by hewIngram** [comment]
@Ankcorn @starsuit - like these bats:    🦇🦇🦇🦇🦇

**Comment by seanmtracey** [comment]
Those bats? Oh, I was getting excited 😜 https://youtu.be/AnXh3XR9zyM

**Comment by admataz** [comment]
All done - video is here: https://www.youtube.com/playlist?list=PLam_80-FY3vRrbZMQYgxNuG4zdr7R8nhz
