### ISSUE TITLE
LNUG 2020 retro buzz

### ISSUE THREAD

**Issue by admataz** [lnug/speakers#181]
Last year - while the rest of the world was losing its mind,  LNUG continued to grow its solid community of friends among professionals. We  saw major milestones for node.js  and we also hosted some great  talks  and events.

It’s 2020! 

This year we want  to strengthen and grow - and support the communities and individuals  to continue to learn and create amazing work with node.js.  We want to  welcome visitors, out of town developers and guest speakers to add to our mix of local talent. 

It’s 2020! 

So we’re kicking off the decade with a fresh look back - and a new look forward.  What’s upcoming for node.js in 2020? And what are we going to do about it? 

This is your chance to get involved - have a laugh and a look back with us, and have your say with what happens  next.

**Comment by admataz** [comment]
@hewIngram - just putting this up here - dunno if this matches the mood you have in mind for the interactive retro talk idea? 

cc @Ankcorn @seanmtracey

**Comment by Ankcorn** [comment]
> “…the only thing bigger than us last year was Brexit…”

So much hype!

**Comment by admataz** [comment]
Lol @Ankcorn indeed. It’s a bit much - caught up in hype of the stormzy diss battle while writing this

**Comment by hewIngram** [comment]
Yep sounds good - will add some details here later with a rough plan and get some postits and stuff for it.

**Comment by hewIngram** [comment]
Ok so... my plan is:
A quick recap of some cool stats from the last year (number of talks, number of video views, number of attendees and stuff - any other ideas shout).
A recap of what LNUG is and a bit about how we as organizers do stuff but the attendees are important and we want to hear fro them.

A "Loved, Learned, Lacked, Longed for" exercise. 4 of us stationed around the room with a wall and a stack of postit notes and sharpies and ask people to wander about and add postits into the various sections

(I can' tell if it will work really well or be a complete mess...)

**Comment by hewIngram** [comment]
Any thoughts and comments would be awesome

**Comment by Ankcorn** [comment]
Even if its a mess, it will be a beautiful mess 👍

**Comment by admataz** [comment]
Sounds good to me - looking at the RSVPs we seem to have a good mix of familiar and new faces - so hopefully this leads to some fun feedback. 

> ask people to wander about and add postits into the various sections. 

You ask for ideas... 
- Maybe we can kick off with this feedback idea - and let people add postits to walls and discuss over the break - and let the post break session with your presentation be review/discussion of ideas? Concerned about coordinating movement - esp. as we don't know the space very well. 

-  if there's anything meaningful stats wise for growth in node usage (npm or other?) just to give our activities some broader/ global context. 

will think some more tomorrow

**Comment by hewIngram** [comment]
Oh I read this and the other thread in the wrong order. I guess my concern is allocating specific time to the exercise will likely make people engage in it more. Also - large group discussions don't work very well. We could do a[ 1, 2, 4, all](http://www.liberatingstructures.com/1-1-2-4-all/) type thing

**Comment by admataz** [comment]
yeah - sorry - spreading my feedback across threads :( 

I agree about a large group discussion - and specific time for discussion. I guess I was just thinking of allowing more free discussion/buzz after introducing some of the feedback ideas. 

I'd say breaking up into groups will be useful if we provide a specific topic for discussion for each - 'venues for 2020', 'shaping online forums', 'talk topics' ?  or is that what you had in mind

I don't want to crowd your thinking about this  - so if you have a clear idea of how you see this shaping up  - I trust that!

**Comment by hewIngram** [comment]
No worries. `so if you have a clear idea of how you see this shaping up` sadly... not.

Currently this feels ok. I'll rustle up some slides for it but it will be a little hastily put together. Given that heres a bunch of stuff we need to think about later re: venue maybe we leave you free to do that and maybe @Ankcorn - could I steal you to give me a hand with this?

```
Before break:
Brief thing about wanting feedback (+why) and explain the exercise.

In the break get people to be by each area and get them to encourage people to add posits (we should add a handful first)

Slightly longer break to enable this? Maybe a reminder 10 mins before the end 

After the break:
The stats - a look at 2019 in LNUG 
Quick summary about what LNUG is and how it happens every month (talk through the GitHub setup and organisers and have a little call for organisers).
Summary of a couple of peoples ‘3 words’.

Get whoever was staffing each section to summarise the postits in their section?
Ask people to chat with 2-4 people around them to try to come up with ideas about what LNUG could do - have two ‘walls’ for these to postit-ed up on 5 mins + posits time?

Some kind of conclusion….
```

**Comment by Ankcorn** [comment]
Happy to help facilitate. I think the plan sounds excellent 👏 looking forward to it.

Is anybody planning on getting their a bit earlier today? I was thinking I would arrive about 6

**Comment by hewIngram** [comment]
Yeah I can be there early. It'd be nice to chat through this with you @Ankcorn if you're about.

**Comment by Ankcorn** [comment]
I need to meet with Aris first as he wants to give us some cityjs tshirts and 1 free ticket to give away.

**Comment by hewIngram** [comment]
Kewwwwl I'll be about - I think I just want to sense check it.
