### ISSUE TITLE
⚡️Bangle.js/ Nodewatch demo ⌚︎

### ISSUE THREAD

**Issue by admataz** [lnug/speakers#182]
> The world’s first hackable open source JavaScript-powered and TensorFlow-powered smartwatch

[Nodewatch/ Bangle.js](https://nodewatch.dev)  was [introduced as the conference badge](https://www.nearform.com/blog/bangle-js-hackable-oss-js-and-tensorflow-smartwatch/) at Nodeconf EU in November. A [Kickstarter](https://www.kickstarter.com/projects/gfw/banglejs-the-hackable-smart-watch) that followed was swiftly funded. 

I received my watch from NearForm in the post the other day - and I don't know what to do with it yet - but this is too good not to share for a quick lightning demo. 

Adam aka [admataz](https://admataz.com) is a core LNUG organiser, a hacker, and a software developer at [NearForm](https://nearform.com)

**Comment by admataz** [comment]
@lnug/organisers  - I'm going ahead and scheduling my own lightning talk without a seconder so I can get it onto the site and get the newsletter out today. Sorry to break protocol. :)

**Comment by hewIngram** [comment]
@lnug/organisers - He's gone mad with power!!!!!

(sounds super interesting and like a nice light talk to compliment the other one)

**Comment by admataz** [comment]
video at https://www.youtube.com/watch?v=1TlAKTw167s&list=PLam_80-FY3vSPW9apMaczTN_4dtke9GYM
