### ISSUE TITLE
⚡️Lightning talk - a practical guide for building an Alexa Skill. Coronavirus News.

### ISSUE THREAD

**Issue by iketari** [lnug/speakers#183]
There is a lot of noise about the Coronavirus for a few latest weeks.
I've created a simple Alexa Skill which provides users with the latest update about the figures. Here it is https://www.amazon.co.uk/Artsiom-Mezin-Coronavirus-News/dp/B084M81B6Q

However, it feels like there are tons of stuff that could be improved. 
I'd like to talk about the following things:

1. How to design and implement an Alexa app for less than one weekend?
2. What to expect from validation and rolling out processes?
3. Where to get and how to store the data?
4. How to automate the routine?
5. How this sort of app can help people?
6. What else could be done? 
7. **I am eager to collaborate!** 

Given the fact that I'm doing this in a little rush, it feels more like **a lightning talk**.

> About me: I am a Senior Frontend Engineer at Behavox. I have almost 10 years of experience in JavaScript development behind my back.
> 
> You can find more about me on [LinkedIn](https://www.linkedin.com/in/artsiommezin/).

- [x] I confirm my talk is 20 mins long in total.
- [x] I confirm that I will abide by the Code of Conduct

**Comment by hewIngram** [comment]
Speedy! Thanks @iketari 
Sounds like an awesome talk

**Comment by iketari** [comment]
The first attempt at making slides.
https://slides.com/iketari/practical-guide-for-building-alexa-skills-coronavirus-news

**Comment by iketari** [comment]
Hi @admataz @hewIngram,
I've found a new meeting on my schedule for today. =( But I'm still sure I can deliver a talk! Is that ok if I arrive at the venue at 18:30 - 18:40?

**Comment by admataz** [comment]
hi @iketari  - that's fine - see you later!

**Comment by admataz** [comment]
Hey @iketari I hope you are well?  

thanks again for stepping up and providing the lightning talk in February (seems lifetime ago)

I did upload it to YouTube a while ago, but I've been a bit slow in updating things otherwise  - it's on our channel at https://www.youtube.com/watch?v=yHBJV4QGSrM 

Take care and see you sometime hopefully!
