### ISSUE TITLE
Under-the-hood of web bundlers

### ISSUE THREAD

**Issue by craigtaub** [lnug/speakers#184]
A look at the mechanisms inside web bundlers e.g Webpack.

Starting with why they are still useful.

Then how to build a small compiler, akin to Webpack. There are many interesting topics in a very small space here.

Next how to use the output of our compiler with an application.

Finishing with all the additional parts Webpack does which ours doesn't, hopefully with some idea on how those could be done.

## About me
I'm a senior developer at Nested with over 10 years experience. We do dev team talks every week and I have taken a couple, usually on the "under-the-hood of" theme. I was previously at the BBC.

My medium page is [https://medium.com/@tabu_craig](https://medium.com/@tabu_craig), I enjoy blogging.

**Comment by hewIngram** [comment]
Ah this sounds awesome @craigtaub - I think, increasingly, webpack is a bit of a scary black box to most developers (especially as tools like create-react-app abstract it away and hide it).

We might well save questions to the breaks or the pub afterwards if that's ok (in a drive to try and get it down to 20 mins-ish)?

Sounds like an awesome talk! We've got space on the 25th of March if that works for you?

**Comment by craigtaub** [comment]
Hey @hewIngram glad you like the sound of it. 
I think 20 mins-ish will be fine, happy to save the questions for after if necessary.
Thats great Im free on 25th March. Do you have a location for it yet?
If you need anything else from me please let me know.
Thanks, Craig

**Comment by Ankcorn** [comment]
This talk looks really exciting! 🤘🎉

**Comment by hewIngram** [comment]
Awesome - I don't *think* we do have a venue yet, chatting with a few companies to get something lined up - I'll let you know when we do though!
I'm going to book this in for March - thanks!

**Comment by admataz** [comment]
@craigtaub  - sounds great! Thanks for the proposal - sounds like a great talk. Pleased to have you along!

@hewIngram - yes I am talking to a couple possibilities about venue - should have something confirmed in the next day or two.

**Comment by hewIngram** [comment]
Hey @craigtaub 

Venue looks like it's going to be Tussle (near the Barbican) although still be tbc (I think... @admataz ??).

I just stumbled across your blog post about the "Feature Lead" process at Nested - that is very very cool.

Thanks!

**Comment by admataz** [comment]
hi - sorry, been off the ball. Yes, I confirmed with Trussle last week - will create the relevant pages on meetup and the website tonight. 

Address is  `1-3 Dufferin St, London EC1Y 8NA`

**Comment by craigtaub** [comment]
Thanks for confirming venue both.

@hewIngram really glad you enjoyed it, perhaps we can chat about it at the Meetup :). Looking forward to it.

**Comment by admataz** [comment]
hi @craigtaub  - we've just had word from our venue hosts, confirming what I think we already knew was inevitable  - and they are not able to host due to the corona virus concerns - so we will not be holding a physical meetup this month. We have options for running a remote video event - the format, is still to be decided. Would you still be interested in speaking or preparing a video and taking online questions/discussion? Or would you prefer to wait till this all blows over?

**Comment by craigtaub** [comment]
Hi @admataz - thanks so much for the update, yes that was expected. If its ok with you guys I think I would prefer to wait until this all blows over and do a physical meetup. I look forward to meeting all of you eventually.
Thanks, Craig

**Comment by admataz** [comment]
thank you @craigtaub  - I completely understand. Stay safe - will be in touch when the coast is clear!

**Comment by admataz** [comment]
Hey @craigtaub  - seems it's going to be a while before we can meet in physical spaces around open boxes of pizza. Would you be interested in doing an online version of your talk? It can be live or pre-recorded...

**Comment by craigtaub** [comment]
hey @admataz , yes I actually made this an online talk already, the video is here https://www.youtube.com/watch?v=JAY10_75vFw. 
Id be very happy for it to be shown at the next virtual meetup, if you think its gd enough.

**Comment by admataz** [comment]
awesome! I'll take a look - we are working out the details for the next meetup (which is next week) and may have a full schedule already - but if not then, definitely the next one (I don't see the situation changing by late June)  

As it's pre-recorded - would you be able to join a panel or be online to take questions/comments from attendees?

**Comment by craigtaub** [comment]
> we are working out the details for the next meetup (which is next week) and may have a full schedule already - but if not then, definitely the next one

Awesome sounds gd. Let me know.

> would you be able to join a panel or be online to take questions/comments from attendees?

Yes sounds good.

**Comment by admataz** [comment]
Hi @craigtaub  - how would you feel about doing your talk in a live stream? The meetup last week went very well for speakers - and the Remo.co platform was really good. Thoughts?  WE are meeting again on June 24th

**Comment by craigtaub** [comment]
Hey @admataz, glad to hear it went well last week. Videos look great.
Im happy to do the talk again live. I would want to use the same script and same content that I was planning to use before if thats ok i.e. presentation rather than a live code demo.

**Comment by admataz** [comment]
Hey @craigtaub  - all sounding good. I've scheduled you in for next week - just checking - the length of your talk is similar to that in the YouTube video? We need to keep it around 25 minutes.

**Comment by admataz** [comment]
@craigtaub : Details of the meetup are on the website and meetup page: https://lnug.org. I'll be in touch later this week about a possible test run with the video hosts.

**Comment by craigtaub** [comment]
@admataz 

> the length of your talk is similar to that in the YouTube video

Yep should be the same time.

> I'll be in touch later this week about a possible test run with the video hosts

Sounds good to me. 

Thanks for organising

**Comment by admataz** [comment]
hi @craigtaub we are going to go through the details of the Remo platform with @phazonoverload on Tuesday at 2pm - is this time ok for you?

**Comment by craigtaub** [comment]
@admataz yes 2pm on Tuesday works for me. My email is "craigtaub@gmail.com". Let me know what kind of call you guys are planning. Thanks

**Comment by phazonoverload** [comment]
On the platform itself so I can show you how it works 😄 https://live.remo.co/e/lnug-meetup-june-rehearsal

**Comment by craigtaub** [comment]
Thanks @phazonoverload . See you there then.

**Comment by craigtaub** [comment]
Thanks so much for the chance to speak guys. I'll definitely be back next month, perhaps in a couple of months will come back as a speaker with a similar talk.

Take care guys and see you soon.
