### ISSUE TITLE
Migrating a simple study app to AWS

### ISSUE THREAD

**Issue by amdwit** [lnug/speakers#185]
I use a simple React PWA to keep my knowledge up to date. It first was running on a linux server using PostgreSQL and some NodeJS code. I will explain in twenty minutes how I migrated to AWS and I will show what NodeJS code I still use.

I am a Javascript developer for over twenty years and I am currently looking for a full stack contract. I live in London since 2015 and I like visiting the Javascript community and their meetups.

**Comment by hewIngram** [comment]
Hey @amdwit - thanks for this!

Would love to hear a bit more around what you plan to talk about: were you running on a dedicated, non-cloud server?
What AWS service did you move it onto? (I'm assuming the React bit is served via S3/Cloudfront? Is the backend an express app?)
How does Node come into it?

Can't wait to hear more!
Thanks!

**Comment by amdwit** [comment]
Hi! Indeed, it was running on a dedicated linux server running Node Express PostgreSQL. Building using Webpack. Webscraping new data using XML library.
Now I am indeed using S3, Cloudfront, Lambda, API Gateway, Cognito, DynamoDB. Node is still being used in the Lambda API. Node is also in the deploy to AWS scripts of the database and react. I also use it for maintenance and webscraping.

**Comment by amdwit** [comment]
So the node code being used is not rocket science.

**Comment by Ankcorn** [comment]
Over the past year we have seen quite a few talks relating to aws/cloud/serverless, and in general there is a little bit of fatigue around them.  

You should think about and explain the story you want to tell. Here are some questions i think our audience would like to know that might help you flesh out this talk proposal

What is this study app and why is it important to you?
Why migrate it to the cloud? Even if its just to refresh your skills and make your cv 🌶 its something our audience will relate too 🥳
What bits about aws did not work as well as expected?

**Comment by amdwit** [comment]
Yes, sure, I will answer those questions too. But do you mean I need to write that out in this issue? I could also send/attach the presentation sheets. And I understand the fatigue. I will work now on the presentation sheets, I think. Thank you for your commenting.

**Comment by Ankcorn** [comment]
Thanks, yeah post them here in the first comment, think of it like an abstract or hook to get people excited about your talk. 😊

When your talk is scheduled the first comment on the issue gets picked up and put on the website and meetup event if it sounds interesting and your story is compelling its a great way to get people to come to the event just to see you speak!

If you have any questions ask here and I will get back to you asap ✌️
