### ISSUE TITLE
Authentication && Serverless && Node

### ISSUE THREAD

**Issue by bernardbaker** [lnug/speakers#186]
Auth0 is a leading world class authentification platform. And I'd like to present it using Node and Serverless.

Regular methods of authentication include setting up a custom authentification API, user, session and token management. Which is time consuming, not productive and plainly put, not very secure if a solution doesn't aspire to RFC specifications.

In my talk I will present to the audience; Auth0 as a solution, Netlify serverless functions, a Node API implementation of passwordless authentication, and basic API endpoint protection using JWT.

I'm Bernard, I'm working for myself. An e-commerce startup. [@bernibear2000](https://twitter.com/bernibear2000).

**Comment by Ankcorn** [comment]
Cool topic @bernardbaker, how long is the talk going to be?

Also, passwordless auth is super nice, I am seeing more things start to use it, does this talk go into some of the specifics of that?

**Comment by bernardbaker** [comment]
Hi Thomas,

15-20 mins.

And it will cover detail of the authentication flow, implementation of code
and resources.

I contributed to a different Auth0 demo in the past. By implementing an
authentication flow and providing a pull request for a bug fix.

I also plan to join the Auth0 guest author platform and I'll mention the
published materials in the talk.

**Comment by bernardbaker** [comment]
Hi Adam,

Yes, I can present my talk via video link. Send the details of the video
conference call.

I've used Google hangouts and Zoom for Mac in the past.

**Comment by Ankcorn** [comment]
Nice that sounds cool, thanks bernard!

Looking forward to your talk 👍

**Comment by admataz** [comment]
Thanks @bernardbaker  - I'll get the details for the stream to you as soon as that's worked out.  There's a conversation going on in the [planning channel](https://github.com/lnug/event-planning/issues/40) if you're interested.

**Comment by bernardbaker** [comment]
Thanks, just clicked.

Regards,

Bernard T. A. Baker

**Comment by bernardbaker** [comment]
Presentation slides are ready. Looking forward to the talk.

Regards,
Bernard

**Comment by admataz** [comment]
Hey @bernardbaker  - @phazonoverload is looking after the streaming for Wednesday - can I leave it to you both to coordinate what's required?

**Comment by bernardbaker** [comment]
Yes, you can.

@phazonoverload could we open a dialogue?


Regards,

Bernard T. A. Baker

**Comment by phazonoverload** [comment]
Ello! Can you join https://meet.google.com/kap-wyky-hjc at 6pm tomorrow please? Will test the setup. This call is for me, Adam, and speakers only :)

**Comment by bernardbaker** [comment]
Ok

**Comment by admataz** [comment]
Hey @bernardbaker  - thanks again for your talk - I've split your talk into its own video, which is now available here: https://www.youtube.com/watch?v=OJadwGNty78&list=PLam_80-FY3vSnxa361LcIM5tSmZDjSGD-&index=2 

Speak soon!

**Comment by bernardbaker** [comment]
Thanks.


Regards,

Bernard T. A. Baker
