### ISSUE TITLE
Transactional emails at scale

### ISSUE THREAD

**Issue by tschoffelen** [lnug/speakers#187]
Almost all tech startups send out a bunch of emails to their users. Many of those will be based on certain triggers, like creating accounts, new posts, invoice creation, etc. Based on my experience building some companies and apps that rely heavily on transactional emails, I'd like to talk about how to manage and structure those.

* Building and managing templates with involvement of stakeholders (marketing/partnerships team, designers, etc.)
* My solution: Macaw ([repo](https://github.com/macaw-email/macaw) | [blog](https://schof.co/macaw)) - a Node.js toolset to streamline email sending and template management
* Setting up an email sending flow in your serverless app
* (optional - depending on time) Ensuring your emails arrive: your own IP address, SPF and DKIM, reply-to, etc.

## Bio

Starting my first tech company at age 16, I've co-founded several startups that focus on improving communication and helping small businesses, including [NearSt](https://near.st), which partners with Google to help local shops make their products searchable and [Infowijs](https://infowijs.nl), which helps Dutch high schools communicate better with their students, parents and teachers.

I'm on Twitter as [@tschoffelen](https://twitter.com/tschoffelen).

---

I confirm my talk is 20 mins long in total.
I confirm that I will abide by the Code of Conduct.

**Comment by Ankcorn** [comment]
@lnug/organisers I know I am biased but I am really excited to see this talk

**Comment by admataz** [comment]
hey @tschoffelen. Thank you for your talk proposal - this sounds great!  I'd also love to hear it. 

Due to the current limitations and health concetns for actual physical meetups we are running a remote meetup at the same time as our normal monthly meetup - next Wednesday 25th starting from 7pm - and will be streaming talks live. Would you be able to present your talk via a video link? We are busy coordinating the technical details.

**Comment by tschoffelen** [comment]
Thanks @admataz!

Yep, doing it remote is no problem. By that time I should have fibre internet at home, hopefully. Looking forward to hearing about the technical details when they're known. I'm guessing I'll be able to share my screen to present some slides with code examples, right?

**Comment by admataz** [comment]
Thanks @tschoffelen  - Kevin, [who wrote this](https://dev.to/_phzn/running-my-first-online-meetup-o1h) is looking after the stream.

There's also a conversation going on in our planning channel:  https://github.com/lnug/event-planning/issues/40 - feel free to ask any questions or add your thoughts.

**Comment by admataz** [comment]
Hi @tschoffelen - @phazonoverload is looking after the streaming for Wednesday - can I leave it to you both to coordinate what's required?

**Comment by phazonoverload** [comment]
Ello! Can you join https://meet.google.com/kap-wyky-hjc at 6pm tomorrow please? Will test the setup. This call is for me, Adam, and speakers only :)

**Comment by tschoffelen** [comment]
Will do @phazonoverload! Thanks for setting everything up!

**Comment by admataz** [comment]
Hey @tschoffelen  - thanks again for your talk last month. 
I've split the live stream into the separate talks - yours is available here: https://www.youtube.com/watch?v=3h5L67voufI&list=PLam_80-FY3vSnxa361LcIM5tSmZDjSGD-&index=3 

Hope all is well - speak soon.
