### ISSUE TITLE
Super simple service health monitoring with upmon

### ISSUE THREAD

**Issue by alanshaw** [lnug/speakers#19]
A talk about this thing I built called [upmon](https://github.com/alanshaw/upmon). It's essentially a description of what it is and how to use it and how using node streams is a great way to create modular and compose-able software.

**Comment by iancrowther** [comment]
thats defo going in..! just need to check dates

**Comment by orliesaurus** [comment]
this is amazing bcuz I had a similar thing called " cronmailer " that I wanted to release, basically a wrapper for cron that would alert you when things didn't work out and errors were produced. I can't wait to hear your talk!

**Comment by iancrowther** [comment]
@orliesaurus which month?

**Comment by orliesaurus** [comment]
March it is

**Comment by iancrowther** [comment]
@rosskuklinski is doing a talk on running Node, Docker & CoreOS

https://github.com/lnug/speakers/issues/21

Worth running an uptime demo on this stack?

**Comment by alanshaw** [comment]
Is there an internet at the venue I can use during the talk?

**Comment by iancrowther** [comment]
yep, but there will be a room full of dev's on it + phones so I would have a backup gemlin slide!

**Comment by alanshaw** [comment]
It wouldn't be an exciting presentation if I wasn't flying by the seat of my pants

**Comment by iancrowther** [comment]
that maybe the slide then ;-p
