### ISSUE TITLE
How to write a DevOps friendly Node application

### ISSUE THREAD

**Issue by dgonzalez** [lnug/speakers#191]
DevOps is a necessity nowadays. It is not a job title itself but a set of practices, many of them spanning across development. It is extremely important that the applications that we write are adapted to run in a DevOps environment:
- Monitoring
- Process management
- Log aggregation
Are only few of the aspects to be considered when building a Node application in order to succeed on DevOps environments, specially containers and Kubernetes.

---

David Gonzalez is a DevOps Architect at NearForm, building systems at scale for our customers. He is also a Google Developer Expert on Kubernetes and avid coder. Author of three books around microservices and DevOps, he is always challenging the comfort zone of his day to day work finding new ways of delivering highly transactional systems.

- Twitter: [@dagonzago](https://twitter.com/dagonzago)
- [LinkedIn](https://www.linkedin.com/in/david-gonzalez-microservices/)
- GitHub: [@dgonzalez](https://github.com/dgonzalez)

**Comment by admataz** [comment]
Hey @dgonzalez  - thanks for your talk proposal - this sounds great to me... can you confirm you will be able to cover it all in about 25 minutes? 

@lnug/organisers  - any thoughts?

**Comment by Ankcorn** [comment]
I'm always up for learning more about how to make stuff more robust and stuff. Looking forward to this! 👍

**Comment by admataz** [comment]
Hey @dgonzalez  - thanks for a great coverage of practical devops - much needed information for all of us! From the conversations and feedback, I think it went very well - despite the time pressures. Thank you!

I'll post the video link here when we get that processed. Feel free to add any thoughts and feedback from a speakers perspective around the event, and it's organisation

**Comment by admataz** [comment]
Video: [How to write a DevOps friendly Node application - David Gonzalez (LNUG May 2020) - YouTube](https://www.youtube.com/watch?v=8MmZ0qh-Ti0&t=6s)
