### ISSUE TITLE
Writing A CPU Intensive Node.js Server With Worker Threads API

### ISSUE THREAD

**Issue by tamartwe** [lnug/speakers#193]
Node.js provides the developer a system with single threaded event loop architecture, that provides non blocking I/O mechanism. This work great until we get to CPU intensive tasks. In this case, Node doesn’t perform up to mark. This has changed with the release of the worker threads in latest Node versions. We can use threads and write CPU intensive code in Node. This can make Node popular in many other fields of software development, starting from algorithms , AI , complicated computations and more. In this talk I will go over the concept, API and architecture of worker threads. I will show a demo of a Node server that implements CPU intensive task , to assist you to retain a cool new ability to you Node.js coding skills

---

I am a software manager and architect. In the past, I managed large development teams, and was a CTO of a start up of my own. I have a decade of software engineering experience in various technologies: Server side, big data, mobile, web technologies, and security. I am currently focusing on Node.js, and have a deep knowledge of Node.js server architecture and Node.js performance optimizations.

[@SternTwena](https://twitter.com/SternTwena) on twitter

**Comment by admataz** [comment]
Yes! Thank you for this talk proposal. 

I'd love to hear about the new worker threads -  where and in what kinds of applications it can benefit us.  As an aside I think it's particularly interesting to see threads adopted in node.js core, given our proud history of  "single-threaded simplicity beats threaded complexity"  - and how as a platform we have matured into a tool that can allow JavaScript to be used so effectively in new ways... 

How are you fixed to deliver this via video link on Wednesday 27th May (next week)?

**Comment by Ankcorn** [comment]
This looks awesome! Looking forward to your talk 👍

**Comment by admataz** [comment]
Hi @tamartwe  - please can you drop me an email at adam@admataz.com - so I can put you in touch with the video hosts and so they can coordinate any tech/streaming issues? 

Thanks!!

**Comment by admataz** [comment]
Hi @tamartwe  - thank you so much for your talk last night - it was great to have such an advanced technical topic and thorough coverage of Worker Threads. I think it went very well, and from the twitter conversations and feedback I'd consider it a success! Thank you!

I'll post the video link here when we get that processed. Feel free to add any thoughts and feedback from a speakers perspective around the event, and it's organisation

**Comment by tamartwe** [comment]
It was a wonderful experience . Thank you !

בתאריך יום ה׳, 28 במאי 2020, 12:24, מאת Adam Davis ‏<
notifications@github.com>:

**Comment by admataz** [comment]
Video: [Writing A CPU Intensive Node.js Server With Worker Threads API - Tamar Twena Stern (LNUG May 2020) - YouTube](https://www.youtube.com/watch?v=GJNJI0vC1Ag&t=4s) 
 
🎉
