### ISSUE TITLE
11 years of Node: Let’s have an honest conversation

### ISSUE THREAD

**Issue by addaleax** [lnug/speakers#194]
Node.js has been around for a long time now, and it’s worth looking at what went great, what went well, what didn’t go so well, and where we’ll go from here.
Having been a core contributor for a long time now, I’ll reflect on the processes around Node.js and the results we’re getting out of them, and try to have an honest conversation on where the community stands and how fresh new projects like deno will change the landscape of JS outside of the browser.

---

Over the last 4 years, Anna has been one of the most active contributors to Node.js core. She is fueled by a passion for Node.js and its community.

[@addaleax](https://twitter.com/addaleax) on twitter, working at [NearForm](https://www.nearform.com/)

**Comment by admataz** [comment]
Hi @addaleax. that's brilliant - thank you so much for this - it's just the talk we would like to hear at this month's meetup... I look forward to hearing it! Let us know how you get on with the prerecording  - or if you change your mind and decide to go live with it on the night - up to you....

**Comment by admataz** [comment]
Hi @addaleax  - thanks for the great talk last night - it was very well presented and well paced - and lots of spin-off conversations... I'll post the video link here when we get that processed. Feel free to add any thoughts and feedback from a speakers perspective around the event, and it's organisation

**Comment by admataz** [comment]
Video: [11 years of Node: Let’s have an honest conversation - Anna Henningsen (LNUG May 2020) - YouTube](https://www.youtube.com/watch?v=TthueRgvVQ4&t=4s)
