### ISSUE TITLE
Creating end-to-end typesafe APIs with tRPC

### ISSUE THREAD

**Issue by ixahmedxi** [lnug/speakers#197]
[tRPC](https://trpc.io)  is an API layer utilising the full power of TypeScript to deliver fully typesafe APIs from the backend to the frontend. The newest version of tRPC has been released recently (v10) which brought a lot of revolutionary features such as go to definition from the frontend to the backend and a more robust API.

In this talk I will talk about what tRPC is, comparison with GraphQL and REST, introducing V10 and the differences and improvements it builds upon from V9 as well as walking through creating a simple API with tPRC and connecting it to the frontend (Next.js).

I'm an Egyptian web developer and final year computer science student at Royal Holloway University of London and have been into web development ever since I was about 14 years old. I'm also a contributor of tRPC having helped with the website redesign and implementation, og image generation, code refactors and much more.

- [Twitter](https://twitter.com/ixahmedxii)

- [x] I confirm that I will abide by the [Code of Conduct](https://lnug.org/code-of-conduct.html)

- [x] I confirm my talk is 20 mins long in total.

**Comment by Ankcorn** [comment]
Hi Ahmed!

The talk sounds great.

We are going to try and run LNUG on the 22nd at Ballys Interactive https://goo.gl/maps/Cc9z1Vj91u7nQ6qH7

Can you make this date?

If you have any questions feel free to reach out

**Comment by ixahmedxi** [comment]
I can confirm that I will make this date
