### ISSUE TITLE
Fastify - a fast web framework with batteries attached and amazing TypeScript support

### ISSUE THREAD

**Issue by mikeborozdin** [lnug/speakers#198]
**Abstract**

There are more web frameworks for Node.js than Express. [Fastify](https://www.fastify.io/) is a great alternative to Express. It's blazingly fast. It's got a lot of features out of the box that require don't require installing additional package unlike other frameworks. And it's got an amazing TypeScript support.

In this talk we'll build a REST API while exploring Fastify features. We'll also compare it with what we would have to do in other Node.js frameworks.

**About me**

Mike is an entrepreneurial software engineer. He's built products across the entire stack ranging from native Android apps to serverless ML pipelines. And now he's helping to build a brand new AI product for [Tractable](https://tractable.ai/). In his spare time he tries build a personal finance product - [Cashable](https://www.cashable.app/).

[Twitter](https://twitter.com/mikeborozdin)
[Blog](https://mikeborozdin.com/)

- [x] I confirm that I will abide by the [Code of Conduct](https://lnug.org/code-of-conduct.html)

- [x] I confirm my talk is 20 mins long in total.

**Comment by Ankcorn** [comment]
Hi Mike!

The talk sounds great.

We are going to try and run LNUG on the 22nd at Ballys Interactive https://goo.gl/maps/Cc9z1Vj91u7nQ6qH7

Can you make this date?

If you have any questions feel free to reach out

**Comment by mikeborozdin** [comment]
Hi @Ankcorn,

Thank you! And sorry for the late response! Unfortunately, I'm going on holiday on the 22nd.

Can I give a talk at the event after then?

**Comment by Ankcorn** [comment]
Hey @mikeborozdin, awesome to run into you last night, just to confirm would you potentially be able to make the 22nd of march?

**Comment by mikeborozdin** [comment]
@Ankcorn, yeah, all good 👍

**Comment by admataz** [comment]
Hey @mikeborozdin  - I hope all is well  with you - just cleaning up a few old issues - if you didn't see, the video from your talk is on YouTube - you can also find it [on our site](https://lnug.org/talks/fastify-fast-web-framework-with-batteries-attached-and-amazing-typescript-support-mike-borozdin-april-2023-ksI-v1uXmbk)

Hopefully see you at the next meetup (26 September - see here)[https://www.meetup.com/london-nodejs/events/295949812/]
