### ISSUE TITLE
⚡️Lightning talks for February 22nd 2023 🎤

### ISSUE THREAD

**Issue by admataz** [lnug/speakers#199]
We're opening the mic to lightning talks  - something node related. 5 minutes allowed. 

Add your topic and name to the comments and a bit about you, e.g. current job, twitter handle, etc.

- [x] I confirm that I will abide by the [Code of Conduct](https://lnug.org/code-of-conduct.html)

- [x] I confirm my talk is 5 mins long in total.

**Comment by errietta** [comment]
Name: Erry Kostala
Topic: web antipatterns
company: software engineer at TAKUMI international ltd

**Comment by MattBidewell** [comment]
(not directly node related, but git related) 🥺 

Name: Matt Bidewell
Topic: The wonderful world of Trunk based development
Company: Beamery

**Comment by akash-joshi** [comment]
Name: Akash Shirish Joshi
Topic: Breaking client-server barriers with rocketrpc
Company: Meta

**Comment by Ankcorn** [comment]
Thank you everyone! Looking forward to seeing you on Wednesday. These talks sound great

@errietta welcome back! Hope you are doing well. Looking forward to your talk 🙂

@MattBidewell It's fine as long as you promise you are writing node whilst you are doing trunk based development!

@akash-joshi interesting topic! Just wanted to check you are aware the main talk of the night is about TRPC.  We encourage a bit of friendly rivalry so it's totally okay to have your talk

**Comment by akash-joshi** [comment]
@Ankcorn I am aware yes, my library was built around the same time. And have met the creator in person as well :)

**Comment by Ankcorn** [comment]
Thank you so much for coming and sharing with us! Was brilliant :partying_face:
