### ISSUE TITLE
Francisco Ferreira - Javascript Craftsmanship

### ISSUE THREAD

**Issue by fmsf** [lnug/speakers#20]
Avoid stepping into the rabbit hole with common anti-patterns and bad code. With a strong emphasis on how JavaScript code can be done beautiful and maintainable, this talk explains how to write very readable and testable code. At eBay we love to have our code clean, so we’ll use some examples of eBay’s code during this presentation.

We’ll touch topics on how functional can intersect with object oriented programming to decrease the learning curve to your code. Or how choosing the correct data structures is more important than ever to guarantee optimal performance. 

All of this in a framework agnostic way, so that it is easy to take home and apply to your projects with ease. 

Hopefully after you have attended this talk you will code cleaner.

Topics covered:

Code readability
Functional JS
Object Oriented JS
Unit Testing
Code structuring

**Comment by iancrowther** [comment]
thanks @fmsf
