### ISSUE TITLE
Destroying Client-Server Barriers using TypeScript

### ISSUE THREAD

**Issue by akash-joshi** [lnug/speakers#200]
[Abstract of your talk]

Could you access the Prisma client on the frontend - without revealing any environment variables? This talk goes into my experimentation with Object proxies and websockets, allowing a developer to access server-side objects on the client, with type-safety.

I'll walk through how the proxying works, the type-safety features, and everything else which makes the library works. https://rocketrpc.com

Use Cases:
- Define a type-safe API layer on the backend
- Share objects like ORM clients with the frontend 

[A bit about you, e.g. current job, twitter handle, etc.]

I'm a frontend developer at Meta London, with an extreme interest in open source and building web apps for the future. I have 4 years of professional experience in total, but have been contributing via articles and open-source projects since 2016. You can find me on Twitter @thewritingdev.

- [X] I confirm that I will abide by the [Code of Conduct](https://lnug.org/code-of-conduct.html)

- [X] I confirm my talk is 20 mins long in total.

**Comment by Ankcorn** [comment]
Hey I'm trying to get organised and have an lnug on the 22nd of march, would you be able to make this data?

**Comment by admataz** [comment]
Thanks for the talk! cleaning up the issues. The video is now on the website.
