### ISSUE TITLE
Allen Helton - Creating best-in-class developer experience for your SDKs

### ISSUE THREAD

**Issue by allenheltondev** [lnug/speakers#201]
**Abstract of your talk**

In this talk, we will explore the best practices and strategies for building a best-in-class developer experience for a Node.js SDK. We'll cover the essential elements of an excellent developer experience, including documentation, fundamentalism, and lowering time to first call. We will also cover how to meet your users where they are. Knowing who you're building for is critical to developer experience. Follow along as I talk about my experience with the Momento Node.js SDK and how I worked on taking it from a poor DX to a great one. Whether you're a seasoned developer or new to the game, you'll come away from this talk with valuable insights and actionable strategies for building a world-class SDK.

**A bit about you, e.g. current job, twitter handle, etc.**

I am an AWS Serverless Hero and Ecosystem Engineer at Momento. I have over a decade of experience in tech and 4+ years in AWS serverless. My focus is on educating others on the nuance of serverless development, API design, and caching/data concepts. I write extensively on my personal blog, Ready, Set, Cloud, where I also send out a weekly serverless newsletter and host a podcast. When I'm not neck deep in serverless you can find me tending to my 39 chickens and turkeys and teaching my two girls some life lessons along the way. To follow my journey, you can find me on Twitter, LinkedIn, and GitHub at @allenheltondev.

**Date of meetup**

April 26th

- [ **X** ] I confirm that I will abide by the [Code of Conduct](https://lnug.org/code-of-conduct.html)

- [ **X** ] I confirm my talk is 20 mins long in total.

**Comment by admataz** [comment]
Hey @allenheltondev  - thanks for the talk all those months ago - I hope you had a good time in London. I'm cleaning up a few of the old issues as we are getting ready for the next round of meetups - I hope you had the link your video already on youtube - it's [also on our site](https://lnug.org/talks/creating-best-in-class-developer-experience-for-your-sdks-allen-helton-april-2023-lxjhs-BDEw4)


Drop by again next time you're in town
