### ISSUE TITLE
Praveen Kumar Purushothaman - Client Side JavaScript Encryption & Decryption

### ISSUE THREAD

**Issue by praveenscience** [lnug/speakers#202]
**Abstract of your talk**

In this intriguing JavaScript talk, we delve into the world of client-side encryption and decryption, presenting a daring idea that promises enhanced safety. By exploring the potential of safeguarding sensitive information within the realm of JavaScript, we embark on an unconventional journey that challenges conventional practices. Brace yourself for an unconventional approach that pushes the boundaries of security and dares to place valuable data in an unexpected location. This talk is going to be completely practical. 💪🏻

Use Cases:

* Storing Email Address or Phone Number under a password on a public website.
* Storing Exam Results on a public website for only those who want to know.

**Some more information:**

A small video of my talk...

https://github.com/lnug/speakers/assets/1830380/b0f078c4-347e-4bed-b9ed-73c7447033fe

It would be amazing to get this scheduled on the 100th Meetup! 💪🏻

**A bit about you, e.g. current job, twitter handle, etc.**

I’m Praveen Kumar Purushothaman, a London-based Director of Engineering at a Fortune 50 FinTech in Canary Wharf. Originally from Chennai, India, I’m an avid JavaScript enthusiast, specialising in React and Node JS, while also harbouring an extreme love for cats. I [tweet](https://twitter.com/praveenscience) at @praveenscience and I’m extremely active on [LinkedIn](https://www.linkedin.com/in/praveentech/) & WhatsApp. 📱

All the creatives and more information about me, you can find them here: [Schedule a Workshop with Praveen](https://events.praveen.science/).

- [x] I confirm that I will abide by the [Code of Conduct](https://lnug.org/code-of-conduct.html)
- [x] I confirm my talk is 20 mins long in total.

**Comment by praveenscience** [comment]
@admataz Yea, it's gonna be concentrated on the Node side of things, and this time I have changed a lot in the content of the presentation so it's not gonna be like how it was before.

**Comment by admataz** [comment]
Hi @praveenscience  - looking forward to seeing you later this evening. It would be good if you can get in to Makers a little early - say 6:15 or so to coordinate with the videographer and laptop issues - it's generally done via a shared zoom call hosted at the venue account - I'll share the invitation to that over email

**Comment by admataz** [comment]
OK, I don't have your email - I'll DM you in twitter

**Comment by admataz** [comment]
lol, you don't follow @lnugorg - can't DM you - we can work it out at the venue

**Comment by praveenscience** [comment]
Hey @admataz & @Ankcorn just saw this. All good here?

**Comment by admataz** [comment]
Hi @praveenscience - all good. I'll try follow up with the video - with pusher closing up their sessions we have some gaps
