### ISSUE TITLE
Crafting Robust APIs with TypeScript: A Hands-On Approach

### ISSUE THREAD

**Issue by artfuldev** [lnug/speakers#204]
Immerse yourself in a hands-on exploration of crafting robust, self-documenting, and efficient APIs with TypeScript. This dynamic session urges a rethink of conventional API development, focusing on how TypeScript's static typing can help develop accurate and consistent APIs - making impossible scenarios impossible.

We'll untangle a common problem into an intuitive API, emphasizing on clear API signatures to prevent error scenarios instead of just handling them. We'll illustrate how TypeScript's features can diminish potential failures, resulting in APIs that are easier to use, inherently self-describing, and highly reliable.

Tailored for developers with a basic understanding of APIs and typed languages, this session is also an invitation for anyone keen on writing quality code to delve deeper into effective API design. While familiarity with TypeScript is beneficial, it's not a prerequisite - we'll navigate the learning curve together.

By the end of this talk, you'll walk away with fresh insights on how to leverage TypeScript to improve API design, making them more robust and user-friendly. Even if you find yourself disagreeing with the viewpoints presented, you'll undoubtedly emerge with a more thoughtful approach to API design. Ready to roll up your sleeves and redefine robust API design? Let's embark on this hands-on journey together, TypeScript style!

About me:
Hi, I'm Sudarsan Balaji, also known as artfuldev, a full stack engineer focused on creating and multiplying value. A few links if my github bio isn't enough:
https://artful.dev
https://journal.artful.dev
https://linkedin.com/in/artfuldev
https://twitter.com/theartfuldev

- [x] I confirm that I will abide by the [Code of Conduct](https://lnug.org/code-of-conduct.html)

- [x] I confirm my talk is 20 mins long in total.

Actually I'd like a slightly longer session if possible (anywhere from 30 mins to 90 mins) - this one works best when there's a lot of interactions between the audience and me, as we try to start with a basic API for a trivial problem, and try to work on problems with it with ideas from the audience, slowly building up to a (more) robust API. I have presented this as a 30min talk earlier and also as a 5 min lightning talk at a lunch event, so I'm okay to work with the timings, it's just that it works best with a lot of audience engagement.

I'm happy to receive help/advice on this.

**Comment by admataz** [comment]
Hi @artfuldev - thanks so much for your talk proposal. Looking forward to hearing more about your approach and involving the audience in some positive thinking around all those red squiggly lines 😈


Just confirming you are scheduled in for the next LNUG meet up on 26 September at Makers Academy. 

I'm not sure if you have discussed timings with @akash-joshi - but I would ask to stick to the 20-30 minute format.

**Comment by artfuldev** [comment]
I will be there - and try my best to keep it to around 25 minutes so we have a few minutes of question time. Please help me out by giving me a heads up if I'm running late at around 25 mins. (I do usually have a timer on me esp. if I have a screen to work with)

**Comment by admataz** [comment]
Hi @artfuldev  - looking forward to seeing you later this evening. It would be good if you can get in to Makers a little early - say 6:15 or so to coordinate with the videographer and laptop issues   - it's generally done via a shared zoom call hosted at the venue account - I'll share the invitation to that over email

**Comment by artfuldev** [comment]
I plan to get there at 5.30 or so if that won't be disruptive. I share an editor which I try to edit code with while I also have slides to switch between so my setup is a little more complicated than just sharing slides or a single screen and I'd like to get it tested early. Now I guess that's also supposed to be tested with zoom so I have a bit of work to do.

**Comment by admataz** [comment]
Ok sounds good - earlier should be fine - I'll ony join later but @Ankcorn and @akash-joshi should be around to help - and Alex the videographer (or one of his people) will be there to help get things sorted

**Comment by artfuldev** [comment]
Thanks, it was a wonderful event!

**Comment by artfuldev** [comment]
Hi, did we record the session? Would love to see it online!
