### ISSUE TITLE
The next stage of serverless is personal

### ISSUE THREAD

**Issue by threepointone** [lnug/speakers#209]
Serverless changed the world by bringing on-demand compute to everyone across the planet, but with tradeoffs, making certain architectures like multiplayer and collaboration much harder to implement. The next evolution aims to fix these problems, and is available today. In this talk we'll talk about the details of this evolution, and see what new capabilities and tradeoffs arise. 

Sunil Pai is the founder of [PartyKit](https://twitter.com/partykit_io), an open source platform for building  real-time, collaborative, multiplayer apps. You can find him at [@threepointone](https://twitter.com/threepointone/) and [@partykit_io](https://twitter.com/partykit_io)

- [x] I confirm that I will abide by the [Code of Conduct](https://lnug.org/code-of-conduct.html)

- [x] I confirm my talk is 20 mins long in total.

**Comment by Ankcorn** [comment]
Thank you for the talk submission @threepointone. Very excited about this talk. :grin:

**Comment by admataz** [comment]
ooh. this is exciting - I love what I've heard about Partykit.   @threepointone  - thank you for your talk submission! I look forward to hearing more about what you're up to and these patterns and the kind of fun we can have with this. 

I've scheduled this for our November 29th meetup - we'll be at Makers Academy in Shoreditch - hope that works for you?

**Comment by threepointone** [comment]
Yup that works for me. Looking forward to it!
