### ISSUE TITLE
Building NodeJS Applications with Docker & CoreOS

### ISSUE THREAD

**Issue by rosskukulinski** [lnug/speakers#21]
Hello!

I'm a co-organizer of [BayNode](http://www.meetup.com/BayNode/) and internet friends with @orliesaurus and @iancrowther.  We've been kicking around the idea of sharing pre-recorded talks.

I'm proposing to do a (revised) screencast of a talk I did at BayNode in November.  Slides for that talk can be found [here](http://www.slideshare.net/kuxman/bay-node-dockernodejscoreos)

**Comment by iancrowther** [comment]
so would we live stream? or just play back the video?

**Comment by rosskukulinski** [comment]
I was thinking just playback the video, but if timing works out, I'd be willing to live-stream

**Comment by bencevans** [comment]
Some sort of Node/io.js (:P) website/collection with talks from all the
Node/io.js meetups would be awesome. Not sure about just showing the videos
at the events when people can watch them wherever they are would be of much
interest personally.

The subject of this presentation sounds great! Unfortunately I can't get
the presentation at the moment due to a lacking speed in connection.

**Comment by iancrowther** [comment]
@rosskukulinski it would be between 11:00 - 13:00 your time.  Live stream would be :+1:

**Comment by iancrowther** [comment]
@bencevans thats a cool idea -> https://github.com/lnug/feedback

**Comment by bencevans** [comment]
Live stream would be cool though! :D

**Comment by rosskukulinski** [comment]
@iancrowther yeah, that should work

**Comment by iancrowther** [comment]
yay

**Comment by basicallydan** [comment]
:+1: This idea, love it.

**Comment by lukebond** [comment]
@rosskukulinski are there slides or video available for this? want to make sure i don't overlap too much with my next talk.

**Comment by rosskukulinski** [comment]
@lukebond no, I would probably put something custom together.  In principal it would be similar to the november talk, but focus more on the containerizing / microservice-ing of nodejs apps.  I'm also perfectly happy to do something unrelated.
