### ISSUE TITLE
Suspend Server Side Request Waterfalls 

### ISSUE THREAD

**Issue by Ankcorn** [lnug/speakers#210]
[Abstract of your talk]
Moving your app to a server side rendered approach has performance pitfalls people are not talking about enough. 

The server side request waterfall blocks page loads and can make the UX bad. But what can we do other than move data fetching back to the client? 

Streams, WebStandards, and Transfer-Encoding: Chunked. 

We are going to break down how these tools work and and why we would use them and finally I am going to show how [HonoJS](https://github.com/honojs/hono) helps package up these tools to provide an easy-to-use and familiar API to solve this problem.

[A bit about you, e.g. current job, twitter handle, etc.]
I work at [Baselime](https://baselime.io) on distributed tracing and observability for Node.JS applications and Occasionally help organise LNUG.

* [@thomasankcorn on twitter](https://twitter.com/thomasankcorn)

- [x] I confirm that I will abide by the [Code of Conduct](https://lnug.org/code-of-conduct.html)

- [x] I confirm my talk is 20 mins long in total.

**Comment by admataz** [comment]
Yes! Thanks @Ankcorn  - looks good. Love the idea of fast edge hosted stream of data and a better UX - hadn't heard of HonoJS, but it looks like a fun framework, worthy of a demo.
