### ISSUE TITLE
Looking sharp: 10 years of Node.js image processing

### ISSUE THREAD

**Issue by lovell** [lnug/speakers#211]
[Abstract of your talk]

From the history of art, through the worlds of fashion, sustainability and security, this talk details the story of [sharp](https://sharp.pixelplumbing.com/) as it made its way into many of the popular JavaScript frameworks and tools we use today.

_This will be an updated (and distilled to 20 minutes) version of a talk I did at last year's [WebDirections Lazy Load conference](https://webdirections.org/lazyload/)._

[A bit about you, e.g. current job, twitter handle, etc.]

Lovell is a freelance software developer based in London, coding since the 1990s and still learning, with experience across a wide range of industries.

https://lovell.info/

- [X] I confirm that I will abide by the [Code of Conduct](https://lnug.org/code-of-conduct.html)

- [X] I confirm my talk is 20 mins long in total.

**Comment by admataz** [comment]
Hi @lovell  - sorry about the slow response. Between the holiday season and getting back to a new project at work I've dropped a few things. 

I love it when the tech we work with has the real world and cultural storyline - fascinated to hear more about  sharp. I think you have the makings of a good talk for LNUG - would love to host you at an upcoming meetup. 

We are working out our schedule for the coming months with sponsors and venue. Would you have a preference for Feb, pr March or other?  - usually a mid-week towards the end of the month.

**Comment by lovell** [comment]
Hi Adam, no worries, this all sounds great. February is good for me, with 21/22/28/29 all free at the moment. Looking forward to it!

**Comment by Ankcorn** [comment]
Hey @lovell 

Sorry for dropping off the face of the earth here.

We have found a venue for the 22'nd of may at the cloudflare london offices.

If this suits you could you let me know? Your talk sounds fantastic so fingers crossed 🤞

**Comment by lovell** [comment]
@Ankcorn Hello, no worries about the delay, I'm aware how much effort goes into finding sponsors/venues for meetups (especially when very few companies are actively hiring) so thank you for all your work.

Since proposing this talk I've been asked by the organisers of another London-based tech meetup to present on the 21st May, the day before, and I was planning to deliver this same talk. This event hasn't been announced yet and it's possible there may be some overlap in attendees. Would this be OK, at least in theory? (I'll also check with the other meetup organisers to see if they are OK with this.)

**Comment by Ankcorn** [comment]
This is okay in theory for us 🙂

I will keep you in the loop as I finalize sponsors and get the event pages up.

**Comment by Ankcorn** [comment]
Hey @lovell 

We spoke with the City JS organisers, I am unsure of the conversations you had with them but would it be best for you to do this talk at lnug at a later meetup?

**Comment by lovell** [comment]
I was originally told by the CityJS organisers that I'd be speaking at the same event as @admataz, which turned out to be incorrect and has led to this situation.

I'm happy to speak at both events and will repeat the message I told the CityJS organisers: "I don't want to disappoint anyone, especially either audience."

I've no idea how much overlap, if any, there will be in terms of (potential) attendees.

Thank you for continuing to be open about all this, it's refreshing to have at least half of this conversation in public.

**Comment by simkesd** [comment]
Hi @Ankcorn , i just want to check where we stand with this. I imagine we share quite a few members and in order to keep both sides happy, I would rather have @lovell speak only at one event. Will it be possible for you to find a replacement? If not, I think I can sort something out on JS Monthly side.

**Comment by admataz** [comment]
Hey @simkesd and @lovell ! Sorry if there's any confusion - been chatting with @Ankcorn  - and just to confirm we are totally happy that you go ahead as planned  with your schedule for the 21st.  There will be future LNUGs - and we can catch up with an iteration of the talk in coming months when there's less of a crossover. 

Thanks for flagging the proximity! Hope to see you at one or both of the May events.

**Comment by admataz** [comment]
> speaking at the same event as @admataz 

I wish I could get it together to plan a talk - too many zoom meetings! Maybe one day!

**Comment by lovell** [comment]
Thanks all, glad this has been sorted out, I'm happy to keep this issue open for a possible future LNUG event later in the year.

@simkesd No pressure on us both but I guess we now have to ensure the event on the 21st May is doubly good. :sweat_smile: 

@Ankcorn I'll see you at LNUG on the 22nd May, and (for me) in the slightly more relaxing role of audience member.

**Comment by Ankcorn** [comment]
Hi @lovell,

It was great to meet you at our last event, I'm organising lnug for June 26th. Are you still interested in giving your talk?

Thank you

**Comment by lovell** [comment]
@Ankcorn Likewise, and yes, I'm available on the 26th.

**Comment by Ankcorn** [comment]
Amazing! I will get everything scheduled.

See you then

**Comment by Ankcorn** [comment]
Hi @lovell,

Thank you so much for your talk, it was inspiring to learn about the story of sharp. Hope to see you soon! :)

**Comment by admataz** [comment]
Hey @lovell  - seems I left this thread open - the videos from LNUG in June  are available at [this playlist](https://www.youtube.com/watch?v=wql4Ci4WLLE&list=PLam_80-FY3vQ2Jeb6kCiU3kjmCtWSXjnS) on YouTube. 

You're talk is [here](https://www.youtube.com/watch?v=YEE1Kp4ZS4w&list=PLam_80-FY3vQ2Jeb6kCiU3kjmCtWSXjnS&index=3)

Thanks again for a great talk - hopefully see you again soon.
