### ISSUE TITLE
Typescript all the way down

### ISSUE THREAD

**Issue by pierskarsenbarg** [lnug/speakers#212]
In 20 minutes, Piers will show that Pulumi allows Typescript and NodeJS developers to expand what is meant by “full stack developers”, going from the Front End all the way down to the Infrastructure level. 

Piers is a Senior Solutions Engineer at Pulumi, working with users to build and manage their cloud infrastructure. 

- [x] I confirm that I will abide by the [Code of Conduct](https://lnug.org/code-of-conduct.html)

- [x] I confirm my talk is 20 mins long in total.

**Comment by Ankcorn** [comment]
Thanks @pierskarsenbarg , sounds interesting.

you good for Wednesday 22nd of May?

**Comment by pierskarsenbarg** [comment]
All good
