### ISSUE TITLE
Lessons Learned Building an AI CLI in 2024

### ISSUE THREAD

**Issue by akash-joshi** [lnug/speakers#214]
[Abstract of your talk]

How is an AI-powered CLI which allows you to confidently write complex commands and queries in your CLI. This talk goes into how "How" was built, talking about the no-build CLI deployment process, type-safety, cross-OS compatibility, and more!

[A bit about you, e.g. current job, twitter handle, etc.]

I'm a software engineer at RocketConnect, like to host meetups and write code in my spare time and also run!

@thewritingdev on Twitter

- [ X ] I confirm that I will abide by the [Code of Conduct](https://lnug.org/code-of-conduct.html)

- [ X ] I confirm my talk is 20 mins long in total.

**Comment by Ankcorn** [comment]
Hey @akash-joshi ,

Getting this scheduled for the 31st of July.

Thanks for the talk submission. Excited to hear it.

**Comment by admataz** [comment]
Hey @akash-joshi  - just confirming the [videos for the LNUG 105  are online](https://www.youtube.com/watch?v=DAqtwllkz3M&list=PLam_80-FY3vSpaUlOSFPIBVK5cMGm8TVA)  - yours is at https://www.youtube.com/watch?v=C2maxcMr53E&t=2s

**Comment by admataz** [comment]
...and of course - Big Thanks for the talk - really enjoyed watching it again
