### ISSUE TITLE
Type-safe app configuration: a powerful, emerging way to accelerate product development

### ISSUE THREAD

**Issue by miraan** [lnug/speakers#215]
Everyone has heard of feature flags: boolean switches in your code that you can flip at runtime for different users, environments, etc. But they are just one part of a much broader best practice called “application configuration”. Big tech companies like Meta and Google have internal tools for structured, type-safe app configuration that help them accelerate development of products and backend services. This talk dives into what app configuration is and how it can empower your whole team to move faster, including your nontechnical colleagues.

Miraan is the founder at Hypertune. He was previously at Meta where he led teams across frontend, mobile, backend and machine learning.

- [x] I confirm that I will abide by the [Code of Conduct](https://lnug.org/code-of-conduct.html)

- [x] I confirm my talk is 20 mins long in total.

**Comment by Ankcorn** [comment]
Hi @miraan 

Thanks for the awesome talk submission. It sounds really interesting.

Can you do July?

Thanks

**Comment by miraan** [comment]
Hi @Ankcorn glad it sounds interesting! Yes I can do July

**Comment by Ankcorn** [comment]
Hi @miraan how does the 31st of July sound to you? I'm just in the process of finalising the scheduling.

**Comment by miraan** [comment]
Hi @Ankcorn, 31 July sounds great!

**Comment by Ankcorn** [comment]
That's great, I will get everything up on meetup and the website by tomorrow. 

Have you been to LNUG before? (Sorry if we spoke and I forgot!)

Let me know if you have any questions about speaking at LNUG let me know.

**Comment by miraan** [comment]
I have, yes! Although not many. Thank you, I'll let you know if I have any questions

**Comment by Ankcorn** [comment]
Hey @miraan , all good for tonight?

**Comment by miraan** [comment]
@Ankcorn yes, all good!

**Comment by admataz** [comment]
Hey @miraan thank you for the talk. I heard good praise from attendees. Nicely done! How did the QuickTime video turn out? Can you share a copy somewhere and I'll try get everything synced in the video.

**Comment by miraan** [comment]
Hey @admataz, thank you for having me! Glad to hear there was good praise. The QuickTime video worked well for the first half of the talk with the live demo but when I switched from screen mirroring to extending for the second half, it captured the wrong screen (with the presenter notes window rather than the main slides). I switched back to mirroring for the Q&A so that part is fine.

The recording is here: https://drive.google.com/file/d/1m16p-TE-f2zhHKf6tXOiqiQldHb1MAw4/view?usp=sharing

The affected time period is 9 minutes between 14.56 - 23.53 so we could re-record that part with the main slides (in sync with the presenter dialog) and it should all be good.

The slides are here: https://docs.google.com/presentation/d/1e58buB2DB4ve3R2o8SMyQ9BnXULzprty9tofynNwS3E/edit?usp=sharing

Let me know if that sounds good, and I can have a go at re-recording this part and splicing it in.

**Comment by admataz** [comment]
Hey @miraan - thanks for this - I've put the videos and audio together - and left a gap for the missing screen recording between `14:13` and `23:30` - it would be great if you could try rerecording that segment and share with me and I'll add it in. 
here's a copy of the draft video for reference:
https://www.dropbox.com/t/p0zKbwkDzIUitEpR

**Comment by miraan** [comment]
@admataz apologies for the delay. I just checked the link now but it looks like it expired yesterday unfortunately. Would you be able to share another link?

**Comment by admataz** [comment]
Hey @miraan - no worries - try this link https://www.dropbox.com/scl/fi/mmp5lvp6op6iji7pfpkcn/DRAFT-miraan-lnug-2024-07-31.mp4?rlkey=tl0rplx2jbpxrc9ohovffeklu&dl=0

**Comment by miraan** [comment]
@admataz thank you! I've recorded the slides for the gap here: https://drive.google.com/file/d/1VpY8YoyY2SJ1USQXiM8hjvTvLT5m-bJy/view?usp=sharing

**Comment by admataz** [comment]
Thanks @miraan  - I've put the final version together -  the [videos for the LNUG 105  are online](https://www.youtube.com/watch?v=DAqtwllkz3M&list=PLam_80-FY3vSpaUlOSFPIBVK5cMGm8TVA)  - yours is at https://www.youtube.com/watch?v=DAqtwllkz3M

Thanks again for the great talk
