### ISSUE TITLE
Effect Loves Node.js

### ISSUE THREAD

**Issue by mikearnaldi** [lnug/speakers#216]
The reason I created Effect in the first place was to develop production grade backends in TypeScript targeting Node.js, today I'll be showing the result! In this talk we will be looking at a live demo & coding session where we will develop an API server and client from scratch using Effect and Node.js that includes features such as OpenAPI spec generation, OpenTelemetry, Metrics and much more.

I am the author of Effect and the CEO of Effectful Technologies, my twitter is [https://x.com/MichaelArnaldi](https://x.com/MichaelArnaldi)

- [x] I confirm that I will abide by the [Code of Conduct](https://lnug.org/code-of-conduct.html)

- [x] I confirm my talk is 20 mins long in total.

**Comment by Ankcorn** [comment]
Thanks @mikearnaldi 

Really excited about this. It's going to be on June 26th

For context for other organisers, me and Micheal have been talking about this talk in dm's for a few months and has organised to travel to London specifically for the 26th

**Comment by Ankcorn** [comment]
Hi @mikearnaldi 

Thank you so much for the talk! It was great to get insight into the power of Effect and I love the hat :)

We will get the video footage up asap, @admataz has it on his laptop but has a lot of commitments.

**Comment by mikearnaldi** [comment]
I am just back home, will upload the screen recording tomorrow

**Comment by mikearnaldi** [comment]
@Ankcorn here you go apologies for the delay https://drive.google.com/file/d/1IuS1WKwHeBftP9YkMzvaCTjU7K3FquW-/view?usp=sharing

**Comment by Ankcorn** [comment]
No problem, Thank you for coming to speak! I hope we can see you back at LNUG again some time  

The video for your talk is here

https://www.youtube.com/watch?v=wql4Ci4WLLE

**Comment by admataz** [comment]
Thanks again @mikearnaldi  for the great talk. Al videos from the night are available at the [playlist on youtube. ](https://www.youtube.com/watch?v=wql4Ci4WLLE&list=PLam_80-FY3vQ2Jeb6kCiU3kjmCtWSXjnS&index=2)

Hopefully see you again at a future LNUG
