### ISSUE TITLE
Sniffing API requests for fun a̶n̶d̶ p̶r̶o̶f̶i̶t̶

### ISSUE THREAD

**Issue by OZCAP** [lnug/speakers#217]
### Abstract
In this talk, I talk through my process of messing with the Bereal native app to post custom images by intercepting Firebase file upload requests. this talk is inspired by [my blog post](https://blog.oscars.dev/posts/hacking_bereal_with_man_in_the_middle/) on the subject. Through the presentation, I reflect on security considerations for building native apps, especially security concerns associated with Firebase. 

**This is the same talk I delivered at the London Supabase GA release event**

### About me
Senior fullstack Typescript dev, working for a women's fertility med-tech startup (Hertility). I also contract in Antarctica over the winter to help scientists with experiments.

https://x.com/oscars_dev

- [x] I confirm that I will abide by the [Code of Conduct](https://lnug.org/code-of-conduct.html)

- [x] I confirm my talk is 20 mins long in total.

**Comment by Ankcorn** [comment]
Hi @OZCAP 

This sounds awesome! :) I recently had some fun doing this but with charles proxy which I found a bit clunky. I did not know about mitm which looks super slick 

I'm looking to organise the next event on the 27th of August but have not confirmed that yet with our hosts. Are you around that week?

**Comment by OZCAP** [comment]
Hey @Ankcorn!

I would love to speak then if you would like me to. I've reserved the date in my calendar! :)

**Comment by Ankcorn** [comment]
Sorry @OZCAP  I got my dates mixed up. It's wednesday the 28th of August. Is that still okay?

Really sorry for the confusion!!!

**Comment by OZCAP** [comment]
@Ankcorn, no problem at all. I am also free that day so we are all good. If you need to send me any extra details directly, feel free to DM on twitter or send to [x@osc.sh](mailto:x@osc.sh)! :)

**Comment by admataz** [comment]
Hey @OZCAP  - great to see you last night - and thank you for a great talk - and very well delivered. I look forward to hearing some of your other adventure "stories for another time" :)

Can you share the screen recording? here's a link to my dropbox  https://www.dropbox.com/request/RqCxwXSZ4GxNV36kA5oz

**Comment by OZCAP** [comment]
Hey @admataz ! Thanks for having me. I have attached the screen recording along with a little README for you. Best

**Comment by admataz** [comment]
Thanks @OZCAP  - received and understood - I agree totally!

**Comment by admataz** [comment]
Hi @OZCAP - thanks for the screen recording... I've put the video together and it's now available on YouTube 
https://www.youtube.com/playlist?list=PLam_80-FY3vTTq1vV0vDmKCI0s0U3N4xw

Thank you again for contributing  - hopefully see you again soon!

**Comment by OZCAP** [comment]
Hey @admataz is there an email where I can contact you on?
