### ISSUE TITLE
NodeJS stream module

### ISSUE THREAD

**Issue by mrbrianevans** [lnug/speakers#218]
NodeJS provides a brilliant built-in "stream" module for working with data streams. It is well suited for processing large data files and its promises API super-charges working with async iterables, such as paginating items from an API. This talk will feature a real time coding demo of how I've written simple data processing scripts for quick analysis at work, rapidly and effectively crafted using the `node:stream/promises` module. I'll also present some bonus developer tips on other use cases for the highly flexible Readable stream API. 

Brian Evans is a full stack software engineer working in London using Javascript/Typescript.

- [x] I confirm that I will abide by the [Code of Conduct](https://lnug.org/code-of-conduct.html)

- [x] I confirm my talk is 20 mins long in total.

**Comment by Ankcorn** [comment]
Hello @mrbrianevans 

Thank you for your talk submission, are you available the last full week of august (25th - 29th).

I'm looking to arrange the next LNUG that week but have not fully confirmed the date yet.

Can you also confirm your talk will be 20 minutes long?

**Comment by mrbrianevans** [comment]
Hi Tom. 
Unfortunately I'm not available that week, since its the bank holiday weekend I'm going away.
September perhaps?

Brian

**Comment by Ankcorn** [comment]
Hi @mrbrianevans,

We have a meetup scheduled for the 25th of September, does that suit you?

**Comment by mrbrianevans** [comment]
Yes

**Comment by admataz** [comment]
Hey @mrbrianevans  thanks again for your talk the other night. Very appreciated and I enjoyed hearing some shouts for node's streaming module. 

I've uploaded the video to our youTube channel: https://youtu.be/lSFvtY_bpAc

Hopefully see you again soon at a future LNUG.

**Comment by mrbrianevans** [comment]
Thanks Adam. 

There's a little typo in the YouTube video name, just that my surname should be spelled "Evans" but its currently "Evens" in the title. It's spelt correctly in the video itself though, so all good there.

I'll have to plan a "part 2" talk on streams sometime - if you think there is interest in the topic? Could go a bit more in depth now that everyone has been introduced to streaming at least. Maybe one for 2025.

**Comment by admataz** [comment]
Apologies @mrbrianevans  - fixed now!

**Comment by admataz** [comment]
> I'll have to plan a "part 2" talk on streams sometime - if you think there is interest in the topic? Could go a bit more in depth now that everyone has been introduced to streaming at least. Maybe one for 2025.

Yes please! I think it's a great idea to have a follow up.
