### ISSUE TITLE
How to build an aerial photos website with Node.js, OpenLayers, SQL Server, .. and an aeroplane

### ISSUE THREAD

**Issue by neil9327** [lnug/speakers#219]
[Abstract of your talk]
I built a website that is like Google's StreetView, but up in the sky.
It is:
https://WingVista.org

With around 8000 360 photos taken from my flights in my plane all across the south of the UK, it is an elegent demonstration of OpenLayers javascript technology compiled with Node.js, SQL Server to process the data, Pannellum to display the images, and OpenStreetMap to provide the background maps.

In this talk I will explain how it all works, including a run-through of the source code.

[A bit about you, e.g. current job, twitter handle, etc.]
I'm a SQL Server Developer contractor and private pilot
https://www.linkedin.com/in/neilmsql/

- [**Yes**] I confirm that I will abide by the [Code of Conduct](https://lnug.org/code-of-conduct.html)

- [**Yes**] I confirm my talk is 20 mins long in total.

I attended the last meetup on July 31st, and it was suggested I could perhaps do a talk on my website.
I had been thinking about putting together a talk about it in any case, so in the last few days have recorded the following:
https://youtu.be/R1DPqe9nv4E

It is 50 minutes long, so I would have to cut it down a fair bit to fit in your 20/30-minutes slots.

Thanks

Neil Miller
neilm@millersql.com

**Comment by Ankcorn** [comment]
Hey @neil9327 

Thanks so much for submitting your talk! :) Would you be interested in talking at the next meetup - 27th of August?

I'd be happy to help you cut and shape the talk to fit within the 20 minutes.

**Comment by neil9327** [comment]
Yes 27th August works for me Thomas. It won't take long to cut the talk down to the 20 minutes - I wrote a script I can easily revise.

**Comment by Ankcorn** [comment]
Nice! :) I will get everything announced.

It would be great to have a little bit of an intro where you tell us about about you, your aircraft, sqlserver, and openlayers. It would be a mistake to assume anyone in the audience has any knowledge of these things. 

I'd also personally love to hear about the motivations behind making wingvista and some of the challenges you had along the way that you had to overcome. 

Hope those talk pointers help - thanks for making the video btw. It really helps

**Comment by Ankcorn** [comment]
Sorry @neil9327   I got my dates mixed up. It's wednesday the 28th of August. Is that still okay?

Really sorry for the confusion!!!

**Comment by neil9327** [comment]
Wednesday 28th August is fine - I've updated my diary to that. Let me know the time and venue when you have it.

Thanks for the tips. I'll re-version my talk to include all of those points, and probably do a second video to be sure it fits in the 20 minutes :)

**Comment by Ankcorn** [comment]
Venue and time will be same as last time. Cloudflares Office. 6.30pm pizza arrives but feel free to get there a little earlier if you need too :)

**Comment by admataz** [comment]
Hey @neil9327  - thanks for a great talk last night - I loved it - great application of the technology. Thanks for sharing. 

@Ankcorn can you send me the screen recording?

**Comment by admataz** [comment]
@Ankcorn  - here's a link to my dropbox: https://www.dropbox.com/request/RqCxwXSZ4GxNV36kA5oz

**Comment by admataz** [comment]
Hi @neil9327  - I've put the video together from your talk and it's now available on YouTube 
https://www.youtube.com/playlist?list=PLam_80-FY3vTTq1vV0vDmKCI0s0U3N4xw

Thank you again for contributing and sharing  - hopefully see you again soon!

**Comment by neil9327** [comment]
> Hi @neil9327 - I've put the video together from your talk and it's now available on YouTube https://www.youtube.com/playlist?list=PLam_80-FY3vTTq1vV0vDmKCI0s0U3N4xw
> 
> Thank you again for contributing and sharing - hopefully see you again soon!

Thanks for that Adam. Just watching it through now.
Looking forward to next month's event :)
