### ISSUE TITLE
Ross Kukulinski - What to expect when expecting IOJS

### ISSUE THREAD

**Issue by rosskukulinski** [lnug/speakers#22]
Hello!

I'm a co-organizer of BayNode and internet friends with @orliesaurus and @iancrowther. We've been kicking around the idea of sharing pre-recorded talks.

I'm going to be doing a ~20 minute talk at BayNode next week on the 1.0.0 release of [iojs](https://iojs.org/).  The talk will be recorded and I can send over the video, alternatively, I could live-stream the talk for y'all.

Overview:
* Why fork node?
* What new/broken IOJS 1.0.0
* Node/IOJS Compatibility
* Should I be scared / Should I deploy it?
* My take on what the future holds for the node community

**Comment by iancrowther** [comment]
Really pleased with this @rosskukulinski
