### ISSUE TITLE
Collaborative File Systems

### ISSUE THREAD

**Issue by benfoxall** [lnug/speakers#220]
Modern browsers have powerful apis for accessing local files.

I'd like to talk about those, and how we can combine them with peer-to-peer networking to share capabilities between devices and push edge compute further down to local devices.

topics: File System Access, CRDTs, Origin Private File System, WebRTC, Edge compute.

I'm Ben Foxall, I lead the Robot Web team at [Wayve](https://wayve.ai/).  👋  @benfoxall / [@benjaminbenben](https://twitter.com/benjaminbenben)

- [x] I confirm that I will abide by the [Code of Conduct](https://lnug.org/code-of-conduct.html)
- [x] I confirm my talk is 20 mins long in total.

**Comment by benfoxall** [comment]
👋  I had a really lovely time at my first LNUG last night, thanks for being so welcoming!

This topic is a little rough / in progress, but I'm really eager to share it and talk to people about it.

**Comment by Ankcorn** [comment]
Hi @benfoxall 

This is awesome!

Would you like to present at our meetup on the 25th of September?

**Comment by benfoxall** [comment]
@Ankcorn sure 🥳

**Comment by Ankcorn** [comment]
Amazing! <3 

I will get everything announced

**Comment by benfoxall** [comment]
Hey @Ankcorn, thanks for getting this organised. I'm looking forward to it!

I looks like my talk title has been changed on the [meetup page](https://www.meetup.com/london-nodejs/events/303316177/), would you be able to change to this (I've edited it to be somewhere between the two):

> Browser File Access APIs to Share Local Capabilities and Data Between Devices

I'd be happy to make other tweaks if you've feedback!

Also, from my bio could you remove ` and edge computing` from the end? (that's not so relevant for my role atm).

**Comment by benfoxall** [comment]
Hey, thanks a lot for having me along to speak last night!

You can find my slides here:
https://docs.google.com/presentation/d/1M7U8SuN-OmLri0EuzFuhKQgUXDi_l-bZolAKlkqz9gc/edit?usp=sharing

And some things I showed:
https://benjaminbenben.com/hex
https://benjaminbenben.com/ycode
https://benjaminbenben.com/opfs
https://prpc.netlify.app/

All source on my github repos:
https://github.com/benfoxall?tab=repositories

**Comment by admataz** [comment]
Hey @benfoxall  - thank you  again for your talk  - very enjoyable. 

I've put together the video and uploaded it to our channel - https://youtu.be/v919R5RuHK0

Look forward to seeing you again at the next meetup...  and sometime for Part 2 :)
