### ISSUE TITLE
Flo Servers are dead, long live the service

### ISSUE THREAD

**Issue by flomotlik** [lnug/speakers#24]
Short intro why the days of the server are numbered as our most basic building block and building on top of services is the future.

**Comment by iancrowther** [comment]
perfect - thanks

**Comment by basicallydan** [comment]
:+1: Sounds like a very Node-y talk :smile:

**Comment by flomotlik** [comment]
@basicallydan have to admit I'm not really on the Node side (the little that I get to code) but yeah pretty general topic anyway. With AWS Lambda being released interesting for everyone though I think
