### ISSUE TITLE
Benefits of using Convention over Configuration

### ISSUE THREAD

**Issue by Globegitter** [lnug/speakers#25]
Node/io.js and npm is now the most flourishing ecosystem with over 200 npm modules being published a day*. While this poses a lot of opportunities for us to work together and build better software, it also comes with problems we as developers have to face: Which package should I now choose? How do I use it in my app? What input does it expect? etc. Making a multitude of these simple decision drains a lot of our energy - more than you might even think initially. Imagine now `npm install` and you are ready to go. You installed your addon, you already know what to expect and it hooks itself up into your app.

This is the philosophy behind convention-over-configuration: having a standard we all work with to automate mundane decisions. So we can focus on making our software better.

*Source: http://www.modulecounts.com/

**Comment by iancrowther** [comment]
I understand where your coming from. 

I think if you can make the talk focus more on the msg eg "convention-over-config" and worry less about the tools this would be great.

my advise would be suggest the tools & frameworks but don't go into too heavily as you want to keep the entire audiences attention.

pencilled in for march :-)

**Comment by ifraixedes** [comment]
I agree with @iancrowther to focus on the message and tell the advantages and disadvantages and tell about your experience with Sane Stack however it could be another.

**Comment by Globegitter** [comment]
@iancrowther that is great to hear and a good point :). So if I keep most of the presentation generic and then at the end have a little showcase (in my head about 80:20 split) is that something that sounds like a good mix for the audience?

**Comment by iancrowther** [comment]
Seems reasonable to me.. 📢 do you know anyone who would be willing to voulenteer to record the session?

**Comment by Globegitter** [comment]
With session do you mean, just my talk, or all the talks? But did get someone from the office to volunteer.

**Comment by iancrowther** [comment]
I meant all the talks.  were looking for someone to take ownership of video recordings

**Comment by orliesaurus** [comment]
@globegitter can you edit ur talk text to be 1 paragraph of text only about what you decided to talk about without "hey" and stuff. Just the abstract plz

**Comment by Globegitter** [comment]
@iancrowther sorry for the delay - brought that up in the office today but the guy who suggested that we can film is sick, so can give you an update in the next few days.

@orliesaurus will do
