### ISSUE TITLE
Server mocking with canned

### ISSUE THREAD

**Issue by sideshowcoder** [lnug/speakers#26]
I've been frustrated with the complexity involved with just setting up a mock server so I wrote [canned](https://github.com/sideshowcoder/canned) sometime ago making faking a webserver just a matter of putting files in folders. This simple approach led to a whole bunch of usecase from 

- frontend development first, backend later
- mock server for testing
- performance testing for mobile apps without backend influence

I think some of this would make an interesting talk and maybe some people might even find a use for canned in their own work.

**Comment by iancrowther** [comment]
Ha, have built a few of these up myself! Yeah it's a nice and would be welcomed

**Comment by iancrowther** [comment]
Hi @sideshowcoder 

Can you make the 22nd April?

**Comment by sideshowcoder** [comment]
22nd works yes

**Comment by iancrowther** [comment]
@achingbrain came back to me moments before.. thanks for being flexible though

**Comment by orliesaurus** [comment]
Hey @sideshowcoder are you happy to present this month?

**Comment by sideshowcoder** [comment]
@orliesaurus yes I am :+1:
