### ISSUE TITLE
Progressive Enhancement Strategies

### ISSUE THREAD

**Issue by simonmcmanus** [lnug/speakers#27]
Advances in JavaScript are changing the way that we think about the web; it's no longer just a platform for information, but for complex interactions too.

As we race into the future, we risk losing some of the things that make the web so special.

In this talk I will outline why I believe progressive enhancement is still important. Demonstrating processes, techniques and architectures which provide the benefits without introducing an overhead.

**Comment by simonmcmanus** [comment]
This will be a very opinionated talk :)

**Comment by web-bert** [comment]
Sounds like a good one to me!

**Comment by tomcartwrightuk** [comment]
+1 for this. Sounds good

**Comment by jkbits1** [comment]
+1
