### ISSUE TITLE
The state of web asset pipelines and the description of a new pipeline that combines the best of all worlds.

### ISSUE THREAD

**Issue by ohjames** [lnug/speakers#29]
People soon realised that a task runner is not an asset pipeline, maybe sometime after the millionth spaghetti gruntfile was written. Along came gulp, the wonderful streaming pipeline, but the people saw that it was flawed, being built around `1:1` operations (disallowing nice n:1 stuff such as concatenation of streams together with their source maps).

Then came plumber, broccoli, gobble, and metalsmith, all with unique selling points yet all having drawbacks not found in grunt and/or gulp.

It was time for a new asset pipeline to be born out of the pain of trying to find the holy grail of asset pipelines. It was time to write it using functional reactive programming, ES6 and a geekgasm of buzz-words to seduce the JavaScript community. It was time for a bullshit sensationalised lnug talk abstract. Yes, it's time to sigh. [sighjs](https://github.com/sighjs/sigh).

In this talk I will describe the issues with existing asset pipelines (read: trash all the competition) and describe how sighjs improves upon the state of the art (read: gloriously inflate my ego).

This talk will last around 10 minutes long and it will be a little surreal. Here is [one of my other talks at HNN](https://vimeo.com/31535266j).

**Comment by orliesaurus** [comment]
YES!!

**Comment by iancrowther** [comment]
If you can make it 20 mins then I'm keen to see how this one unfolds.

**Comment by olizilla** [comment]
+1 for surrealism in tech

**Comment by nuisanceofcats** [comment]
@iancrowther Yeah it's about 20 minutes worth of material but I'm planning on rushing through it.

**Comment by orliesaurus** [comment]
Try not to rush it then please

**Comment by nuisanceofcats** [comment]
@iancrowther Could you schedule it for May, thanks!
@orliesaurus George Ornbo's talk started late and he had to rush but it made the talk even better I think - rushdown style.

**Comment by orliesaurus** [comment]
haha yeah but that wasn't because he wanted to, that's because we had no more time left :P Anyway we don't mind shorter talks, in fact we're gonna have lightning talks soon!

**Comment by nuisanceofcats** [comment]
@orliesaurus haha yeah I know he had to rush, I thought it might be cool to intentionally go fast though. Yet there's a lot of material to cover so a lightning talk might not be long enough.

I've already planned most of the talk, but I want to spend some time adding some even cooler stuff to `sigh` and working on the animations in the slides.

**Comment by iancrowther** [comment]
@nuisanceofcats get in touch with @simonmcmanus to see if your talks can complement each other at all.

https://github.com/lnug/speakers/issues/27

Do you prepare images? @simonmcmanus do you consume images etc..

**Comment by nuisanceofcats** [comment]
@iancrowther sigh asset pipelines can transform any type of file, including images. I'm planning on adding more specific API around dealing with binary data and caching files out to the fs (or a virtual/shared memory fs) when necessary.

**Comment by simonmcmanus** [comment]
@iancrowther @nuisanceofcats My talk will cover things like Duo (duojs.org) and browserify transforms. Both of which could be a part of an asset pipeline but I wont be covering those aspects in my talk. 

I could mention that asset pipelines will be discussed in more detail in the following talk and link them in that way.

**Comment by nuisanceofcats** [comment]
Duo is really inspiring and something I've looked at while writing sigh. One thing that concerns me is that it doesn't support source maps, we have a plan to support the same duo `require` syntax with a js/css transformation, that way you'll be able to benefit from that goodness together with incremental compilation and other asset pipeline goodness. Hopefully we'll be able to use some of the duo API, depends how they're exporting things.

**Comment by nuisanceofcats** [comment]
Essentially we want the asset pipeline to be able to automatically add your github `require` dependencies directly to your package.json as soon as the pipeline detects you've added them.

**Comment by nuisanceofcats** [comment]
Sorry for the noise, I deleted my previous comments in favour of pushing the github repository earlier than I had planned:

[sigh external](https://github.com/sighjs/sigh-external)

As you can see sigh overlaps with duo quite a lot!

**Comment by iancrowther** [comment]
It would be great if you're talks compliment each other, have a chat maybe if both of you list some topic points etc in your proposals.. 

its not mandatory but would help add some polish to the event

**Comment by simonmcmanus** [comment]
@nuisanceofcats - that is interesting, Duo definitely has some pain points and it looks like you might be  working in those areas.

**Comment by nuisanceofcats** [comment]
@simonmcmanus Yep I tried it a bunch and there were some aspects that I thought were pretty flawed and could be done much better. I think `sigh`+`sigh-external`'s approach will be better because:

1. More external repositories supported, npm/bower/github
2. Will maintain your package.json/bower.json so that requires without versions like `require("bower:package")` will be fixed for everyone who uses your repository in the future.
3. Won't have to type the same versions over and over again.
4. Source Maps.
5. Watches your files for changes with incremental rebuilds.

**Comment by iancrowther** [comment]
Apologies for the scheduling confusion

**Comment by ohjames** [comment]
Added some great new features recently! :)

**Comment by orliesaurus** [comment]
Are you happy to present this month @ohjames ?

**Comment by ohjames** [comment]
Yep :+1:
