### ISSUE TITLE
Guvnor: running your processes like a boss

### ISSUE THREAD

**Issue by achingbrain** [lnug/speakers#30]
[Guvnor](https://www.npmjs.com/package/guvnor) is a fully featured, multi user process manager for node.js/io.js that leans heavily on the Unix permissions model for security.  It's also got a neat web interface that monitors multiple hosts, reports live statistics about your application and lets you interact with it - debugging, monitoring resource usage, live logs, restarting, etc.

The talk will cover why the world needs another process manager, CLI usage, deploying apps from git repositories, cluster management, using the web interface and live coding a small app that uses the programmatic interface.

**Comment by iancrowther** [comment]
n-i-c-e

**Comment by iancrowther** [comment]
Hi @achingbrain,

Can you make the 22nd April?
