### ISSUE TITLE
Liwe, an open source remote control for WebApps

### ISSUE THREAD

**Issue by maxwellito** [lnug/speakers#31]
This is a project I've been working on for few months and I just released it on [github.com/liwe](https://github.com/liwe) (under MIT). It's a service to let web developers (frontend guys) to use smartphones as remote for their webapps. Of course it's built with NodeJS. But at the moment it look more like a prototype than a robust piece of code.

It won't be very techy, especially in front of NodeJS developers. The talk would be axed on two main points:

- Make a technology accessible to other developers. Like sockets (think about jQuery and PHP devs)
- Find contributors

I have absolutely no idea if this talk respect the idea of LNUG. I think I can hold 20 minutes demo included.

https://github.com/liwe
http://liwe.co

**Comment by ifraixedes** [comment]
The website looks pretty good.
I love the sentence "made with ~~love~~ a keyboard"

**Comment by orliesaurus** [comment]
amazing @maxwellito finally!!!

**Comment by iancrowther** [comment]
@maxwellito - I put you in next month to give you some time
