### ISSUE TITLE
OpenComponents as microservices in the front-end world

### ISSUE THREAD

**Issue by matteofigus** [lnug/speakers#32]
Writing front-end code today is very challenging when you have to be resilient and robust in a big corporation. Working on a website that involves dozens of engineers based in three different continents, I learned that the complexity lies not only within the code itself. Allowing people to develop new features and deploy the code multiple times a day, keeping it up and running, is hard to achieve: we want small teams to be independent and not to interfere each other, in order to be quick and happy, but we also want to optimise cooperation when it is needed.

In the front-end world components are very small units of code providing application functionality that are all connected in order to become a web-site.

During this talk I’m going to speak about how we tried to approach to components at OpenTable. After breaking our monolithic back-end into smaller parts, we tried to break the front-end into smaller parts too, called micro-sites. Then, following the SOA principles, we tried to elevate components as services, in order to make engineers able to create and consume them via clear and well-defined contracts and interfaces. This allowed us to put in place the infrastructure to optimise testing and to have hundreds of changes live every day without conflicts. The result is OpenComponents, a framework that we recently open-sourced.

References:
http://tech.opentable.co.uk/blog/2015/02/09/dismantling-the-monolith-microsites-at-opentable/
https://github.com/opentable/oc

**Comment by iancrowther** [comment]
We have an open slot on the 27th if your ready?

**Comment by matteofigus** [comment]
Yes, ok! Thanks!

**Comment by matteofigus** [comment]
gonna do a PR for the site ok?
