### ISSUE TITLE
Production browser-side npm

### ISSUE THREAD

**Issue by mikemaccana** [lnug/speakers#33]
Everything you need to take advantage of npm in your browser side code, and avoid the pitfalls! 

Including:

 - Building browser bundles with gulp and npm build -  and how they compare
 - How to identify the modules that contribute to bundle file size
 - Pros, cons and workarounds for the izs style 'no lib dir, everything is a module' coding style
 - Ensuring consistent versioning during deploys
 - How to include templates in your browserify bundles

Based on experiences in a real world, production, profitable application.

**Comment by iancrowther** [comment]
Superb

**Comment by orliesaurus** [comment]
thanks Mike!!

**Comment by mikemaccana** [comment]
Per @orliesaurus chat I've modified this to be more focused on full stack npm.

**Comment by iancrowther** [comment]
np
