### ISSUE TITLE
Blowing out the LAMP

### ISSUE THREAD

**Issue by hxoliverrumbelow** [lnug/speakers#34]
Holiday Extras, a times top 100 company, maintains a big online presence selling airport parking, travel insurance and overnight stays in hotels. We made over 4,000,000 bookings last year and our API serves around 35 requests/second - we aren't big big, but we're big enough to have to deal with 'big website' problems.

We've spent 3 years fully migrating our production traffic away from a 10 year old LAMP stack to a NodeJS API. I want to share our journey - the migration plan, the evolution of our NodeJS codebase from beginning to end, our biggest mistakes and our biggest victories.

**Comment by hpoom** [comment]
This is in response to a call for for speakers from both [Emily](https://twitter.com/emilyatk/status/603886621046497280) and a conversation with Orlando in Barcelona a couple of weeks back.

**Comment by iancrowther** [comment]
Thanks @hpoom, excellent proposal

**Comment by orliesaurus** [comment]
@hpoom @hxoliverrumbelow - is June a good month for ya?

**Comment by hxoliverrumbelow** [comment]
@orliesaurus I'm not sure when the June meetup is happening - is it the 24th?

**Comment by iancrowther** [comment]
yep 24th

**Comment by hxoliverrumbelow** [comment]
Sounds good :+1: I'm looking forward to it!

**Comment by orliesaurus** [comment]
okay then its happening!

**Comment by iancrowther** [comment]
@hxoliverrumbelow whats your email? I need to send you instructions on where to upload your video :-)

**Comment by iancrowther** [comment]
@hxoliverrumbelow https://gist.github.com/iancrowther/4a87404d5a115924ed10

**Comment by hxoliverrumbelow** [comment]
I have some bad news... The mac recorded the webcam instead of the screen :(

My email is [firstname].[lastname]@holidayextras.com

**Comment by iancrowther** [comment]
lol.. now worries

cc @johnnybridges
