### ISSUE TITLE
TypeScript will finally bring peace to your troubled soul

### ISSUE THREAD

**Issue by pimterry** [lnug/speakers#35]
You've heard of TypeScript, but you're not sure if it's a good idea, and you've never really seen it in action. TypeScript is powerful though, rapidly gaining momentum, and has a lot more to offer than just JS + classes. Let's take a proper look.

In this talk, we'll dig a bit deeper and play around with some of the more interesting features TypeScript gives you. We'll walk through the extras that TypeScript provides and how they'll solve your every woe, learn a bit about where the types come in and why you care, and see how exactly you might put it into action on your next Node project.

**Comment by orliesaurus** [comment]
@pimterry remove the stuff below the line and put it as a sperate comment plz <3
also, July 22 and August 26 are the scheduled days for LNUGs

**Comment by pimterry** [comment]
Original below-the-line text:

It's me again! I've been doing a bunch of TypeScript recently, and I'd quite like to show everybody else a bit more about it, because it's actually pretty great. Needs to be July or August, as I'm not going to be in London from September. When are the July/August events? Do you still have any free speaker slots for those?

**Comment by pimterry** [comment]
August 26 would work nicely for me.

**Comment by orliesaurus** [comment]
Okay let's keep it to that for now :)

**Comment by iancrowther** [comment]
We have all the dates confirmed till 2016

**Comment by orliesaurus** [comment]
Yeah I know: but he's leaving London in September :p (just like me)

**Comment by iancrowther** [comment]
blimey, everyone is getting out of town!

**Comment by iancrowther** [comment]
@pimterry your on the August roster

**Comment by pimterry** [comment]
Great to hear, thanks Ian, I'll see you there.
