### ISSUE TITLE
Mikeal Rogers - Node Foundation Q&A

### ISSUE THREAD

**Issue by iancrowther** [lnug/speakers#39]
The following form needs distributing:

https://docs.google.com/forms/d/1XvqIY3OroqUaxQPlfIc1VsCKzsbg1VbzbXrD4IHlx3w/viewform

**Comment by web-bert** [comment]
twitter username needed

**Comment by web-bert** [comment]
description for the talk needed

**Comment by web-bert** [comment]
github username for avatar

**Comment by simonmcmanus** [comment]
Hi @web-bert  - I added this to the website last night,  did you need the username/avatar for anything else?

**Comment by web-bert** [comment]
No I was going to update the site, so no need for it now :+1:
