### ISSUE TITLE
Joe Nash - Tokenization

### ISSUE THREAD

**Issue by iancrowther** [lnug/speakers#40]
Description to follow

**Comment by jdNash** [comment]
Title: Insert Token: Immersive UX with Tokenization

Users of our apps and products yearn to be immersed; but so often, the worlds we build with software show surprising seams, shattering immersion for our users. In this talk, we'll look at the magic of tokenization, and how it can transform the UX of your application.

**Comment by iancrowther** [comment]
Thanks @jdNash
