### ISSUE TITLE
How Waffle.io separated its API from its core web app

### ISSUE THREAD

**Issue by burtonjc** [lnug/speakers#41]
At Waffle.io, we recently built a public API to gain access to Waffle's data (in private beta now). We knew we wanted the API to be deployed, scaled, and monitored separately from our core app. We also wanted the app to use the same API we were providing to our users. Carving the API out as its own service consumed by our app provided some interesting challenges and produced some surprising benefits. This talk will describe the design we came up with, the challenges we faced, and the largely unexpected benefits we received.

**Comment by malditogeek** [comment]
As a daily Waffle user I would love to see this talk! 

:+1:

Mauro.

**Comment by iancrowther** [comment]
ah awesome.. glad to have you onboard

**Comment by burtonjc** [comment]
@iancrowther, thanks for accepting! I will most likely be out of the country on the 26th. Is there any chance we can bump this back to the next session?

**Comment by iancrowther** [comment]
September?

**Comment by burtonjc** [comment]
That would work great, thank you!

**Comment by iancrowther** [comment]
Sold

**Comment by admataz** [comment]
hi @burtonjc  - just want to confirm with you before I prepare the mailer - you're all good to go on Sept 23rd?

**Comment by burtonjc** [comment]
I am! What is your preferred remote presentation method, Google Hangouts?

**Comment by iancrowther** [comment]
fancy trying yodlr? hangouts and skype have been poor quality recently

you need bandwith and a good mic for the presenter with skype and hangouts

**Comment by iancrowther** [comment]
can test on saturday avo?

**Comment by burtonjc** [comment]
Yeah, I'm up for trying yodlr. Do you mean this Saturday or the 19th?

**Comment by burtonjc** [comment]
@iancrowther, been playing around with yodlr, seems like an awesome tool! How do I join the meeting tomorrow? Should I just join the yodlr room and go from there? If so, can I get an invite to the room?

**Comment by burtonjc** [comment]
Also, can people join remotely? The rest of the Waffle.io team is interested in watching.

**Comment by iancrowther** [comment]
ill find out, we have an lnug room

**Comment by iancrowther** [comment]
i did mean the 19th btw, but completely forgot :-)

**Comment by iancrowther** [comment]
am testing now

**Comment by burtonjc** [comment]
Cool, no worries.

**Comment by iancrowther** [comment]
https://rooms.getyodlr.com/lnug
