### ISSUE TITLE
Rethinking backend with webtasks

### ISSUE THREAD

**Issue by tjanczuk** [lnug/speakers#42]
You are writing a mobile or HTML5 web application that needs just a little bit of a backend. Maybe you want to access MongoDB, send an SMS, or an e-mail. Do you really need to host your own Node.js service to run this small snippet of backend logic?

In this talk I will take a hard look at the role of the backend in modern applications. I will introduce the concept of a [webtask](https://webtask.io) - a lightweight representation of backend logic that can safely be embedded in a client application. I will show how you can use modern container technologies based on CoreOS and Docker to build a generic, multi-tenant runtime for securely executing webtasks directly from a mobile or HTML5 application. You don’t need a backend to run backend code.

This talk is based on lessons learned when building the Node.js sandboxing technology for internal use in our core operations at Auth0.

Find out more:
[Webtask concepts](http://tomasz.janczuk.org/2015/04/rethinking-backend-with-webtasks.html)
[Webtask CLI](https://github.com/auth0/wt-cli)
[Webtask playground](https://webtask.io)
[Webtask technology](https://medium.com/aws-activate-startup-blog/sandboxing-code-in-the-era-of-containers-294edb3a674)

**Comment by iancrowther** [comment]
Video Talk

**Comment by tjanczuk** [comment]
@iancrowther how does the technical side of this talk look like? How/when do I join and present?

**Comment by iancrowther** [comment]
We can Skype or use any webrtc option like yodlr

**Comment by tjanczuk** [comment]
So the idea is we connect, I share my screen, and talk to it, or do you need my slides beforehand?

**Comment by iancrowther** [comment]
yep, nice and simple.  no need for slides in advance although it would be great for you to tweet the url for them after the talk
