### ISSUE TITLE
Load-testing for fun and profit

### ISSUE THREAD

**Issue by hassy** [lnug/speakers#44]
This talk will (briefly) outline why load-testing should be a part of your testing activities and then dive into an overview of tooling and strategies & processes to get the most out of it when working on a production system. We'll also explore how load-testing can improve our understanding of both our own code and components that our code depends on.

**Comment by hassy** [comment]
Examples will use [Minigun](https://github.com/artilleryio/minigun), the load-testing tool I'm working on, but I'll talk about other options like JMeter and Grinder too.

**Comment by orliesaurus** [comment]
September?

**Comment by hassy** [comment]
@orliesaurus sure :)

**Comment by iancrowther** [comment]
ah hassy, is this what I think it is?? woohoo

**Comment by admataz** [comment]
@hassy  - just confirming before I do the mailer - you're on for 23rd Sept?

**Comment by hassy** [comment]
@admataz yes!

**Comment by iancrowther** [comment]
ola! @hassy 

do you have screen recording software? if not can you full-screen record with quicktime for the youtube vids

**Comment by iancrowther** [comment]
you'll be on 2nd

**Comment by hassy** [comment]
I'll use quicktime 👍

**Comment by hassy** [comment]
@iancrowther you'll have projector cables right? otherwise i'll need to source one

**Comment by iancrowther** [comment]
hdmi
