### ISSUE TITLE
2FA, WTF?

### ISSUE THREAD

**Issue by philnash** [lnug/speakers#45]
Everyone is hacking everything. Everything is vulnerable. Your site, your users, even you. Are you worried about this? You should be!

Don't worry, I'm not trying to scare you (that much). We have plenty of safeguards against attempts on our applications' user data. We all (hopefully) recognise Two Factor Auth as one of those safeguards, but what actually goes on under the hood of 2FA?

We'll take a look into generating one time passwords in JavaScript, implementing 2FA in Node.js applications and the only real life compelling use case for QR codes. Together, we'll make the web a more secure place.

**Comment by ifraixedes** [comment]
Security is one topic that I like to hear

**Comment by iancrowther** [comment]
free for september?

**Comment by philnash** [comment]
Ah, I'm not in the country on the 23rd, can't make that I'm afraid. Is the October event planned for the 28th October? It would really help me if it could be 21st and I could speak then, as I have a conference I am giving the talk at on the 27th-28th. Sorry to be a pain!

**Comment by iancrowther** [comment]
November 25th it is then..

**Comment by iancrowther** [comment]
Please can you confirm your happy with November?

**Comment by philnash** [comment]
Sorry @iancrowther, I can't make that either! Guess it'll have to be next year, if that's ok?

**Comment by iancrowther** [comment]
Argh!! ok np

**Comment by philnash** [comment]
Give me a suggested date and I'll block it off now :)

**Comment by iancrowther** [comment]
@philnash new date proposed :-)

**Comment by philnash** [comment]
It's in the calendar. Let's lock it in!

**Comment by iancrowther** [comment]
locked! See you in 2016!
