### ISSUE TITLE
The Miracle of Generators

### ISSUE THREAD

**Issue by bodil** [lnug/speakers#46]
The ECMAScript 2015 specification introduced *iterators*, which generalise iteration over common data structures, as well as providing an interface for allowing you to iterate over any custom data structures using common language constructs. ES2015 also introduced *generator functions*, which make writing arbitrary iterators a lot easier and less boilerplatey.

But generators aren't just for making simple iterators over data structures. Because they're bidirectional—they don't only produce output, they can also take input—they're actually *coroutines*, which means there's no end to the sort of fun you can apply them to. We're going to explore how we can use them to make asynchronous programming in JavaScript a lot more elegant—to chart a path out of callback hell. And then we're going to take a look at what we've really discovered: one of the most fearsome mysteries of computer science, suddenly laid bare before us.

**Comment by bodil** [comment]
Be warned, this is a 40 minute talk.

**Comment by jkbits1** [comment]
@bodil I'm keen to hear this

**Comment by malditogeek** [comment]
Sounds brilliant, I played a bit with Koa and would love hear more about generators :+1:

**Comment by olizilla** [comment]
Very much :+1:

**Comment by iancrowther** [comment]
Are you ok for September 23rd?

**Comment by bodil** [comment]
Definitely.

**Comment by iancrowther** [comment]
Your on the roster, really looking forward to this one.  We have a max speaking slot of 30 mins so if you could condense the 40 mins and push q's onto gitter, that would help us keep the venue happy.

w00t

**Comment by bodil** [comment]
I'd have to cut the introduction and assume people know their iterators, if so, but I think that wouldn't have a huge impact on the quality of the talk.

**Comment by iancrowther** [comment]
the audience is very technical so its safe to assume they are up to date.

**Comment by iancrowther** [comment]
@bodil do you want to go on 2nr or 3rd?

**Comment by bodil** [comment]
3rd, for preference.

**Comment by iancrowther** [comment]
done.. do you have screen recording software?  if not can you full-screen record via quicktime for the youtube vids

**Comment by bodil** [comment]
I'm on a Chromebook, so it'll be... experimental... but we can give it a go. There is software for recording browser tabs, which is what I'll be presenting from, so in theory it should work.

**Comment by iancrowther** [comment]
ok cool - good job I mentioned it then hey :-)
