### ISSUE TITLE
Libraries.io beta

### ISSUE THREAD

**Issue by simonmcmanus** [lnug/speakers#47]
Description: 

```
Almost everyone uses and depends on open source software libraries these days, especially with the rise in popularity of NPM, but with nearly 200,000 libraries, how do you know which ones are worth using?

In this talk, Andrew Nesbitt will outline his solution to this problem with Libraries.io, which attempts to index all the world's open source software libraries and provide helpful ways of exploring the data and finding the best libraries for you to depend upon in your projects.

Some of the topics we'll touch on include: 

- What makes a good library
- How to make your open source libraries more user friendly
- Dependency management with npm, bower and more 
- Exploring open source big data to find hidden gems
```

**Comment by iancrowther** [comment]
@andrew - pain in the ass as this may seem, can you post a proposal? otherwise the automated tools will add @simonmcmanus as the speaker

**Comment by simonmcmanus** [comment]
As the issue is assigned to @andrew it should pick that up. 

If you could add a description will be v helpful. 

Thanks

**Comment by andrew** [comment]
@simonmcmanus I did edit and add a description to the first comment

**Comment by gwenau** [comment]
Hi all,

Unfortunately, I could not secure the URL
http://attending.io/events/lnug-september-2015 from the attending.io site
so this month's event is on URL
http://attending.io/events/lnug-september-2015-07d52f57-a7a3-4d4f-8642-2f4d66231200.
It has been created with the @LNUGorg twitter handle so anyone in the team
should be able to update information on it.

Cheers,

Gwen

**Comment by iancrowther** [comment]
@simonmcmanus - ah nice, is that in a readme anywhere? if not can it be..

**Comment by iancrowther** [comment]
@simonmcmanus - is this to be closed or rescheduled?

**Comment by iancrowther** [comment]
@andrew - would love to see this talk btw..
