### ISSUE TITLE
White water streams

### ISSUE THREAD

**Issue by tomgco** [lnug/speakers#48]
We use streams on a daily basis when handling data with our Node.js applications, but how do they work, and more importantly, how do we keep them efficient and performant?

This talk focus mainly on analysing applications that utilises streaming data, identifying bottlenecks and making improvements. Be wow’ed by Flame{graphs,charts}, awed by benchmarks and take away some tips in writing decent stream implementations.

**Comment by iancrowther** [comment]
superb
