### ISSUE TITLE
Graph databases - A holy crap moment!

### ISSUE THREAD

**Issue by adrianblynch** [lnug/speakers#50]
I don't often get blindsided by a new technology but investigating graph databases for a problem I'm trying to solve lately made me exclaim "Holy crap!"

When you're stuck in a relational world you find ways to make everything fit. We've all learnt the lesson that other types of databases are better suited for certain problems, be it document store, key-value or column based. Graph databases on the other hand have been on the peripheral for me and no doubt many others. Even after reading Seven Databases in Seven Weeks, I still didn't quite get the point of graph DBs.

Since looking into them, I now see that they could well nail down a lot of problems we all encounter and I think I'd like to talk about what we're using OrientDB for and highlight the potential they have in future development.

**Comment by jkbits1** [comment]
I'd be interested to hear more about graph databases and how people are finding them in actual use

**Comment by iancrowther** [comment]
@adrianblynch - Please can you do October

**Comment by adrianblynch** [comment]
Nooooo. Way too busy at the moment. @clarkie already hounding me for Oct or November! Is there a December one planned?

**Comment by iancrowther** [comment]
November is booked up now and we dont have an event in December.

October is the slot we need to fill ;-)

Failing that were back online in January 2016

**Comment by adrianblynch** [comment]
I'm free in the New Year :dancers:

I'd do it sooner but I won't prepare in time.

**Comment by iancrowther** [comment]
totally understand.  looking forward to it

**Comment by iancrowther** [comment]
@adrianblynch your scheduled for Jan, can you confirm?

**Comment by iancrowther** [comment]
@adrianblynch bump

**Comment by iancrowther** [comment]
Moved talk to Feb

**Comment by iancrowther** [comment]
@adrianblynch still planning to do this talk?

**Comment by iancrowther** [comment]
@adrianblynch pls confirm your happt to procees?

**Comment by admataz** [comment]
Hi @iancrowther @adrianblynch  
I'm putting the newsletter together - is this talk confirmed? It's next week.

**Comment by adrianblynch** [comment]
As much as I'd love to do this, I just don't have the time at the moment.

**Comment by iancrowther** [comment]
no worries, thanks for letting us know
