### ISSUE TITLE
Flux to Redux, Thinking with Data

### ISSUE THREAD

**Issue by bananaoomarang** [lnug/speakers#51]
Flux is one of the newer cool kids on the block, but it has it's fair share of problems. With all of the different implementations fighting for recognition, to first time users and abusers it can seem overly complicated.

Redux is one Flux framework which has gained a lot of traction recently, thanks to its novel take on the architecture (vastly simpler than Facebooks sample implementation, for instance) and neat debugging features.

This talk can show the differences between Redux's approach and more 'traditional' Flux architectures, running over its benefits for developers. It will also briefly explain the difference between Flux applications and other MVC implementations, for anyone curious and unfamiliar.

**Comment by clarkie** [comment]
+1 

Can you do the 28th October?

**Comment by tomgco** [comment]
Would love to hear this Milo! :dancer:

**Comment by bananaoomarang** [comment]
Yup, 28th of October should work out fine. Will pencil it in my diary.

**Comment by iancrowther** [comment]
aaaaaahhhhhh @bananaoomarang awesome :-)  I saw your article, will be fantastic to see you back on stage... 

oh thats a yes btw.

**Comment by bananaoomarang** [comment]
Awesome, will see you guys then :)
