### ISSUE TITLE
A javascript to c++ transpiler!

### ISSUE THREAD

**Issue by fabiosantoscode** [lnug/speakers#52]
A talk about an in-development javascript to c++ transpiler which currently kind of works and implements closures, numbers, objects, functions and strings.

Watch it compile and run hello world, and beat node in an EPIC FIB() BENCHMARK!

Be compelled by the power of tern.js to figure out what you think you're actually writing!

**Comment by tomgco** [comment]
+1 this sounds great!

**Comment by iancrowther** [comment]
yeah im keen as mustard for this talk

**Comment by fabiosantoscode** [comment]
@iancrowther can this issue be updated as per the new schedule we talked about?

**Comment by iancrowther** [comment]
@fabiosantoscode ok for November?

**Comment by fabiosantoscode** [comment]
Yes sir!

**Comment by iancrowther** [comment]
@fabiosantoscode your on.. welcome aboard :+1:
