### ISSUE TITLE
Going cross-platform with React: ~1 codebase, 3 platforms

### ISSUE THREAD

**Issue by HugoDF** [lnug/speakers#53]
What's the fastest way to ship a Web, iOS and Android app?

React Native goes beyond making native apps with web technology. You use javascript (granted that's a web technology) to make a fully fledged React app, using native components.

It's more than leveraging the power of the (state) => (UI) mapping of React. It's about code reuse. Being this DRY hurts. All the high-level logic is portable and you have **one** single codebase for all three target platforms. 

All of this is free, as long as you embrace React.

**Comment by iancrowther** [comment]
Many thanks for this, looking forward to then new year event

**Comment by HugoDF** [comment]
@iancrowther that would be great thanks, if you needed me to, I could also do November ;) look forward to catching up tomorrow

**Comment by iancrowther** [comment]
hey @HugoDF november is fully loaded now, but thanks for the offer
