### ISSUE TITLE
Scaling Node.js using Docker

### ISSUE THREAD

**Issue by BenHall** [lnug/speakers#54]
With great load comes great scaling responsibility. If we need to scale then hopefully it means we're doing something right. The problem is how to scale without increasing complexity and re-writing the application.

In this talk, Ben will discuss how he scales Katacoda.com, an online learning platform for developers. Ben will show how to deploy Node.js applications with Docker. Once deployed, Ben will highlight how to scale the processes and take advantage of container based deployments.

**Comment by jkbits1** [comment]
Fantastic, looking forward to this one!

**Comment by jkbits1** [comment]
@BenHall this sounds great, any chance it would be ready for november 25?

**Comment by BenHall** [comment]
Yes that should be OK

**Comment by jkbits1** [comment]
brilliant, it's been added to the schedule !

**Comment by iancrowther** [comment]
ok now it has!
