### ISSUE TITLE
How to contribute to the LNUG website

### ISSUE THREAD

**Issue by iancrowther** [lnug/speakers#56]
The LNUG websiet is undergoing a major overhaul.  @iancrowther & @simonmcmanus would like to give an architectual overview, onboard people and highlight the roadmap

**Comment by admataz** [comment]
Yes! I think it would be a great way to get people involved in the ongoings of LNUG, and expanding/improving as we go

**Comment by simonmcmanus** [comment]
This is 8 days before EnahnceConf. Can we do month before, or ideally afterwards?

**Comment by iancrowther** [comment]
@simonmcmanus ^^

**Comment by admataz** [comment]
@simonmcmanus  - are you still up for this? I think it would be good - you can reopen if you think there's a talk still in this
