### ISSUE TITLE
NodeJS Supercomputing?!

### ISSUE THREAD

**Issue by hxoliverrumbelow** [lnug/speakers#58]
Join me in a wild adventure to take a computationally heavy single-use NodeJS application and automagically scale it across many cores and many servers in the hunt for lazy performance. Disclaimer: This is all for fun, games and science.

**Comment by iancrowther** [comment]
Hi @hxoliverrumbelow, 

Was great to see you at the event last night, I know its not an easy location for you!

"This is all for fun, games and science" - We'll you sold me right there!

**Comment by hxoliverrumbelow** [comment]
Thanks, it was good to talk to various people :+1: I left fairly sharpish after 9pm and got back around 11pm - I'm going to look into a later train so I can hang around for a bit longer next time.

**Comment by iancrowther** [comment]
hmm fancy doing Jan after all?

**Comment by hxoliverrumbelow** [comment]
Sure, sounds great :+1:

**Comment by iancrowther** [comment]
@hxoliverrumbelow - still ok for Jan? I dbl booked the last slot!

**Comment by hxoliverrumbelow** [comment]
Yep, absolutely

**Comment by iancrowther** [comment]
:+1:
