### ISSUE TITLE
Shotguns and Scalpels: Cheerio and Casper at scale

### ISSUE THREAD

**Issue by mikemaccana** [lnug/speakers#62]
Two very different techniques to get Other People's Data. Cheerio to make the easy stuff easy, and Casper to make the hard stuff possible. Casper is complex: this talk makes it painless.

**Comment by mikemaccana** [comment]
This is a 10-15 minute super fast talk. Cheerio to make the easy stuff easy, and Casper to make the hard stuff possible. Casper is complex: this talk makes it painless.

**Comment by simonmcmanus** [comment]
I would love to hear this talk :)

**Comment by iancrowther** [comment]
@mikemaccana there is only 1 condition, Mr Oizo **must** make an appearance in the majority of the slides..

I would not be opposed to a small sample from the track either!

**Comment by mikemaccana** [comment]
On it. What date's good?
![screen shot 2016-01-22 at 15 32 29](https://cloud.githubusercontent.com/assets/172594/12514865/6702f1de-c11d-11e5-9503-b7dafd858cb9.png)

**Comment by iancrowther** [comment]
Just checking...

![image](https://cloud.githubusercontent.com/assets/76060/12516266/815837cc-c124-11e5-832c-0219371c7727.png)

It's looking like April

**Comment by mikemaccana** [comment]
April is rad! What date?

**Comment by jkbits1** [comment]
:+1: :tada: 

It'll be April 27, we're always the fourth Wednesday.

**Comment by iancrowther** [comment]
@mikemaccana just locking this in

**Comment by mikemaccana** [comment]
👍 Looking forward to it.

**Comment by admataz** [comment]
@mikemaccana:  - what size LNUG tshirt do you want?

**Comment by mikemaccana** [comment]
Large! 
Nice timing, currently churning through talk!

Sent from Outlook Mobile




On Tue, Apr 26, 2016 at 2:51 AM -0700, "Adam Davis" <notifications@github.com> wrote:












@mikemaccana:  - what size LNUG tshirt do you want?
