### ISSUE TITLE
I've got swagger. Have you?

### ISSUE THREAD

**Issue by tanzim** [lnug/speakers#63]
OpenAPI Specification, formerly known as Swagger is a well established standard for defining REST API interfaces. In this talk I'd like to quickly go over Swagger, how you can integrate it with node.js and a few best practices that goes a long way to deliver robust enterprise class API service

Additional links:
- https://github.com/OAI/OpenAPI-Specification
- https://github.com/swagger-api/swagger-node

**Comment by iancrowther** [comment]
Hey @tanzim 

I've been looking at this recently so would be interested in the talk.

**Comment by iancrowther** [comment]
We currently have an open slot next week in and in April.  When would you think this talk could be ready?

**Comment by iancrowther** [comment]
ok ive not got my bearings and proposed may for this talk

**Comment by tanzim** [comment]
Sounds good.

**Comment by iancrowther** [comment]
can I confirm this?

**Comment by admataz** [comment]
Hi @tanzim  - I would love to May's talks before Wednesday's meetup - can you confirm?

**Comment by tanzim** [comment]
Sorry for the delayed response. I'm out of the country 😅. Yes, you can confirm the talk for May. 
Thanks,
T

**Comment by iancrowther** [comment]
Locked in

**Comment by tanzim** [comment]
@iancrowther @admataz 
Gents,
I really do apologise for the last minute notice, but it looks like that I won't be able to present on 25th. I've been caught in an unexpected hard deadline and I had plans to finish off the slides over the weekend, which was a miserable failure and it's clear that I won't be able to get them finished either by tomorrows event.  

I'd have monkey patched something but it's unlikely that I would even make it to the event, so there's no point of making false promises.  

Apologies once again.

**Comment by admataz** [comment]
Thanks for letting us know @tanzim  - we'll try make a plan and hopefully get you in another month

**Comment by clarkie** [comment]
@tanzim I'm not sure we should have closed this. Are you interested in rescheduling?

**Comment by tanzim** [comment]
@clarkie Yup very much interested in rescheduling. I will get back with a date. Stay tuned.

**Comment by admataz** [comment]
@tanzim how are you fixed for August 24th?

**Comment by tanzim** [comment]
@admataz Yikes, looks like once again I'm not available for the 24th. I can commit to September if that's okay? And I shall make sure this time that my calendar is free. Sorry about that.

**Comment by admataz** [comment]
@tanzim  - thanks...

**Comment by clarkie** [comment]
Hi @tanzim, just checking you're 100% for September?

**Comment by admataz** [comment]
bump! @tanzim

**Comment by tanzim** [comment]
Yup on for Septembre @clarkie @admataz :)

**Comment by admataz** [comment]
cool! excellent - confirmed

**Comment by admataz** [comment]
Hi @tanzim 
Just confirming you're all OK for Wednesday? Is there anything you need for your talk? Just to be safe - if you have an adaptor for your laptop to plug in to the projector, can you bring it along?

See you there! I will be there  at Makers from about 5:30pm.

**Comment by tanzim** [comment]
@admataz I'm good for Wednesday. I use and Mac and last time around didn't need to use any adapter, IIRC I just used HDMI to hook up to the screen. Hopefully that's remained the same?

**Comment by jkbits1** [comment]
it's the same setup as before, hdmi is fine :+1:

**Comment by clarkie** [comment]
@tanzim are you here? Please make yourself known to someone at the front. Thanks
