### ISSUE TITLE
Computing at scale. Why you should already be using AWS Lambda

### ISSUE THREAD

**Issue by tanzim** [lnug/speakers#64]
Node.js is awesome for I/O. But what happens when you need to use CPU bound operations? Or what happens when you don't want to bog down your server with lots of long running tasks? Lambda from AWS gives you just the medicine to solve these headaches and more. Join me for a quick overview and how we solved some real world problems elegantly leveraging the power of Lambda

Additional links:

http://aws.amazon.com/documentation/lambda

**Comment by tanzim** [comment]
@iancrowther 
Sadly, I'm away from 22nd to 29th April and I was wondering if it could be moved to May or later please?
Thank you :)

**Comment by iancrowther** [comment]
how about March?

**Comment by tanzim** [comment]
Wanted to avoid March as we have a product release slated for beginning of March. Having said that, I will accept.

**Comment by iancrowther** [comment]
superb

**Comment by iancrowther** [comment]
May 25th?

**Comment by iancrowther** [comment]
oh hold on.. i miss read...

so you can do next week?

**Comment by iancrowther** [comment]
i got confused with you having two proposals.. ignore me
