### ISSUE TITLE
Isomorphic apps with Hapi.js and React

### ISSUE THREAD

**Issue by lucamezzalira** [lnug/speakers#65]
In this talk I'd like to show a quick example on how to create an isomorphic application with Hapi.js and React, in particular focusing why Hapi.js allows to create configurable and well organised code and how to use React as views for your isomorphic application.

**Speaker**: Luca Mezzalira
**Linkedin**: https://uk.linkedin.com/in/lucamezzalira
**Twitter**: https://twitter.com/lucamezzalira

**Comment by iancrowther** [comment]
@lucamezzalira march ok?

**Comment by lucamezzalira** [comment]
May is better if it's not a problem

**Comment by iancrowther** [comment]
new proposed date - pls confirm

**Comment by lucamezzalira** [comment]
cool I confirm that!
thanks so much :D

**Comment by lucamezzalira** [comment]
Sorry my bad... just bumbped in my mind that day I have the meetup of my community: http://www.meetup.com/London-JavaScript-Community/events/228450662/

**Comment by iancrowther** [comment]
can yo ureview the milestones and see which date works for you

**Comment by lucamezzalira** [comment]
can we do it in June?

**Comment by iancrowther** [comment]
June should be fine
