### ISSUE TITLE
NodeJS a professional case study

### ISSUE THREAD

**Issue by bernardbaker** [lnug/speakers#67]
Hiring people from these events work! And small NodeJS apps that get things done.

When I came to a previous event I was asked if I was hiring... I was, and found a great candidate and now a new team member for our development team.

She will describe her working day and the different things she has been doing with us at Sky Works since she started.

After that I will take you through the build and development of a small NodeJS app which gets a single task done well. We use it to update obfuscated JavaScript files.

I'll explain the project/technical/functional brief and then take you through the development in steps of progress, there will be live coding of parts of the application and an explanation of how the libraries used work.

At the end I will present the live application which is hosted on Heroku.

Twitter: @bernibear2000
Github: bernardbaker

**Comment by admataz** [comment]
Thanks @bernardbaker for your proposal

> I would like to present NodeJS by means of it successful application to a business case study. It was applied to a project successfully and then utilised further to build a maintenance utility for the project.

This sounds very generic in its current form. Could you be more specific about your project and talk - maybe what was interesting about your use of node, or what  you did that was original, creative or insightful - and  describe the angle that would make it an interesting talk for attendees?

You can refer to previous speakers' proposals for some idea: https://github.com/lnug/speakers/issues?q=is%3Aissue+is%3Aclosed+label%3A%22Accepted+%26+Scheduled%22

This will help us to be able to best assess and schedule a talk 
Thanks!

**Comment by jkbits1** [comment]
This talk proposal related to a discussion with @bernardbaker at the recent Nodeschool London.

There is definitely a good talk here, with some interesting underlying details and code. It might be a lightning talk rather than a main talk, as regards length.

We've talked recently about giving support to coders who are both relatively new to Node and perhaps also to public speaking. This would be an ideal opportunity to put those ideas into practice.

**Comment by bernardbaker** [comment]
Hi all, the project utilized Node to automate common tasks and challenges that I came up against in the development. For example: seeing changes in my code in real time, linting, re-writing file contents, combing source files, making zip files for distribution and obfuscating project source files. What was interesting was the speed at which a person with little or no experience can get set up in Node and produce production ready solutions in little or no time at all.

**Comment by admataz** [comment]
Great - sounds like it could be really interesting and practical talk on node for tooling - can we give it a descriptive more catchy title that will make people sit up and listen? 

random suggestion, I'm sure you can do better:

> "A toolbox full of JS: practical ways we use node to get the job done" 

and follow up with a promise of a a walkthrough the setup/script and maybe a live demo of one or two of your favourite node.js tools you made/used in this process?

**Comment by clarkie** [comment]
I'm with @admataz on this. I enjoy the 'new shiny' talks but my favourites are the ones where I go into work the following day and actually use something from the night before.

**Comment by iancrowther** [comment]
nice shaping.

**Comment by iancrowther** [comment]
@bernardbaker march ok?

**Comment by jkbits1** [comment]
@bernardbaker Here are some specific ideas we discussed about supporting our speakers
https://github.com/lnug/planning/issues/91

**Comment by iancrowther** [comment]
@bernardbaker can you confirm your good for march?

**Comment by admataz** [comment]
Hi @iancrowther @bernardbaker 
I'm putting the newsletter together - is this talk confirmed? It's next week.

**Comment by iancrowther** [comment]
@bernardbaker should I close this?

**Comment by admataz** [comment]
HI @bernardbaker  - I hope all is well with you.... I'm closing this just to keep things in order - but let me know if you are still keen to speak - and we can reopen and get you on the schedule.

**Comment by bernardbaker** [comment]
Hi, I would like to do a talk which is a little different...

When I came to a previous event I was asked if I was hiring... I was, and found a great candidate and now a new team member for our development team.

I would like to affirm with the audience that people do hire through your events. And then let her describe what she has been doing in her new role.

After that I would like to take the audience on a walk through of building an application. An application that we currently use in the studio to process obfuscated JavaScript files.

I'll explain the project/technical/functional brief and then take them through the development in steps of progress, doing a little coding and explaining how the libraries work as I go along. I think the talk will be about 30-40 mins. Hope that it doesn't take more than an hour to go through it all.

At the end I will present the live application which is hosted on Heroku.

Regards,
Bernard

**Comment by admataz** [comment]
hi @bernardbaker 
Sounds good - maybe we can split your talk into 2 and have a break between them?  can you update your first desription in this issue to what you want to appear on the website as that's what gets pulled in for your talk description. 

How are you for next week Wednesday's (24 Aug)  meetup?

**Comment by bernardbaker** [comment]
Next week Wednesday is ok.

**Comment by admataz** [comment]
great  - confirmed!

**Comment by jkbits1** [comment]
This looks fantastic
