### ISSUE TITLE
What learning to code in 12 weeks really means

### ISSUE THREAD

**Issue by michaellennox** [lnug/speakers#68]
With Makers Academy currently hosting LNUG I thought it might be a great chance to give a talk to cover a few things about it including:
a) what a bootcamp is, 
b) what they teach, 
c) what is actually meant by the concept of 'learning to code in 12 weeks',
d) what it feels like as a student to push yourself to go from very little coding capacity at the start to being able to write, test and deploy applications 3/4 months later,
e) the contrast between CS and bootcamp style education and why there is such a demand for alternate education sources in the current market

I would be very interested in giving a talk of how Makers Academy has shaped my transition from a very different career path into a junior developer passionate about what I do. The talk would be rather technology agnostic, although node is one of the technologies I have had the pleasure of working with (and had to get to grips with very rapidly during a craft-a-thon), it would be much more based around trying to let people know about the trials and tribulations of the Makers Academy student journey.

I'm Michael, a junior developer who's just finished here at Makers
You can learn a little more about me at [michaellennox.me/blog](http://www.michaellennox.me/blog/)

**Comment by iancrowther** [comment]
love this.. thanks for the subission

**Comment by michaellennox** [comment]
That's great, April should be fine. Looking forwards to it.

**Comment by iancrowther** [comment]
done, your locked in for April

**Comment by admataz** [comment]
Hi @michaellennox  -  what size LNUG tshirt do you want?

**Comment by michaellennox** [comment]
Ooo a tshirt, small or medium should be great @admataz
