### ISSUE TITLE
NoSQL is a lie

### ISSUE THREAD

**Issue by ukmadlz** [lnug/speakers#70]
NoSQL is a term on the rise, and it's a lie. NoSQL is a catch-all term and I will point out why a catch all means missing tools that may help solve your problems. Going through a few popular DB's we will walk through the use cases and why they're good at what they do.

Job: Developer Advocate @ IBM Cloud Data Services
Twitter: @ukmadlz

**Comment by iancrowther** [comment]
@ukmadlz - super star :-)
