### ISSUE TITLE
Microservices development in node.js

### ISSUE THREAD

**Issue by pelger** [lnug/speakers#71]
**Abstract:**
Whilst micro-service based architectures promise many benefits in production, such as rapid continuous deployment cycles. Current developer tools are lagging behind. Irrespective of platform our current toolchains are very much oriented around the construction of monolithic application stacks and are unwieldy and cumbersome when applied to micro-service based systems. This talk will demonstrate a dynamic and responsive developer toolchain for micro-services implemented in and targeting node.js, that is more aligned with this architectural style. This talk will cover the tools that nearForm use to develop micro-services in the wild, something we've discovered and iterated on over the last three years.

**Bio**
Peter Elger is Director of Engineering with nearForm, a Node.js consultancy - http://nearform.com.
Formerly a physicist working on the JET nuclear fusion research project, Peter has been co-founder 
and CTO of two companies prior to nearForm and holds degrees in theoretical physics and computer science. Based in Ireland, Peter has spoken and run workshops at many international conferences including, Node Interactive, nodeConfEU, Node Summit, node day (NYC), DevOpsCon, JS Conf.
Twitter: @pelger

**Comment by jkbits1** [comment]
Sounds great, I'm very keen to hear this :+1:

**Comment by rdquintas** [comment]
Indeed. This will be super awesome. 
Looking foward.

**Comment by iancrowther** [comment]
its a bit last minute, but are you free next week?

**Comment by pelger** [comment]
Yes free next week!

**Comment by iancrowther** [comment]
Confirmed

**Comment by pelger** [comment]
Awesome :)
