### ISSUE TITLE
Infinitely scalable chat

### ISSUE THREAD

**Issue by nelsonic** [lnug/speakers#72]
Last month @tanzim *introduced* you to AWS Lambda ... 
this time we're going to *show* you how to build a chat/messenger app that scales to ***hundreds of thousands of messages per second*** without deploying a single Docker Container or manage a Database. 

Overview
+ Instead of using a (*traditional*) Node.js Web Server, we'll be using Lambda Functions. (*Don't worry, its still node.js*...)
+ Instead of a (*traditional*) Database, DynamoDB.
+ Instead of Pub/Sub and Socket.IO we will use [AWS SNS](https://aws.amazon.com/sns/)
+ If there's time we can also show how to do Facebook/Twitter/Google Auth using [AWS Cognito](https://aws.amazon.com/cognito/)

We will be writing the code for the app over the next couple of weekends. 
It will be similar to our previous demo app: https://github.com/dwyl/hapi-socketio-redis-chat-example
in that there will be ***end-to-end tests*** *and* ***detailed documentation***, but that's where the similarity ends!

During the talk we will do a full stack/code/deployment walkthrough (*aprox 15 mins*)
and then do AMA/Q&A (*5 mins*)

We already have *extensive practical* notes on using AWS Lambda: https://github.com/dwyl/learn-aws-lambda ... these are going to be expanded into an end-to-end tutorial which *everyone* can follow. 

If you are *curious* about the *future* of web apps, give us a thumbs up.

**Comment by rdquintas** [comment]
This sounds awesome Nelson!

"alta cena" ;o)

**Comment by jkbits1** [comment]
sounds good :smile:

**Comment by iancrowther** [comment]
hi @nelsonic - can you do this in April? We have just had a slot open up

**Comment by nelsonic** [comment]
@iancrowther sure. :+1:

**Comment by iancrowther** [comment]
locked in..

@simonmcmanus we can redeploy the hounds

**Comment by tanzim** [comment]
@nelsonic drat, just realized that I'll be out of town on the week of 27th. Was looking forward to it!

**Comment by nelsonic** [comment]
@tanzim will share the notes with you and we can chat when you get back. :wink:

**Comment by iancrowther** [comment]
It'll be recorded and live streamed!

**Comment by admataz** [comment]
Hey @nelsonic  - what size LNUG  tshirt do you want?

**Comment by nelsonic** [comment]
Hi @admataz only saw this now. sorry too many GitHub notifications... already have an LNUG T-Shirt. Thanks again for co-organising last night. 👍
