### ISSUE TITLE
Declaratively mocking HTTP

### ISSUE THREAD

**Issue by alexjeffburke** [lnug/speakers#73]
I am a co-maintainer and the second largest contributor to an open source library named [unexpected-mitm](https://github.com/unexpectedjs/unexpected-mitm). This is a plugin for [Unexpected](http://unexpected.js.org), an extensible assertion tooklit, which enables HTTP mocking using declarative descriptions written in plain JavaScript. Unexpected itself is an open project is supported by a small but growing community. MY goal would be to give a basic introduction to Unexpected assertion syntax, some elements of it's extension API and combine those with an introduction to the functionality in unexptected-mitm.

My name is Alex J Burke, I currently work as the Lead Platform Developer at a small company in London. I have worked on node the node platform building web application backends and associated software from version 0.6 onwards. I've a Computer Science degree from King's College London and lived for three years in Copenhagen where for a time I worked for a medium size web hosting firm. My handle around the internet is alexjeffburke.

**Comment by iancrowther** [comment]
Hi Alex,

Looks like a great talk to me.

Proposing May?

**Comment by alexjeffburke** [comment]
Hey Ian,

Appreciate your looking at this and provisionally that sounds good - just want to double check the date that'll end up being in May?

Thanks, AJB.

**Comment by iancrowther** [comment]
May 25th, that ok?

**Comment by alexjeffburke** [comment]
Definitely, put me down! :)

**Comment by iancrowther** [comment]
Locked in
