### ISSUE TITLE
Building Complex SPAs with React and ESP

### ISSUE THREAD

**Issue by KeithWoods** [lnug/speakers#74]
What does it take to build a complex single page application (SPA)? How do you model state in a way that can be reasoned with yet scales with functionality and remains maintainable? How do you separate your view code from your state and update state in a deterministic manor? We'll answer these questions using a real world open source sample application, [Reactive Trader](https://github.com/AdaptiveConsulting/ReactiveTraderCloud), build on [React](https://facebook.github.io/react/) and Evented State Processor ([esp-js](https://github.com/esp/esp-js)).

Keith Woods has been working in the city for several years on real time push based FX trading platforms.
Consulting at various banks he has helped developed some of the worlds leading FX platforms using a range of differing technologies (including .Net, Java and JS). He works right across the stack. He is the author of ESP ([esp-js](https://github.com/esp/esp-js), [esp-net](https://github.com/esp/esp-net)), build to solve complex state modelling problems.

**Comment by jkbits1** [comment]
state modelling sounds interesting :+1:

**Comment by KeithWoods** [comment]
Great :) Would love to talk about it. This would be the first public talk where ESP is mentioned, I've used the pattern at various banks and at Adaptive (my current gig). It's now used on several projects (both .net, JS and TypeScript). Would be nice to get it out to the broader community. 

Similarly we've (at Adaptive) not really publicly talked about the latest version of [Reactive Trader](https://github.com/AdaptiveConsulting/ReactiveTraderCloud) (other than a mention at QCon). It's getting some final cleanup work which should be done and dusted in time for a LNUG talk. It'll be a great ES6/Webpack/React/ESP real world reference implementation.

The above said, the talk would focus more on general GUI problems with state management and how you can use modelling and a deterministic workflow to solve these. Esp and Reactive Trader are more supporting the core concept.

**Comment by rdingwall** [comment]
Yes! Would love to see a talk about ESP 👍

**Comment by admataz** [comment]
Hi @KeithWoods  - putting you in for the next available speaker slot on June 22nd  - can you let me know how that works for you?

**Comment by KeithWoods** [comment]
Fantastic that date sounds good to me.
