### ISSUE TITLE
LNUG May lineup

### ISSUE THREAD

**Issue by admataz** [lnug/speakers#76]
Hi @alexjeffburke, @theninj4, @srounce  and @tanzim

Seems we have a lineup of 4 speakers instead of our usual 3 for May (we're not sure how this happened)

First-off - would any of you _prefer_  [June 22nd](https://github.com/lnug/speakers/milestones/June%2022nd%202016)?  - if so, let me know, and we can shift your talk. 

Otherwise, can you let me know how long your talks are? If we have a couple shorter than 20 mins we could possibly squeeze you all in. 

Failing that - we will discuss a plan among the @lnug/organisers and let you know - things may need to get shuffled!

Best, 
@admataz

**Comment by tanzim** [comment]
@admataz I won't be able to do 22nd June. It's either May or July and afterwards for me. 
T

**Comment by theninj4** [comment]
I'm happy to move to June if it helps keep things simple.


Oli

**Comment by admataz** [comment]
Thanks Oli, you're now on for June. That's a great help.

**Comment by admataz** [comment]
Hi Oli
We've had a speaker drop out due to work pressure. Would you like to speak at tomorrow's meetup? 

If you can let me know - and I canl send out a mailshot  this morning with the update

cc. @clarkie @iancrowther @theninj4

**Comment by theninj4** [comment]
Sorry @admataz it's too short notice, I can't do it.

**Comment by admataz** [comment]
ok thanks Oli - no worries - was worth a shot.

**Comment by alexjeffburke** [comment]
Hey, I don't know if this is useful (or desired), by I could probably add a few live examples at the end of mine. Have practiced at 20 but 5-10 extra minutes could buy that or some Q/A. Alex

**Comment by admataz** [comment]
Thanks Alex - great  - 5-10 minutes of live examples would be good thanks!
