### ISSUE TITLE
AVA: Futuristic JavaScript test runner

### ISSUE THREAD

**Issue by novemberborn** [lnug/speakers#77]
AVA is a futuristic JavaScript runner. It's designed to make testing easier and perhaps even fun. Let's talk about its design philosophy, some of it's powerful features and what's next.

---

I'm Mark, member of the AVA core team. I try and spend my time doing Node/JavaScript contracting and open source work.

**Comment by novemberborn** [comment]
Please note that I can't make it for the August meetup.

**Comment by iancrowther** [comment]
Hey @novemberborn,

I have proposed this talk for July, how does that fit?

**Comment by adrianblynch** [comment]
👍 x 10

Shout if you need a proof reader or help in any way?

**Comment by novemberborn** [comment]
@iancrowther yea that should work. Was concerned about it being too close to the FullStack conference but I've got two weeks to prepare the LNUG talk after that.

**Comment by iancrowther** [comment]
locked in :-)

**Comment by admataz** [comment]
Hi @novemberborn - just so we don't have any surprises - can you confirm all is OK for later this evening?

**Comment by novemberborn** [comment]
@admataz 👌

**Comment by alexbooker** [comment]
Excited to see this talk tonight ✨
