### ISSUE TITLE
Node.js on Google Cloud

### ISSUE THREAD

**Issue by meteatamel** [lnug/speakers#78]
In this session, I will show how to deploy your Node.js app to Google Cloud, talk about versioning and traffic splitting for your Node.js app, portability with Docker and if there's time, briefly talk about live debugging and tracing using Stackdriver.

I'm a Developer Advocate at Google for Google Cloud Platform. @meteatamel

**Comment by meteatamel** [comment]
Note, I'm requesting to talk for July's event.

**Comment by admataz** [comment]
sounds great @meteatamel  - have added you to July's schedule

**Comment by meteatamel** [comment]
Thanks!

**Comment by admataz** [comment]
@meteatamel  - can we confirm are you are able to speak at this month's meetup?

**Comment by meteatamel** [comment]
July 27th correct? Sure, yes.

**Comment by admataz** [comment]
Thanks!  - I've added you to the speakers for the 27th. Let us know if you need anything for your talk. If you have slides you want to show on your laptop, can you bring an HDMI adaptor to be sure we can plug you in?

**Comment by admataz** [comment]
Hi @meteatamel - just so we don't have any surprises - can you confirm all is OK for later this evening?

**Comment by meteatamel** [comment]
Yes, I'll be there by 6:30pm. Do you guys have reliable WiFi or shall I not assume it? Also, when does the meetup usually end so I can plan my travel accordingly? Thanks.

**Comment by admataz** [comment]
Hi @meteatamel  - the wifi is generally quite good - speakers often do live demos without any problem. That said - it's always good to have a backup! We usually finish around 9pm, and go on for a drink at the nearby pub afterwards - if you want to join us and stay as late as you like!
