### ISSUE TITLE
Event Driven Architecture

### ISSUE THREAD

**Issue by gnugat** [lnug/speakers#79]
When [Node.Js](https://nodejs.org/en/) says "```event-driven, non-blocking I/O```", have you ever felt it was some sort of black magic? Well in this talk we'll [make the magic go away](https://blog.8thlight.com/uncle-bob/2015/08/06/let-the-magic-die.html) by implementing our own simple HTTP server, Event Loop, Scheduler, Deferer/Promise and [Thread Pool](http://screencrush.com/442/files/2016/02/deadpool-2-boyfriend-pic.jpg?w=720&cdnnode=1).

Oh, Hi by the way! I'm Loïc (it's pronounced Low-ic), a "Lead Engineer" (read Lead Dev) at [Constant Commerce](http://constant.co/). You'll find that I [tweet](https://twitter.com/epiloic) and [blog](http://gnugat.github.io/) a lot about tech. I aslo [contribute a bit](https://github.com/gnugat) to FOSS projects.

**Comment by admataz** [comment]
Hi @gnugat 
This looks good - I'd like to hear your talk. How are you for next month (August 24th) ?

**Comment by gnugat** [comment]
Hi @admataz, thanks for considering my talk, unfortunately I'll be away on the 24th of August. Are there any other available schedule?

**Comment by admataz** [comment]
Hi @gnugat  - of course. How are September 28th or October 26th?

**Comment by gnugat** [comment]
I should be available on both dates :)

**Comment by admataz** [comment]
Great! Have added you to the August schedule - we can confirm again closer to the time.

**Comment by gnugat** [comment]
Sorry, I meant I'm available on the 28th of September and on the 26th of October, I'm still unavailable for the 24th of August 😉

**Comment by admataz** [comment]
Sorry - my mistake - I meant to add you to September... done now.

**Comment by gnugat** [comment]
No worries, thank you :)

**Comment by clarkie** [comment]
Hi @gnugat, just checking you're still on for September's meetup?

**Comment by gnugat** [comment]
More than ever!

**Comment by clarkie** [comment]
Great, we'll see you there!

**Comment by admataz** [comment]
Hi @gnugat 

Just confirming you're all OK for Wednesday? Is there anything you need for your talk? Just to be safe - if you have an adaptor for your laptop to plug in to the projector, can you bring it along?

See you there! I will be there  at Makers from about 5:30pm.

**Comment by gnugat** [comment]
Hi @admataz, everything's OK for Wednesday, thanks for asking.
I'll be showing the slides from a PDF on my laptop (just to be safe I'll bring a USB stick with a copy of it), which has a HDMI port. Do I need a VGA to HDMI adaptor?
Also, out of curiosity, do you know if the talk will be recorded? Thank you very much.

**Comment by jkbits1** [comment]
the hdmi port is fine :+1:  We may be recording this month, but it's not definite

**Comment by gnugat** [comment]
Thanks for replying so quickly :+1: .
By the way I should get to the venue around 6pm, see you there!

**Comment by jkbits1** [comment]
Great, see you at 6 :smile:

**Comment by clarkie** [comment]
@gnugat are you here? Please make yourself known to someone at the front. Thanks

**Comment by gnugat** [comment]
Sorry, I should have signaled myself much earli
