### ISSUE TITLE
Node.js, the Web and the IoT

### ISSUE THREAD

**Issue by domguinard** [lnug/speakers#80]
Everyone talks about the Internet of Things, but the lack of interoperability in the IoT today means what we really have is a series of isolated "Intranets of Things". This fragmentation and the high costs of integration required to overcome it, shows that we're failing to realize the full potential of the IoT.

Just like the Internet needed the Web to become successful, the Internet of Things needs an application layer to truly blossom. The Web of Things (WoT) approach offers a compelling solution to this problem. The core of the Web of Things (http://webofthings.org) approach is quite simple: why don't we re-use Web standards to build the APIs of Things?

In this talk I'd like to introduce a book we just published at Manning press (http://book.webofthings.io) on how to build an open IoT using Web technologies. The talk will look at the layers of integration to the Web, from IoT networks, to Web APIs, the semantic Web and the programmable Web all of this illustrated with Node examples (as the book is based on Node.js code for the Raspberry Pi).

About me:
Twitter: @domguinard and @webofthings
CTO and co-founder @EVRYTHNG
http://dom.guinard.org

**Comment by jkbits1** [comment]
I'm interested to hear about the use of Nodejs on IoT devices

**Comment by admataz** [comment]
Hi @domguinard  - this sounds great...  we'd love to hear more. How long would your talk be? We have a slot available for this month's meetup (next week on 27th) if you're ready? Let me know!

**Comment by domguinard** [comment]
Hi, 27th works perfectly for me, I can be ready by then. I would need along the lines of 20 mins if possible.

**Comment by admataz** [comment]
great - thanks - confirmed - I'll be sending out a newsletter later today - so can include your talk

**Comment by admataz** [comment]
Hi @domguinard  -  just so we don't have any surprises - confirming you are all OK for later this evening?

**Comment by domguinard** [comment]
Thanks for the great evening, what a nice community, long live LNUG :)
Please find my slides here: http://www.slideshare.net/misterdom/nodejs-the-web-and-the-iot
