### ISSUE TITLE
Harnessing the full power of Redis

### ISSUE THREAD

**Issue by dmagliola** [lnug/speakers#81]
The vast majority of projects use Redis like it's Memcached, but Redis can give so much more. In this talk I'll give practical examples of use cases where Redis, with its very particular set of skills, outshines everything else I've tried.

Bio:
Daniel Magliola has been writing code since he was 7 years old, professionally since 16, and through those years has dabbled in multiple technologies. These days you'll find him trying to extract every last bit of performance out of web applications.

[Portfolio / Bio / CV / about me](http://danielmagliola.com/)

Note on length: 
I *can* fly through this talk in 25 minutes, I can probably also shorten it a bit more and do it in 20 (with no time for Q&A), but it's really a whirlwind. If I could have 30 or more that'd make it a lot more understandable by the audience :-)

Note on dates: 
I can do August, but not September unfortunately.

**Comment by simonmcmanus** [comment]
Sounds good to me. 👍

**Comment by dmagliola** [comment]
Excellent, thank you for the very quick response!
Does that mean it's confirmed for August?

**Comment by iancrowther** [comment]
Certainly does 👍 

You'll be on the updated website

**Comment by dmagliola** [comment]
Excellent, looking forward to it!
Could you confirm how much time I can get for it?
Thank you

**Comment by dmagliola** [comment]
Hi,
Could you please confirm if i'd be able to have 30 minutes for the talk?
Thank you

**Comment by jkbits1** [comment]
@dmagliola thanks for prompting us. We're just double-checking on the time available for everyone.

**Comment by jkbits1** [comment]
@dmagliola 30 minutes will be fine, looking forward to the talk

**Comment by jkbits1** [comment]
@dmagliola we're looking forward to your talk tomorrow. The first talk begins around five past 7pm. You can turn up from about 6'ish if you want to check through setting up etc. Did you have a preference for being the first or second talk?

**Comment by dmagliola** [comment]
Looking forward to it! Will try to turn up shortly after 6pm.
I don't have a  huge preference, really, although being second might leave a bit more time for Q&A if there are questions?
But up to you / the other presenters really.

**Comment by jkbits1** [comment]
Great, I'll be there a little before 6. I saw in the comments above that you need some Q&A time, so we'll make sure you get that whichever slot you take
