### ISSUE TITLE
Ace JavaScript Interviews: Scoping and Hoisting

### ISSUE THREAD

**Issue by foxreymann** [lnug/speakers#82]
Back to basics of JavaScript. Informative, interesting and entertaining talk. Great knowledge refreshment for those who know JavaScript. Essential education for those who never learned JavaScript properly.

Node.js Developer. Web Development Trainer. Looking for new opportunities. @foxreymann

**Comment by foxreymann** [comment]
I already gave this talk on London Ember Meetup. Here is the video https://vimeo.com/178828817

**Comment by foxreymann** [comment]
I'm free to speak on Wednesday

**Comment by simonmcmanus** [comment]
Hey @foxreymann,

Can you do September?

Cheers

**Comment by foxreymann** [comment]
@simonmcmanus Yes, I probably can do September. Not 100% sure as I don't know where I will be working then. ATM I'm just freelancing from home so have plenty of time. But if August is not good then I'm ok with September.

**Comment by simonmcmanus** [comment]
@foxreymann, unfortunately, our slots are taken this month.  I will confirm you for September, if anything changes please let us know.

**Comment by foxreymann** [comment]
@simonmcmanus Of course I will keep you updated, I won't forget about LNUG;)

**Comment by admataz** [comment]
Hi @foxreymann 
Just confirming you're all OK for Wednesday? Is there anything you need for your talk? Just to be safe - if you have an adaptor for your laptop to plug in to the projector, can you bring it along?

See you there! I will be there  at Makers from about 5:30pm.

**Comment by foxreymann** [comment]
Yo @admataz. I'm ok for Wednesday. I don't have an adaptor, I have Xubuntu laptop with VGA and mini display port, so should be ok.
