### ISSUE TITLE
Quick wins with node and Google AMP

### ISSUE THREAD

**Issue by mikemaccana** [lnug/speakers#83]
Google's Accelerated Mobile Pages (AMP) is a subset of HTML designed to load as quickly as possible. AMP pages keep your users happy, get you higher in search engine results pages, and related features like structured data can get you right to the top. Here's how a little node engineering can mean more money in your pocket. 
# Talk Description

What AMP is:
- What you gain (pagerank, content previews inside Google search, low latency)
- What still works and what breaks (analytics, conversion tracking etc support is still ongoing)

Implementing AMP in a node app:
- Creating an AMP version of your existing layout
- Converting output from your existing template engine to AMPHTML via server-side DOM manipulation
- Handing analytics in an AMPHTML world

I've written and Open Soured some express-compatible middleware to make this job easier, see https://www.npmjs.com/package/amps-in-the-trunk
## Bio

Mike MacCana is the founder of CertSimple, a startup that provides EV HTTPS certs - the ones where they check who you are - 40-500x faster than it's competitors. He's previously built web apps for Google, Adobe and Microsoft.

**Comment by clarkie** [comment]
Hi Mike, thanks for submitting this. How are you fixed for speaking in October? We have an event lined up on the 26th.

**Comment by mikemaccana** [comment]
October 26th is fine!





On Mon, Aug 29, 2016 at 2:38 PM +0100, "Clarkie" <notifications@github.com> wrote:












Hi Mike, thanks for submitting this. How are you fixed for speaking in October? We have an event lined up on the 26th.

**Comment by clarkie** [comment]
Thanks Mike, you're all booked in.

**Comment by mikemaccana** [comment]
Thanks Clarkie, looking forward to it!

**Comment by clarkie** [comment]
Hi @mikemaccana, just wanted to check you're still on for Wednesday night?

**Comment by mikemaccana** [comment]
Yep! See you then! 👍

Get Outlook for iOS




On Sun, Oct 23, 2016 at 4:52 PM +0100, "Clarkie" <notifications@github.com> wrote:












Hi @mikemaccana, just wanted to check you're still on for Wednesday night?

**Comment by mikemaccana** [comment]
FYI https://lnug.org/ has a somewhat garbled version of my talk.

Should just be:

*Abstract *Google's Accelerated Mobile Pages (AMP) is a subset of HTML
designed to load as quickly as possible. AMP pages keep your users happy,
get you higher in search engine results pages, and related features like
structured data can get you right to the top. Here's how a little node
engineering can mean more money in your pocket.

*Mike MacCana* is the founder of CertSimple, a startup that provides EV
HTTPS certs - the ones where they check who you are - 40-500x faster than
it's competitors. He's previously built web apps for Google, Adobe and
Microsoft.

**Comment by mikemaccana** [comment]
A link to https://certsimple.com would be rad too!

**Comment by mikemaccana** [comment]
And twitter.com/mikemaccana !

**Comment by mikemaccana** [comment]
On my way now BTW!
