### ISSUE TITLE
How to build a RESTful API

### ISSUE THREAD

**Issue by lazlojuly** [lnug/speakers#84]
Talk agenda:
1. The REST Design
2. Specification
3. Mocking
4. Testing

This talk will also look at some popular API tools.

Bio: I am a JavaScript Engineer. Connect with me on [Twitter](https://twitter.com/lazlojuly), [LinkedIn](https://www.linkedin.com/in/lazlojuly) or [GitHub](https://github.com/lazlojuly)

**Comment by clarkie** [comment]
Booking you in for October 26th.

**Comment by lazlojuly** [comment]
October 26th is perfect. Thanks!

**Comment by clarkie** [comment]
Locked in!

**Comment by jkbits1** [comment]
@lazlojuly hi, thanks for the update :+1: if you think the revisions make for a better talk, go ahead

**Comment by clarkie** [comment]
@jkbits1 how do we get the site updated?

**Comment by admataz** [comment]
@clarkie, @lazlojuly  once you update the talk proposal in the initial comment in this ticket, you  should be able to update by checking out the website repos - running `npm build` and commiting/pushing again  - I think it's all in the readme for the site. I'd do it for you but I'm on the go and away from my desk the next couple days.

**Comment by simonmcmanus** [comment]
@clarkie @admataz - site should be updated now.
