### ISSUE TITLE
Write More Resilient JavaScript with Flow

### ISSUE THREAD

**Issue by bookercodes** [lnug/speakers#85]
**Abstract**

Flow is a static type checker for JavaScript (an otherwise dynamically-typed language). You can think of it as a productivity tool that catches common errors _before_ they run. 

Take the infamous "'Undefined' is not a function" error as an example. When writing vanilla JavaScript, you would have to wait until runtime to receive this arduous error. Flow - on the other hand - integrates with your favorite editor and analyzes the correctness of your code as you write it. If you were to reference a non-existent function, Flow would not only tell you immediately but also provide additional context that makes the error easier to fix.

Whilst Flow is predominantly used with front-end technologies like React, I have been using it with great success for my Node.js projects and in this talk, I'll not only show you how to get up and running with Flow, I'll also share my experience with you. I'll also take a moment at the end of my talk to touch on the differences between Flow and TypeScript.

**Alex Booker**

Alex Booker is a Developer Advocate at [Pusher](https://pusher.com/). There, he spends his time learning and writing about interesting, emerging technologies, and representing Pusher at events around the world. In his spare time, he runs a YouTube channel called [Code Cast](https://www.youtube.com/c/codecast) where he uploads educational screencasts about Linux and JavaScript. You can find him on Twitter [@bookercodes](https://twitter.com/bookercodes).

**Comment by alexbooker** [comment]
I came to LNUG in July, met some awesome people and _really_ enjoyed the talks 😄 

It would be great to speak there myself (my first public talk actually!). Please let me know what you think!

**Comment by clarkie** [comment]
Hi @alexbooker, thanks for submitting your talk proposal, it sounds great. Can we provisionally book you in for our October event on the 26th? Thanks, Clarkie

**Comment by alexbooker** [comment]
Sounds good to me, @clarkie. Thank you!

**Comment by clarkie** [comment]
Perfect! You're booked in.

**Comment by clarkie** [comment]
Hi @bookercodes just confirming you're still ok for Wednesday night?

**Comment by bookercodes** [comment]
@clarkie Of course 😄
