### ISSUE TITLE
A year with AWS

### ISSUE THREAD

**Issue by clarkie** [lnug/speakers#86]
Moving from a company where everything ran on 'bare metal' in a DC on Goswell Road to a startup where everything was already running in AWS has proven to be an interesting learning curve.
This talk will take you through some of my learnings along the way and some of the ways we use bits of the AWS toolkit now at Tido. 

Clarkie
CTO @ [Tido](http://tidomusicapp.com/)
@clarkieclarkie

**Comment by admataz** [comment]
Hey @clarkie  - you up for a January 25th talk?

**Comment by clarkie** [comment]
Yeah definitely!
