### ISSUE TITLE
1. Keep calm and curry on

### ISSUE THREAD

**Issue by cullophid** [lnug/speakers#87]
In this first talk we will look at the fundamental principles that underpin the functional programming paradigm.

We introduce some of basic techniques that makes functional programming so powerful. 
These are techniques you can easily apply to your codebase to increase readability and reusability.

Andreas Møller is a London based full stack JavaScript developer. Andreas splits his time between contracting and his role as CTO of his analytics startup Sentia.

**Comment by clarkie** [comment]
As discussed I've scheduled yous all in for November 23rd. Can you confirm on here that you're all ok with this date? Thanks

**Comment by cullophid** [comment]
@clarkie  november 23 is Perfect!

**Comment by clarkie** [comment]
@cullophid just confirming you're still on for Wednesday?

**Comment by cullophid** [comment]
Hey Yes we are all still in :)
