### ISSUE TITLE
3. Readable Microservices, with functional programming.

### ISSUE THREAD

**Issue by jc888** [lnug/speakers#88]
In the final talk James Chow will talk about how the principles 
of functional programming aligns itself with modern distributed architectures.
Join him as he builds a fully functional microservice application
using our new functional programming toolbox. James shows us how all the various
parts of functional programming comes together to create safe efficient code
that is easily readable and extendable. 

James chow has been a software contractor for over 10 years.  He is currently Devops Engineer for Discovery where he manages Infrastructure, and advises on constructing applications.

**Comment by clarkie** [comment]
As discussed with Andreas I've scheduled yous all in for November 23rd. Can you confirm on here that you're all ok with this date? Thanks

**Comment by jc888** [comment]
Confirmed, thanks!

**Comment by clarkie** [comment]
@jc888 just confirming you're still on for Wednesday?
