### ISSUE TITLE
2. Null Can't Hurt You Anymore

### ISSUE THREAD

**Issue by svozza** [lnug/speakers#89]
This talk follows on from @cullophid's session and seeks to build on those foundations with larger abstractions that can help developers to avoid common pitfalls when writing JavaScript such as null references (`Maybe`s), uncaught exceptions (`Either`s) and asynchronous control flow (`Future`s). These abstractions help to encapsulate uncertainty allowing us to code the happy path whilst ultimately enforcing the handling of error conditions and as the data types all share a common interface it allows us to compose them in predictable ways.

Stefano Vozza is a tech lead at Trinity Mirror and has a keen interest in functional programming, DevOps and continuous delivery. He is a main contributor to several open source Javascript FP libraries such as [Sanctuary](https://github.com/sanctuary-js/sanctuary), [date-fp](https://github.com/cullophid/date-fp) and [Highland](https://github.com/caolan/highland).

**Comment by clarkie** [comment]
As discussed with Andreas I've scheduled yous all in for November 23rd. Can you confirm on here that you're all ok with this date? Thanks

**Comment by svozza** [comment]
Yep, that's fine for me

**Comment by clarkie** [comment]
@svozza just confirming you're still on for Wednesday?

**Comment by svozza** [comment]
Yep,  I am!
