### ISSUE TITLE
Docker Inside/Out: the ‘real’ real-world of stacking Node.js containers in production

### ISSUE THREAD

**Issue by kamerblauwlicht** [lnug/speakers#90]
Did you’ve already containerized the shit out of your `Node.js` code, broken down monoliths, microserviced the hell out of your app and have run some awesome workloads in your local, dev and test environments. It’s all looking good, but now what?

Running `Docker` on your local box is one thing, but maintaining containers in production is a whole other ballgame. So during this talk, I’ll show you the REAL wild world of Docker in production. With the added benefit of talking to and observing how over 900 of our customers have been using Docker in production for Node, I’ll be presenting some of these data points and sharing our observations on how to get it right. 

My aim? I want to turn the conversation on its head and dispel some of the ‘silver bullet’ assumptions flying around by taking an inside-out approach to building with Docker. The idea is to provide you with a framework for how to get your code into containers, streamline the Docker build flow and avoid common pitfalls when moving from dev to live environments.

Because remember, Docker will NOT, and I repeat, will not solve your bad dev and ops behaviours. So don’t end up with a ‘hot mess’ (more on that later).

**Daniël van Gils** is a polyglot developer advocate at [Cloud 66](https://www.cloud66.com). He helps other developers craft web applications and container based microservice architectures with ♥. An accomplished creative technologist, Daniel has vast and varied experience in application development, agile workflows and building container technologies at scale, gained working in the web development, creative technologies and gaming industries. In his spare time he experiments with strawberries in his backyard, likes to surf and practices improvisation theater.

**Comment by kamerblauwlicht** [comment]
hi @clarkie! my colleague Kasia already talked to you about this talk. let me know if it fits your 23th of November schedule.

**Comment by admataz** [comment]
Hi @kamerblauwlicht  - we have a full schedule for November already - any chance we could put this off to the new year (we don't meet in December)

**Comment by admataz** [comment]
Hi @kamerblauwlicht  - would you be interested in speaking on January 25th?

**Comment by admataz** [comment]
Hi @kamerblauwlicht  - we have speaker slots available for later this month - if you still have a talk here?
