### ISSUE TITLE
GraphQL: an API convention that you will actually follow

### ISSUE THREAD

**Issue by clementhannicq** [lnug/speakers#91]
REST is recognized as the "good practice" in terms of web APIs, but can quickly become a hassle as your application grows and evolves.
QraphQL is a new paradigm, allowing developers to request deeply nested information in a single call, without cluttering the response with unneeded fields.
In this talk, I will show how GraphQL overcomes the rest limitations to send only the information a caller wants, without changing anything on your backend.

I am currently working at Theodo (http://www.theodo.co.uk/) and have been for the past 18 months, as a fullstack developer.

**Comment by admataz** [comment]
hi @clementhannicq  - this looks good - how would you be for January 25th?

**Comment by clementhannicq** [comment]
Hi @admataz, I'll be available on January 25th.
