### ISSUE TITLE
Modelling with Pencils (and JavaScript)

### ISSUE THREAD

**Issue by jonnyarnold** [lnug/speakers#92]
*Abstract*

Often the work of a software developer is to write down complicated things in an unambiguous way. In this talk I'd like to remind you about mathematical modelling - writing down mathematical relations that approximate a situation - and give a real story about how I should have started with a pencil rather than a keyboard.

*About Me*

[Jonny Arnold](http://jonnyarnold.uk/) has been a software developer professionally for 5 years and  as an amateur for another 5. Having worked with C# and Ruby in the past, Jonny is now using JavaScript to build an online mortgage broker at [Trussle](http://www.trussle.com/).

**Comment by admataz** [comment]
Hi @johnnybridges  - thanks for the talk proposal. Looks like a great approach worthy of a good talk.

How are you fixed for for this month on January 25th?

**Comment by jonnyarnold** [comment]
Unfortunately I can't make that date! How about next month?

(Also, sorry to @johnnybridges who has accidentally joined this conversation! Hope you can come along 😇 )

**Comment by admataz** [comment]
Thanks @jonnyarnold ! I've put you in for 22nd Feb.

**Comment by jonnyarnold** [comment]
Thank you very much :)

**Comment by admataz** [comment]
Hi @jonnyarnold  - hope all is well with you? If you want to run your talk past any of us at LNUG feel free to drop a line - we'd be happy to review and offer pointers.

**Comment by jonnyarnold** [comment]
Thanks! I'll try and get a copy to you before the night...!

**Comment by admataz** [comment]
Hi @jonnyarnold  - just confirming you're all good for Wednesday? We will be setting up from about 6pm - if you can get there so we can test your laptop with the AV set up and the video guy... usually an HDMI output is enough - but bring any adapters you may have for your laptop. Thanks!

**Comment by jonnyarnold** [comment]
Good stuff @admataz - see you there!

**Comment by admataz** [comment]
Hi @jonnyarnold   - thanks for your talk last night - and the scientific approach. I think everyone had a good evening and I had some good feedback on all the talks.  

Could you upload your slides somewhere and add a link here?

**Comment by jonnyarnold** [comment]
No problem - thanks for letting me speak!

The slides are here:

https://docs.google.com/presentation/d/1fffmaV0P_9TjMOhyp0_r9d6saVE3CX3eouEoBINGuz0
