### ISSUE TITLE
 Native app tips to save your sanity

### ISSUE THREAD

**Issue by trevorah** [lnug/speakers#93]
9 months after you’ve started writing a hybrid app, you’re going to stumble across some unexpected native problems that don’t show up in tutorials. This talk will go over these and other oddities that most web developers wouldn’t expect.

Talk includes:
* classic Android and iOS architecture for restful apps
* weird native bugs (with fixes)
* great things that javascript/web should have

I'm Andy Trevorah, app developer for hire.
Twitter: `@trevorah_`
Website: https://trev.sh

**Comment by admataz** [comment]
Thanks @trevorah - scheduled and added to the website and meetup page

**Comment by trevorah** [comment]
🎉
