### ISSUE TITLE
Our future is in little hands

### ISSUE THREAD

**Issue by tonyyates** [lnug/speakers#94]
I am a huge advocate of women in technology, and I am active in the Health Tech Women movement. I think it is essential that we teach children both boys and girls the fundamentals of computing and engineering at an early age.

I practice what I preach with my own daughter who hacked a chromebook at 3 years old. We also took some unique approaches to her homework which she has shared with school.
Basically the aim of my talk is to encourage others to get involved with technology and their children at an early age, they love it more than gazing at iPads too.

I wrote a [blog post](http://www.tonyyates.co.uk/my-3-year-old-daughter-hacked-a-google-chromebook/) which shows one of the many projects we have create. We also done some using nodered, arduiono and shrimpkit which form the basis of my talk.

About Me

[@TonyYates](https://twitter.com/tonyyates) on Twitter
I am currently lead technical architect for NHS.UK, Citizen ID, Personal Health Records, and NHS Public WIFI all these are going through a major transformation at the moment but that is another talk as we use nodejs heavily.

Lover of most technologies (except Ruby, I don't know why), keen cyclist, dad to 3 children under 5 years old so I get little sleep.

**Comment by admataz** [comment]
Hi @tonyyates - this looks good - thanks! 

we discussed it briefly last week in the pub, but the detail escaped me - did you say you were available to talk in February?

**Comment by tonyyates** [comment]
Hi @admataz thank you.

Unfortunately I can't do February as it is my little boys birthday, but can do March.

**Comment by admataz** [comment]
thanks @tonyyates

**Comment by admataz** [comment]
Hi @tonyyates  - are you still ok for March 22nd?

**Comment by tonyyates** [comment]
Hi, yes still good and scheduled in
