### ISSUE TITLE
Promises & Generator in node.js

### ISSUE THREAD

**Issue by TheBenji** [lnug/speakers#96]
As part of ES6 node finally has a native support for promises and generator.
In this talk I'd like to introduce you to the concept and syntax of both, show you some ways you may use them in the real world and give a quick lookout what's up next.

Hey, my name is Ben, I’m a dev from Germany.
The first time I came in contact with code I was probably around 12 years old.
My dad gave me a little model train set and we hooked it up to an old computer so I could program (with QBasic, fun times!) the trains and make them automatically drive around and stop at train stations and fun stuff like that.

By now I learned a little more about software development and worked in a variety of different companies mostly buildings APIs with a node stack in one form or another.

**Comment by admataz** [comment]
Hi @TheBenji  - thanks for your proposal. I agree - there is a lot in ES6 that should get more attention and usage. I'm sure we're not using it to the fullest... This could be a really good talk. 

I think our attendees are varied enough in their knowledge and experience to start basic and get more complex - if you could provide some good practical code examples... Push it a little further than `let`, `const`, and `var` (we had a talk recently that covered lexical scoping and dealt with these concepts quite thoroughly)

It's up to you of course, and you have 20-25 minutes but things I'd like to see explained and demonstrated well: 
- constructing and using promises
-  interesting ways to use the spread operator, rest parameters,  and destructuring to make our node js more expressive and  intuitive to read. 
- a practical  case for generators

And while you're there, maybe touch on the [node's 97% coverage of es6](https://kangax.github.io/compat-table/es6/#node65)  - and maybe give a little nod to the new features in ES2016+ and what to expect at your talk next year 😉 

On a practical note - we have a slot available for the February meetup (next week Wednesday 22nd) - are you able to make that?

**Comment by TheBenji** [comment]
Very good suggestions!

I'd have time on the 22nd but it might get a little tight in terms of actually preparing the talk.
I could put something together over the weekend and would hope that I could ask some of you guys to read over the slides and fix the things I messed up and add some suggestions to add least push it into the direction of a good talk.

Having said that if we can fit the slot otherwise I would be happy to push this one to a later date :)

**Comment by admataz** [comment]
Yeah - I understand it's a bit tight for next week. Totally up to you - we can put you in for March instead if you prefer.

**Comment by TheBenji** [comment]
If it's not too late I'd let you know by Monday?

**Comment by admataz** [comment]
ok cool. let us know how it goes and feel free to send anything over if you want us to take a look and give some feedback.

**Comment by TheBenji** [comment]
So I was going through it over the weekend and I could do it on wednesday however I would rename it to "Promises & Generators in node.js".

Alone the bit about Generators is probably worth 20 minutes but since they are so powerful with promises together I thought going over that as well would make sense.

If you have a minute feel free to read over the slides although I'm not sure how much sense it makes without the notes:
http://slides.com/benjaminaugust/deck#/

It's mostly sample code so if there is something clearly missing (or wrong for that matter) let me know :)

**Comment by admataz** [comment]
Hi @TheBenji 
nice - promises - always bound to get some debate going! leave a bit of time for comment/questions!! 

I like how you are bringing generators and promises together - you probably have it covered in your narrative - but maybe worth talking a little about where you see this being used in the wild - will provide some context outside of the code abstraction. 

Otherwise, in your slides, small typo on http://slides.com/benjaminaugust/deck#/4 ("Rasons" instead of "Reasons").  I didn't notice any other issues  - I get an idea of what you're covering. 

If you can update the title and your talk description in the initial comment for this issue - I will publish it to the website and make an announcement from Meetup tomorrow.... 

Thanks!

**Comment by TheBenji** [comment]
Thanks!

If you happen to have some good examples for real world uses do let me know - there are probably loads of cool things I didn't even think about yet at all.

See you Wednesday then!

**Comment by admataz** [comment]
Hi, off the top of my head i know Koa framework uses generators. i've not used it, but it's considered very fast efficient way to implement express style middleware 

[Koa - next generation web framework for node.js](http://koajs.com/)

will have a think about any other examples. 

thanks for the update, i'll update the schedule today. see you wednesday!

**Comment by admataz** [comment]
Hi @TheBenji   - just confirming you're all good for Wednesday... We will be setting up from about 6pm - if you can get there so we can test your laptop with the AV set up and the video guy... usually an HDMI output is enough - but bring any adapters you may have for your laptop. Thanks!

**Comment by admataz** [comment]
Hi @TheBenji  - thanks for your efforts last night - I think everyone had a good evening and I had some good feedback on all the talks.  

Could you upload your slides somewhere and add a link here?

**Comment by TheBenji** [comment]
Glad to hear that.

Sure, the slides are all available here http://slides.com/benjaminaugust/deck#/

**Comment by admataz** [comment]
HI @TheBenji  - I forgot the quicktime slide recording for the video - can you put it on dropbox or somewhere for me to download? 

Thanks!

**Comment by TheBenji** [comment]
Hey Adam,
I used the mac of the other guy that helped organising (I'm afraid I forgot his name) and we recorded it on his machine so hopefully he still got it...

**Comment by admataz** [comment]
Ok - thanks @TheBenji ! 

@lazlojuly  - I hope you still have this? can you send it  to me?

**Comment by lazlojuly** [comment]
@admataz @TheBenji yes, I have the video! Apologies, I have been busy and forgot to get back to you.

**Comment by admataz** [comment]
@lazlojuly  - just a reminder... when you get a chance.

**Comment by lazlojuly** [comment]
@admataz @TheBenji apologies for the delay: https://drive.google.com/file/d/0Bzh1DHFKrESBbjFjVmVBbVFoYzg/view?usp=sharing

**Comment by admataz** [comment]
thanks!!
