### ISSUE TITLE
Don't Let Just Node.js Take the Blame!

### ISSUE THREAD

**Issue by danielkhan** [lnug/speakers#97]
## Abstract
Most likely you are choosing Node.js because it has the reputation to be super-fast, easy to use and you heard a lot of success stories at meetups and conferences. Sure you did performance and scalability tests which confirmed that your decision was correct to go with Node.js. 

What Daniel has seen is that in enterprise environments Node.js often acts as the (often microservice based) gluing tier that connects legacy services to modern offerings like mobile apps or your HTML5 SPA (Single Page Apps) via a REST API Layer. 

This means that once you integrate your application into the company infrastructure, connect it to internal & external services and go productive you may be the first person to be blamed because "the website is slow" or even better "something broke – there is an error we have not seen before". But who knows if in fact a service consumed or brokered by Node or a database is slow?  In this session Daniel will cover - how to trace down problems inside Node - the challenges operations is facing in todays highly heterogeneous applications - how to protect the boundaries of your service to pinpoint problems in other tiers - new tracing features in upcoming versions of Node.

## Bio
Pragmatic fullstack engineer from BGP to AJAX. Speaker, mentor and course author. I am leading the Node.js technology efforts of Dynatrace. Member of Node.js Diagnostics WG. Let's chat about the old days, todays cutting edge technologies, (web) performance ... you name it.

[@dkhan](https://twitter.com/dkhan) on twitter

**Comment by admataz** [comment]
Hi @danielkhan  - this sounds great - thanks for putting this talk forward. 
I think our members would really appreciate the insights you have and would enjoy this talk... our June meetup would be on Wednesday 28th - would you be able to make that date?

**Comment by danielkhan** [comment]
Hi @admataz - great! yes June 28th works for me.

**Comment by admataz** [comment]
Thanks @danielkhan - added to the schedule. I will check in with you closer to the time...

**Comment by admataz** [comment]
@danielkhan  - just retagging this as it apparently interferes with our automated build script for the website to have a far future approved and scheduled talk. Will retag again closer to June

**Comment by admataz** [comment]
ignore that it was something else breaking the build. sorry for the noise

**Comment by admataz** [comment]
Hi @danielkhan  - I hope all is well with you? Just confirming - are you still able to join us and speak at the meetup on 28th (2 weeks time) 

Looking forward to it!

**Comment by danielkhan** [comment]
Absolutely - I'll be there!

**Comment by admataz** [comment]
Hi Daniel, 

quick note about next Wednesday I've been asked to relay to you... we recently decided to drop Q&A sessions from the talks - so we won't be opening the floor to questions at the end - although we will encourage people to talk to you in the break if they have questions.  The Q&A was always a bit pressured for speakers and often puts them on the spot, while pushing us overtime and so we've decided to try dropping them. 

I hope this suits you? Please let me know if you feel this wouldn't suit your talk..

**Comment by admataz** [comment]
Hi @danielkhan - I hope all is good to go for tomorrow? I assume you'll have any slides on a laptop? Usually we manage to work things out with all the projector adaptors and things for filming and recording the slides - but if you have one for your laptop to HDMI, please bring it in case...

I should be at Makers Academy from about 5:45 to get things set up - but if you arrive earlier, someone from Makers will let you in - just tell them you're there for LNUG.

In case you haven't got the address detail, it's

MAKERS ACADEMY
50 - 52 COMMERCIAL ST
LONDON E1 6LT

My number is 07757234443 if you need to call for anything.

**Comment by danielkhan** [comment]
Hi - all good.
The message just got lost in all those github issues :)
The mode with questions is fin. I have a macbook with HDMI out.

**Comment by admataz** [comment]
Hi @danielkhan 
Great to meet you last night and thanks for the talk - it was a great combination of overview and deep dive, and people really enjoyed the insights . 

Hopefully see you again.  Next time you pass through London - drop us a line and pop in if it coincides with a meetup date. Of course if you develop another talk  - we'd be happy to have you back. 

I'll keep this issue open until the video is finished and uploaded to our YouTube channel, then I'll post the link here.

**Comment by admataz** [comment]
Uploaded the video last week - https://www.youtube.com/watch?v=r1omVx3Phrw

Thanks again!
