### ISSUE TITLE
Fullstack integration testing that doesn't suck

### ISSUE THREAD

**Issue by artemave** [lnug/speakers#98]
With the help of electron, it is now possible to run your entire web stack (SPA + backend) in a single process. When applied to testing, this becomes a compelling alternative to webdriver based testing, as it is much faster and easier to debug.

In this talk, I am going to start with setting some base terminology of what types of tests there are in a typical web app, what they're for and then show off a [real example](https://github.com/featurist/full-stack-js-testing-demo).

My name is Artem Avetisyan. I work at [Featurist](http://www.featurist.co.uk/). We're a small bunch of like minded individuals who believe that Javascript is the one. We're also very serious about testing and we like good tools. Oh, and we're hiring too.

**Comment by admataz** [comment]
Hi @artemave 
compelling indeed! I'd love to hear about this approach to testing 

Are you available to talk later this month - on Wednesday 22nd March?

**Comment by artemave** [comment]
Hi @admataz , 22nd of March sounds good!

**Comment by admataz** [comment]
good stuff! - I'll add you to the schedule.

If you need any input or feedback along the way - feel free to get in touch

**Comment by artemave** [comment]
Awesome, will do.
