### ISSUE TITLE
'Minecraft' in VR in 30 lines of Javascript

### ISSUE THREAD

**Issue by jamesporter** [lnug/speakers#99]
Leveraging A-Frame and React we will discover just how easy it is to build interactive WebVR experiences.

Just as you create web front ends with React you can place images, text and 3D objects in an interactive 3D VR world. We will learn the basics of A-Frame and how React and Modern Javascript allows us to encapsulate and manage the complexities of it; allowing us to quickly create maintainable/extensible Apps and Visualisations.

The talk will be very much focused on the code/running samples (which are available on Github).

It will be a shorter and improved version of part of a workshop [I gave last November](http://lanyrd.com/2016/over-the-air/sfphcd/) 

I'm James Porter [@complexview](https://twitter.com/complexview). I work at Motivii as a polyglot (but often Javascript) developer and data scientist, though a few years ago was an economic researcher. Recently I have been exploring WebVR, React Native and Elm in various side projects.

**Comment by admataz** [comment]
Hi @jamesporter  Thanks for your talk proposal - it sounds really interesting - I love the whole broad idea of alternative renderings from JS... 

Would you be available to speak next Wednesday (22nd March?)

**Comment by jamesporter** [comment]
Yes, thanks @admataz I'm already planning on coming next week.

**Comment by admataz** [comment]
great stuff - thanks...  I'll add you to the schedule.
